### ISSUE TITLE
Latest release does not include compiled artifacts

### ISSUE THREAD

**Issue by corbob** [PowerShell/PowerShellEditorServices#1047]
The build process for [coc-powershell](https://github.com/coc-extensions/coc-powershell) relies on compiled artifacts for PSES. It appears that the latest releases did not include these artifacts. See the difference in assets between https://github.com/PowerShell/PowerShellEditorServices/releases/tag/v1.13.0 and https://github.com/PowerShell/PowerShellEditorServices/releases/tag/v1.12.2

**Comment by TylerLeonhardt** [comment]
oops. Not sure why the zips failed to upload... this should be fixed now!
