### ISSUE TITLE
Improve startup sequence of ProtocolServer implementations

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#106]
Currently when the PowerShellContext starts up, it happens before the Logger has been enabled which means that any log messages written at that point won't be visible in the log file.  Right now I have to initialize an EditorSession in the constructor of both the LanguageServer and DebugAdapter classes so that things are set up before the channel gets started.

We need to fix the current ProtocolServer startup sequence so that everything happens in the proper order when ProtocolServer.Start is called.

**Comment by TylerLeonhardt** [comment]
I'm just going to close this since we've moved to omnisharp.
