### ISSUE TITLE
Hover handler test failing

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#1082]
The hover handler E2E test is failing in the build because the result depends on help being installed:

https://github.com/PowerShell/PowerShellEditorServices/blob/6781b91670a09c6e62766c90492c9b8d56ffd519/test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs#L690-L708

When no help is installed, hover gives back the signature rather than a function description.

**Comment by rjmholt** [comment]
This also affects the completion test:

https://github.com/PowerShell/PowerShellEditorServices/blob/6781b91670a09c6e62766c90492c9b8d56ffd519/test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs#L672-L688

**Comment by TylerLeonhardt** [comment]
Gosh... We can't rely on `Write-Host`?

**Comment by rjmholt** [comment]
From my machine:

```
> get-help write-host

NAME
    Write-Host
    
SYNTAX
    Write-Host [[-Object] <Object>] [-NoNewline] [-Separator <Object>] [-ForegroundColor {Black | DarkBlue | DarkGreen | DarkCyan | DarkRed | DarkMagenta | DarkYellow | Gray | DarkGray | Blue | Green | Cyan | Red | Magenta | Yellow | White}] [-BackgroundColor {Black | DarkBlue | DarkGreen | DarkCyan | DarkRed | DarkMagenta | DarkYellow | Gray | DarkGray | Blue | Green | Cyan | Red | Magenta | Yellow | White}] [<CommonParameters>]
    

ALIASES
    None
    

REMARKS
    Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.
        -- To download and install Help files for the module that includes this cmdlet, use Update-Help.
        -- To view the Help topic for this cmdlet online, type: "Get-Help Write-Host -Online" or
           go to https://go.microsoft.com/fwlink/?LinkID=113426.



```

**Comment by rjmholt** [comment]
Fixed in https://github.com/PowerShell/PowerShellEditorServices/pull/1083
