### ISSUE TITLE
Add build step to put docs into build artefact

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#1090]
I recall there's some documentation like the README or the CHANGELOG that's supposed to be in a build artefact. We should add that as a build step so that no manipulation is needed.

**Comment by rjmholt** [comment]
Ah it might be more than this. I think currently the build produces some files, but they're not packaged as we would release them. We should change what we need to so that build pipeline assets include a ready-to-release artefact.

**Comment by TylerLeonhardt** [comment]
> We should change what we need to so that build pipeline assets include a ready-to-release artefact

Doesn't it already?

**Comment by rjmholt** [comment]
> Doesn't it already?

Something we should verify, if just to confirm that what we release today is exactly the form we think is best. Worth considering what the "release" means for PSES, whether it's a plug and play thing for clients like today, or a nupkg/module, or both, or other things
