### ISSUE TITLE
Enable code navigation and reference searching between files in a module

### ISSUE THREAD

**Issue by kaylaerdmann** [PowerShell/PowerShellEditorServices#11]
Right now there is only multi-file support for the definition and references features when files are dot sourced.

We also want to add multi-file support modules and module manifests.

**Comment by daviwil** [comment]
This should also work for module files in the same project imported via `Import-Module`.  The dsc-azure-ext that @narrieta works on uses this pattern extensively.

**Comment by daviwil** [comment]
I've recently seen the need for this (especially the `Import-Module` usage inside of a project) in the Azure Stack team.  Need to start making progress on this soon.
