### ISSUE TITLE
Feature request: Search box for Powershell Command Explorer pane

### ISSUE THREAD

**Issue by ffcruz85** [PowerShell/PowerShellEditorServices#1154]
Just what the title says, adding a Feature request: Search box for Powershell Command Explorer pane would be really helpful to filter down the huge number of commands. I am referring to the extension used in Azure Data Studio as seen below. Thanks!
![image](https://user-images.githubusercontent.com/2352828/72209798-2c2ba880-3478-11ea-9e61-7789dc1b74fb.png)

**Comment by corbob** [comment]
I think you meant to put this in the vscode-powershell repository. But it was added by vscode in around July: https://github.com/PowerShell/vscode-powershell/issues/1656

**Comment by ffcruz85** [comment]
Ah, you are right - it's just not a traditional search box. Didn't think of just clicking any item and just start typing... well, can't do literal searches, but it's pretty smooth UI wise and does the job. Looks great.
