### ISSUE TITLE
trigger characters should contains `$` too

### ISSUE THREAD

**Issue by mattn** [PowerShell/PowerShellEditorServices#1176]
I prefer to add `$` into triggerChars for variables.

```csharp
        public CompletionRegistrationOptions GetRegistrationOptions()
        {
            return new CompletionRegistrationOptions
            {
                DocumentSelector = new DocumentSelector(new DocumentFilter { Language = "powershell" }),
                ResolveProvider = true,
                TriggerCharacters = new[] { ".", "-", ":", "\\", "$" }
            };
        }
```

![image](https://user-images.githubusercontent.com/10111/73593783-242cc900-454b-11ea-8a21-13efa60ad296.png)

**Comment by SydneyhSmith** [comment]
@mattn thanks for opening this issue, we are having trouble reproducing this...what version of editor services are you running?

**Comment by mattn** [comment]
Possible to reproduce on master branch since `$` is not contained in TriggerCharacters.

https://github.com/PowerShell/PowerShellEditorServices/blob/81ba0c0b8efb7ee879f2ede511390ba73b0bc86e/src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs

**Comment by TylerLeonhardt** [comment]
I wonder if VS Code is sending over the completion request even though it shouldn't... @mattn which client are you using? Looks like Vim or NeoVim?

**Comment by mattn** [comment]
I use vim-lsp on vim8.

**Comment by SydneyhSmith** [comment]
@mattn yeah that looks like a great idea, feel free to open a PR
