### ISSUE TITLE
Debug launch path should use ${file} variable

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#119]
This will allow the user to launch whatever PowerShell script file is active in the editor without having to change the folder's launch.json file.  The user will still be able to set the launch.json file if they *always* want a specific script to start but this default is more useful for the common case.

**Comment by daviwil** [comment]
You should only have make this change in the vscode-powershell code, right?  I think they will give us the resolved file path in the LaunchRequest

**Comment by rkeithhill** [comment]
Yes, I'm too used to doing stuff in this repo and not the other.  Sorry about that.

**Comment by daviwil** [comment]
No problem man!  I forget that there are bugs in the other repo all the time ;)
