### ISSUE TITLE
Switch all CodeActions from Command to CodeAction 

### ISSUE THREAD

**Issue by mjbvz** [PowerShell/PowerShellEditorServices#1191]
Hi, I work on VS Code's code actions. Our telemetry shows that your extension is returning `Command` types from at least one `CodeActionProvider`. A few years ago, we introduced a [`CodeAction` type](https://code.visualstudio.com/api/references/vscode-api#CodeAction) that brings a number of benefits over `Command`, including allowing workspace edits to be returned directly and letting extensions tag the type of their code actions (such as `Refactor` or `QuickFix`)

To make sure your extension behaves as expected with VS Code's new features, please migrate all of your code action providers to return `CodeActions` instead of `Commands`

 Let me know if you have any questions about this

**Comment by mjbvz** [comment]
Relevant code: 
https://github.com/PowerShell/PowerShellEditorServices/blob/81ba0c0b8efb7ee879f2ede511390ba73b0bc86e/src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs#L88

(Note: Since `CodeAction` take edits directly, you don't need to use the command at all after migrating to use the new type)

**Comment by mjbvz** [comment]
1. They are actually very similar! For the most simple change, create a code action with the proper title and just set `CodeAction.command` to the existing command. However, because you are already generating edits here, it's probably easier to set `CodeAction.edit`. I also strongly recommend setting `CodeAction.kind` as part of this

2. Yes, your providers should only return CodeActions, not commands. Again though, you can continue using commands in your code actions

**Comment by TylerLeonhardt** [comment]
@mjbvz so I gave this a go (taking the simple approach of moving to `CodeAction` wrapped `Command`s and I noticed that the lightbulb no longer shows a dialog of my code fixes.

Here's my change: https://github.com/TylerLeonhardt/PowerShellEditorServices/commit/40de31415b3c506b0e4df6bbbf15faa067bbc0ee

Is there something I'm doing wrong?
