### ISSUE TITLE
Provide feedback on VS Code's code action documentation proposal

### ISSUE THREAD

**Issue by mjbvz** [PowerShell/PowerShellEditorServices#1192]
Hi, I noticed that your extension seems to return documentation code actions:

https://github.com/PowerShell/PowerShellEditorServices/blob/81ba0c0b8efb7ee879f2ede511390ba73b0bc86e/src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs#L97

We have a proposal on VS Code that would standardize documentation for code actions: https://github.com/microsoft/vscode/issues/86788

Can you please take a look at the current proposal and share any feedback you have on it? Is it something you would be interested in adopting? Is the proposal missing anything relevant to your use case?

**Comment by TylerLeonhardt** [comment]
Thanks for the heads up!
