### ISSUE TITLE
FindDeclarationForBuiltinCommand should use Ast.Extent.File

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#1195]
When finding the definition of a command AST, the last fallback option is to get the `CommandInfo` and try to determine the path from that.

https://github.com/PowerShell/PowerShellEditorServices/blob/15df5e0fe4f425ea15cc2c82273e9dd2fed79ad6/src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs#L442-L470

Instead of relying on the function being defined in the psm1, should do something like this:

```csharp
if (commandInfo is FunctionInfo function)
{
    string file = function.ScriptBlock.Ast.Extent.File;
    return MakeScriptFileAndFindSymbolFromThisSpecificFile(
        file,
        foundSymbol);
}
```

/cc @kevinblumenfeld

**Comment by TylerLeonhardt** [comment]
Can you explain this a bit more?

**Comment by TylerLeonhardt** [comment]
please 😅

**Comment by SeeminglyScience** [comment]
Never mind for now, it's not the real problem.  It's still a problem, but fixing it will make the problem seem worse.

**Comment by TylerLeonhardt** [comment]
I know we need to do some work in how we discover the true Definition vs a reference.

**Comment by SeeminglyScience** [comment]
Well either that or we accidentally unleashed whatever ominous worse thing I described three years ago

Thanks for explaining what you mean past me -_-

---

I do vaguely remember but not enough to put it into words, we'll call this done and see if any new issues crop up. Thanks @fflaten!
