### ISSUE TITLE
Formatting with PSScriptAnalyzer not working

### ISSUE THREAD

**Issue by thkn-hofa** [PowerShell/PowerShellEditorServices#1231]
Format Document or Format Selection won't work. I don't see a progress indication like I used to (status bar: "Formatting Powershell...") and nothing is being formatted.

Manually formatting gives me this error:
```Powershell
Invoke-Formatter -ScriptDefinition (get-Content 'Scriptfile.ps1') -Verbose

Invoke-Formatter : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ScriptDefinition'. Specified method is not supported.
At line:1 char:36
+ ... tDefinition (get-Content 'ScriptFil ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Formatter], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Windows.PowerShell.ScriptAnalyzer.Commands.InvokeFormatterCommand
```

But it does work when I convert the array to a string (output omitted):
```Powershell
invoke-formatter -scriptdefinition ([String]::join("`n",(get-Content 'Scriptfile.ps1'))) -verbose
```

Edit: just installed previous version (2020.1.0) and formatter is working again.

**Comment by rjmholt** [comment]
> Invoke-Formatter -ScriptDefinition (get-Content 'Scriptfile.ps1') -Verbose

That's because the output of `Get-Content` is an array of string lines. You need:

```powershell
Invoke-Formatter -ScriptDefinition (Get-Content -Raw 'scriptfile.ps1') -Verbose
```

We're tracking the formatting issue in https://github.com/PowerShell/vscode-powershell/issues/2543.

Can you please turn your logging to diagnostic and upload them in that issue? You'll see instructions for that in the issue template.
