### ISSUE TITLE
completionItem/resolve provider is doubling some module's prefixes when attempting Get-Help

### ISSUE THREAD

**Issue by nakosenk** [PowerShell/PowerShellEditorServices#1242]
This happens on VS Code 1.43.2 using both the PowerShell 2020.03.0 and PowerShell Preview 2020.03.0 with PowerShell 5.1 on Windows 10 1909. 

To reproduce the problem, start typing Test-RD and PSES will call Get-Help to search for Test-RDRDOUAccess when the actual Cmdlet is Test-RDOUAccess. This also happens with a script module I've created, but the RemoteDesktop module is one that comes from Microsoft. 

Strangely, the only other module that I have that uses a Prefix is the ServerManagerTasks module, also from Microsoft, but that one does not cause the problem.

It's possible this could be a PowerShell bug, since I've seen that with my script module using the variable $MyInvocation.MyCommand results in the double prefix, but $MyInvocation.MyCommand.Name does not.

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by nakosenk** [comment]
I've attached a zip file with the logs and the Editor Service trace file.

```
> $psEditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      1      0      0       

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

[test-rdouaccess.zip](https://github.com/PowerShell/PowerShellEditorServices/files/4388591/test-rdouaccess.zip)

**Comment by TylerLeonhardt** [comment]
PR out (for the extension) ^

**Comment by nakosenk** [comment]
Created powershell/powershell#12213
