### ISSUE TITLE
Update to PSScriptAnalyzer 1.4.0

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#127]
Looks like the good folks on PSScriptAnalyzer are going to try to address as much of the "editor extent" issue as they can.  We might get a 1.3.1 drop early next week.  It would probably be worth waiting on that drop for 0.4.0.

**Comment by daviwil** [comment]
I'll talk to Raghu and see if he thinks it might come out on Monday.  I'd prefer not to slip the release date since I foolishly announced it already ;)  On the other hand, I don't know when VS Code folks plan to release 0.10.7 so the date may need to be slipped anyway.

**Comment by daviwil** [comment]
I talked to Raghu earlier, he thinks it may take a week before the fix is done, fully tested, and released.  Since that's the case, I'll ship 0.4.0 with 1.3.0 and then release an intermediate 0.4.1 release when 1.3.1 comes out.

**Comment by rkeithhill** [comment]
How's the PSScriptAnalyzer update coming along?  I guess we have the bigger issue of broken diagnostics to fix first, eh?

**Comment by daviwil** [comment]
I figured out the problem with that, have a PR on the way. They made a behavior-breaking change hidden behind an optional function parameter. I'm adding a unit test to catch future breaks, almost done. 

I think their next release will drop in the next couple of days so we should be ready to release a new version around the same time.
