### ISSUE TITLE
Uncaught exception when clients connect using LSP 3.14

### ISSUE THREAD

**Issue by dkattan** [PowerShell/PowerShellEditorServices#1277]
I posted an issue on the Monaco Language Client repo as well:
https://github.com/TypeFox/monaco-languageclient/issues/211

Essentially the spec for PublishDiagnosticCapabilities changed from version 3.14 to 3.15 and where a boolean used to be accepted for the tagSupport property, it has been replaced by an object. This leads to PowerShell Editor Services throwing an uncaught exception as it tries to deserialize a boolean to the new type.

Newtonsoft.Json.JsonSerializationException: 'Error converting value True to type 'OmniSharp.Extensions.LanguageServer.Protocol.Client.Capabilities.PublishDiagnosticsTagSupportCapability'. Path 'params.capabilities.textDocument.publishDiagnostics.tagSupport', line 1, position 681.'

This is because the current version sends the following parameters:
`publishDiagnostics: {relatedInformation: true, tagSupport: true}`

![image](https://user-images.githubusercontent.com/1424395/80655089-7050b200-8a43-11ea-81ae-0850b97dcc8f.png)

LSP protocol 3.15 does not expect tagSupport to be a boolean, instead it expects an array of tags:
```
tagSupport?: {
		/**
		 * The tags supported by the client.
		 */
		valueSet: DiagnosticTag[];
	};
```
[https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_publishDiagnostics](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_publishDiagnostics)

**Comment by TylerLeonhardt** [comment]
@david-driscoll this is something that would need to be addressed in `Omnisharp/csharp-language-server-protocol`, right?

I'm not entirely sure that you want to be in the business of maintaining backcompat... especially since we don't have union types in C#.

**Comment by david-driscoll** [comment]
Yeah I think I had it right at onepoint and thought it wasn't needed... guess I'm wrong!

**Comment by TylerLeonhardt** [comment]
@david-driscoll want me to open an issue in csharp-lsp?

**Comment by dkattan** [comment]
Turns out I was using monaco-languageclient 0.11.0, updating to 0.13.0 resolved this issue.
