### ISSUE TITLE
PackageManagement module fails to update when using AppLocker

### ISSUE THREAD

**Issue by johlju** [PowerShell/PowerShellEditorServices#1278]
The preview extension asks to replace the PackageManagement module which throws an error when using AppLocker (ConstrainedLanguage mode). 

![image](https://user-images.githubusercontent.com/7189721/80569448-3eb2f900-89f9-11ea-8b5d-f303562f10ae.png)

```
PackageManagement\Install-Package : An error has occurred while loading script module PackageManagement because it has a different language mode than the module manifest. The manifest la
nguage mode is ConstrainedLanguage and the module language mode is FullLanguage. Ensure all module files are signed or otherwise part of your application allow list configuration.
```

_Originally posted by @johlju in https://github.com/PowerShell/PowerShellEditorServices/issues/1221#issuecomment-621028593_

**Comment by TylerLeonhardt** [comment]
@johlju do you have any policies set up for PackageManagement or PowerShell built-in modules or signatures?

Also, what version of PowerShellGet are you using?

**Comment by johlju** [comment]
> ...do you have any policies set up for PackageManagement or PowerShell built-in modules or signatures?

Yes, we allow running the modules under `%programfiles%\WindowsPowerShell\Modules` on these dev worksations.

PowerShellGet has not been replaced with a newer one, still the one that came with Windows 10 I guess. 

```
ModuleType Version    Name
---------- -------    ----
Script     1.0.0.1    PowerShellGet
```

Although myself do not have local admin permission so I waiting for a colleague to verify this still exist when running VS Code with elevation (which I guess is needed to replace/update the PackageManagement module).

**Comment by TylerLeonhardt** [comment]
I have a "fix" out for this that doesn't run a command on your behalf because apparently PackageManagement doesn't play well in CLM...

There's also a setting to disable this warning already... though, keep in mind, you're using a version of PackageManagement that could lock up the PowerShell extension if you don't update it...

**Comment by johlju** [comment]
Then I suggest we close this issue one that PR is through. 

We can distribute the module (PackageManagement and PowerShellGet) centrally for example together with the deployment of VS Code (for PowerShell dev stations).
