### ISSUE TITLE
Update default PSHost console width to 120

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#129]
Now that VS Code shows the Debug Console and Output Window in a horizontal window it makes sense to increase the default width of the PSHost so that more text can be displayed on a single line.

**Comment by rkeithhill** [comment]
I mentioned this on the vscode issue but I'll repeat it here.  The script output is not prematurely wrapped.  This happens when I execute a command from the debug console when I'm debugging.  This makes it more corner case.  And I can workaround it in the debug console by executing:
```powershell
gci | out-string -width 120
```

**Comment by daviwil** [comment]
I think only output formatters (Format-*) obey the console width requirements.  Any calls to Write-Output will write the lines as wide as they're given.  Setting the default console width to be a lot wider will fix the formatter issue.

**Comment by rkeithhill** [comment]
I think I found the method to modify:
```csharp
        private Command GetOutputCommand(bool endOfStatement)
        {
            Command outputCommand =
                new Command(
                    command: this.IsDebuggerStopped ? "Out-String" : "Out-Default",
                    isScript: false,
                    useLocalScope: true);

            if (this.IsDebuggerStopped)
            {
                // Out-String needs the -Stream parameter added
                outputCommand.Parameters.Add("Stream");
            }

            return outputCommand;
        }
```
If the debugger is stopped we need to use Out-String but we need to pass it the width parameter.  Should I hardcode that to 120 or should that be a setting?  Haven't figured out to add settings yet (and reference them from PSES code).

**Comment by daviwil** [comment]
You should only need to change this line: 

https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Session/SessionPSHostRawUserInterface.cs#L22

I'm pretty sure this is what's controlling the width of the output.  If you change the first value from 80 to 120 it should work.  The fix you're making helps for the debug adapter but we need this to work for the Run Selection (F8) command as well.

**Comment by daviwil** [comment]
Making a setting for this will take a bit more work because you'll have to plumb a settings object all the way down through the PSHost classes.  I'd say hold off on that for now because I need to figure out a good strategy for passing settings around in the design.

**Comment by rkeithhill** [comment]
I'll give this a go tonight.  Thanks for the pointer.

**Comment by daviwil** [comment]
Cool, thanks!

**Comment by daviwil** [comment]
I was messing around with debugger stuff so I made the change to see if it would work.  Here's what `gci` looks like with a width of 120:

```
-a----         2/4/2016   7:39 PM         331264 Microsoft.PowerShell.EditorServices.pdb                               
-a----         2/4/2016   7:39 PM         133120 Microsoft.PowerShell.EditorServices.Protocol.dll                      
-a----         2/4/2016   7:39 PM         357888 Microsoft.PowerShell.EditorServices.Protocol.pdb                      
-a----         2/4/2016   7:39 PM         162572 Microsoft.PowerShell.EditorServices.xml                               
-a----         2/4/2016   7:29 PM         176128 Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.dll          
-a----         2/4/2016   7:29 PM         345600 Microsoft.Windows.PowerShell.ScriptAnalyzer.BuiltinRules.pdb          
-a----         2/4/2016   7:29 PM         133632 Microsoft.Windows.PowerShell.ScriptAnalyzer.dll                       
-a----         2/4/2016   7:29 PM         335360 Microsoft.Windows.PowerShell.ScriptAnalyzer.pdb                       
-a----        7/24/2015   3:57 PM         520192 Newtonsoft.Json.dll                                      
```

Since I've already made the fix, mind if I just include it with my next PR?

**Comment by rkeithhill** [comment]
Don't we need to update this code as well?
```csharp
public override Size MaxPhysicalWindowSize
{
    get { return new Size(80, 20); }
}

/// <summary>
/// Gets the maximum size of the console window.
/// </summary>
public override Size MaxWindowSize
{
    get { return new Size(80, 20); }
}
```

**Comment by daviwil** [comment]
hah!  Looks like you're working on it now too.  I don't think those need to be changed, they may only get used if advanced buffer math is involved.  You should submit the PR since you've been looking into it already.

**Comment by rkeithhill** [comment]
No problem. It's just that one line right?  I'll submit it in a few minutes.

**Comment by daviwil** [comment]
Yep, just that one line.  No rush at all!

**Comment by rkeithhill** [comment]
That max info does show up if you query `$host.ui.rawui` in the dbg con:
```
[DBG]: PS C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\bin\Debug> 
$host.ui.rawui


ForegroundColor       : White
BackgroundColor       : Black
CursorPosition        : 0,0
WindowPosition        : 0,0
CursorSize            : 0
BufferSize            : 80,100
WindowSize            : 0,0
MaxWindowSize         : 80,20
MaxPhysicalWindowSize : 80,20
KeyAvailable          : False
WindowTitle           :
```
I don't think it would interfere with anything to keep the widths consistently 120.  What do think?

**Comment by daviwil** [comment]
Shouldn't be a problem, go ahead and change those too

**Comment by rkeithhill** [comment]
Just about done with this.  I feel like a dufus here but I just noticed the "Output" window.  I had been so hung on the Debug Console.  What I don't get is - what determines where script output goes?  I see that it goes to the Debug Console.  The only thing I see appear in the Output window is when I execute using F8.  Does that sound about right?

**Comment by daviwil** [comment]
Yep, your understanding is correct.  Debug Console is for debugger output, Output window is for F8 output.

**Comment by daviwil** [comment]
Fixed by commit https://github.com/PowerShell/PowerShellEditorServices/commit/506d71381337ee206bb7dcec12ea5c43095e03ca

**Comment by daviwil** [comment]
By the way, in the future you can write your commit messages in a certain way so that GitHub automatically resolves them once your PR is merged.  If you write something like "Fix #129", "Fixes #129", or "Resolves #129" in your commit message, it will happen automatically :)

**Comment by rkeithhill** [comment]
Didn't know that.  Thanks for the tip!

**Comment by daviwil** [comment]
Yep, you can write it anywhere in the message.  Sometimes I write it in the top line, other times I write it on its own line at the end of the commit message.  It's pretty smart about picking those up.
