### ISSUE TITLE
Remove DebugAdapter.cmd files

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#131]
Our Microsoft.PowerShell.EditorServices.DebugAdapter.cmd files can now be removed because the VS Code team has fixed the bug that prevented the `/debugAdapter` parameter from being passed to the host process at startup.

Relevant vscode-powershell bug: https://github.com/PowerShell/vscode-powershell/issues/52

**Comment by daviwil** [comment]
Also need to remove the references to these files in the csproj and nuproj files.

**Comment by rkeithhill** [comment]
Yay!!
