### ISSUE TITLE
$PSEditor does not work when VSCode has a folder open

### ISSUE THREAD

**Issue by PeterHodges15** [PowerShell/PowerShellEditorServices#1311]
Open VSCode then open a folder {File}, {Open Folder}, select folder
Start a new powershell PS1 file (ensure that Powershell has started)
enter $PSEditor and you get null.
do the same without opening a folder and $PSEditor works.

**Comment by PeterHodges15** [comment]
Next time round I rebooted my pc and $PSEditor would not work.
I open a working folder it would not work.
I closed the working folder it worked.

**Comment by SydneyhSmith** [comment]
@PeterHodges15 sorry for the delay in response, thanks for opening this issue--looks like I am having trouble reproducing this, could you please provide your system info--Versions of VSCode, PowerShell, any settings etc.

**Comment by PeterHodges15** [comment]
Sydney:

Try this:

#Folder is open {File} {Open Folder}, Select Folder

$PSEditor #Returns nothing.

#Close the folder, the whole UI resets. Load this script

$PSEditor #Returns: EditorServicesVersion Workspace, 2.2.0.0 Microsoft.PowerShell.EditorServices.Extensions.EditorWor…

#Open A Folder, the whole UI resets. Load this script

$PSEditor #Returns nothing.

 



Powershell 7.02

See attached for my settings.

Peter

**Comment by PeterHodges15** [comment]
This might also help:

PS C:\AdministrativeTools> code --list-extensions

eamodio.gitlens

johnstoncode.svn-scm

ms-dotnettools.csharp

ms-mssql.mssql

ms-python.python

ms-vscode.powershell

$Extensions = @(

    "ms-mssql.mssql", #SQL Tools in left panel - it is probablly better to run/learn the Powershell-SQL commands.

    "ms-vscode.powershell", #For Powershell UI

    "ms-dotnettools.csharp", #Debug IMS C# code (Works if you have access to the code base,  Binaries are not enough)

    "johnstoncode.svn-scm", #Subversion integration

    "ironmansoftware.powershellprotools" #For Packaging script as an executable.  https://marketplace.visualstudio.com/items?itemName=ironmansoftware.powershellprotools  #Forms designer must be purchased

)

$Extension = $Extensions[0]

forEach ($Extension in $Extensions){

    $InstalledExtension = code --list-extensions | ? { $_ -eq $Extension }

    if (!$InstalledExtension) {

        code --install-extension $Extension

}

        #code --uninstall-extension $Extension

 

}

 

From: Peter Hodges <PeterH@VestServe.com> 
Sent: Thursday, July 9, 2020 5:25 PM
To: 'PowerShell/PowerShellEditorServices' <reply@reply.github.com>
Cc: 'PeterHodges15' <Peter_Hodges@VestServe.com>; 'Mention' <mention@noreply.github.com>; 'PowerShell/PowerShellEditorServices' <PowerShellEditorServices@noreply.github.com>
Subject: RE: [PowerShell/PowerShellEditorServices] $PSEditor does not work when VSCode has a folder open (#1311)

 

Sydney:

Try this:

#Folder is open {File} {Open Folder}, Select Folder

$PSEditor #Returns nothing.

#Close the folder, the whole UI resets. Load this script

$PSEditor #Returns: EditorServicesVersion Workspace, 2.2.0.0 Microsoft.PowerShell.EditorServices.Extensions.EditorWor…

#Open A Folder, the whole UI resets. Load this script

$PSEditor #Returns nothing.

 



Powershell 7.02

See attached for my settings.

Peter

**Comment by PeterHodges15** [comment]
FYI

Replicates with  nothing but this module installed: ms-vscode.powershell

 

 

From: Peter Hodges <PeterH@VestServe.com> 
Sent: Thursday, July 9, 2020 5:31 PM
To: 'PowerShell/PowerShellEditorServices' <reply@reply.github.com>
Cc: 'PeterHodges15' <Peter_Hodges@VestServe.com>; 'Mention' <mention@noreply.github.com>; 'PowerShell/PowerShellEditorServices' <PowerShellEditorServices@noreply.github.com>
Subject: RE: [PowerShell/PowerShellEditorServices] $PSEditor does not work when VSCode has a folder open (#1311)

 

This might also help:

PS C:\AdministrativeTools> code --list-extensions

eamodio.gitlens

johnstoncode.svn-scm

ms-dotnettools.csharp

ms-mssql.mssql

ms-python.python

ms-vscode.powershell

$Extensions = @(

    "ms-mssql.mssql", #SQL Tools in left panel - it is probablly better to run/learn the Powershell-SQL commands.

    "ms-vscode.powershell", #For Powershell UI

    "ms-dotnettools.csharp", #Debug IMS C# code (Works if you have access to the code base,  Binaries are not enough)

    "johnstoncode.svn-scm", #Subversion integration

    "ironmansoftware.powershellprotools" #For Packaging script as an executable.  https://marketplace.visualstudio.com/items?itemName=ironmansoftware.powershellprotools  #Forms designer must be purchased

)

$Extension = $Extensions[0]

forEach ($Extension in $Extensions){

    $InstalledExtension = code --list-extensions | ? { $_ -eq $Extension }

    if (!$InstalledExtension) {

        code --install-extension $Extension

}

        #code --uninstall-extension $Extension

 

}

 

From: Peter Hodges <PeterH@VestServe.com <mailto:PeterH@VestServe.com> > 
Sent: Thursday, July 9, 2020 5:25 PM
To: 'PowerShell/PowerShellEditorServices' <reply@reply.github.com <mailto:reply@reply.github.com> >
Cc: 'PeterHodges15' <Peter_Hodges@VestServe.com <mailto:Peter_Hodges@VestServe.com> >; 'Mention' <mention@noreply.github.com <mailto:mention@noreply.github.com> >; 'PowerShell/PowerShellEditorServices' <PowerShellEditorServices@noreply.github.com <mailto:PowerShellEditorServices@noreply.github.com> >
Subject: RE: [PowerShell/PowerShellEditorServices] $PSEditor does not work when VSCode has a folder open (#1311)

 

Sydney:

Try this:

#Folder is open {File} {Open Folder}, Select Folder

$PSEditor #Returns nothing.

#Close the folder, the whole UI resets. Load this script

$PSEditor #Returns: EditorServicesVersion Workspace, 2.2.0.0 Microsoft.PowerShell.EditorServices.Extensions.EditorWor…

#Open A Folder, the whole UI resets. Load this script

$PSEditor #Returns nothing.

 



Powershell 7.02

See attached for my settings.

Peter

**Comment by SydneyhSmith** [comment]
@PeterHodges15 thanks unfortunately still unable to repro using those steps, attachments also unfortunately dont seem to come through via email, could you please add them here ..thanks!

**Comment by PeterHodges15** [comment]
Here are the settings.

**Comment by PeterHodges15** [comment]
[settings.json.txt](https://github.com/PowerShell/PowerShellEditorServices/files/4920412/settings.json.txt)
You will have to rename the file back to settings.json

**Comment by TylerLeonhardt** [comment]
Any reason you closed this @PeterHodges15?

**Comment by PeterHodges15** [comment]
No.

I did not mean to. I only meant to ensure you had the attachment.

**Comment by SydneyhSmith** [comment]
Thanks @PeterHodges15 does the extension fully start up before you run  `$PSEditor` a screenshot of the console would be great in determining this?

**Comment by TylerLeonhardt** [comment]
@PeterHodges15 attachments unfortunately don't come through email. You'll have to attach on the actual issue website.
