### ISSUE TITLE
Install-Module -Name PackageManagement  requires TLS 1.2

### ISSUE THREAD

**Issue by MSIH** [PowerShell/PowerShellEditorServices#1314]
https://github.com/PowerShell/PowerShellEditorServices/blob/8cfbf2b4eb636956c31ba6ad258bb3d1b09155eb/src/PowerShellEditorServices/Services/PowerShellContext/Handlers/GetVersionHandler.cs#L121

To download the PackageManagement module requires TLS 1.2. Many users will get an error. Instead, I suggest adding code to force TLS 1.2

`-Command '[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; Install-Module -Name PackageManagement -Force -MinimumVersion 1.4.6 -Scope CurrentUser -AllowClobber`

**Comment by corbob** [comment]
I believe this to be related to https://github.com/PowerShell/vscode-powershell/issues/2763 would probably be good to update both vscode extension and PSES at the same time. 🤷
