### ISSUE TITLE
VersionUtils.IsNetCore returns false in net 5.0, breaking LoadAssemblyInPsesLoadContext

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#1317]
The check for .NET core is implemented as this:

```csharp
public static bool IsNetCore { get; } = RuntimeInformation.FrameworkDescription.StartsWith(".NET Core", StringComparison.Ordinal);
```

But in .NET 5.0 the framework description no longer includes the word "Core".  For example, in pwsh 7.1 preview 3, this is the framework description:

```raw
.NET 5.0.0-preview.4.20251.6
```

This makes `EditorExtensionServiceProvider.LoadAssemblyInPsesLoadContext` load the specified assembly in the default ALC, breaking ESCS:

```csharp
public Assembly LoadAssemblyInPsesLoadContext(string assemblyPath)
{
        if (!VersionUtils.IsNetCore)
        {
                return Assembly.LoadFrom(assemblyPath);
        }
        return EditorExtensionServiceProvider.LoadAssemblyInPsesAlc(assemblyPath);
}
```

**Comment by TylerLeonhardt** [comment]
I always thought that check was suspicious...

**Comment by TylerLeonhardt** [comment]
Looks like `Platform.IsCoreCLR` wasn't introduced until PowerShell Core... so... what about the negative check?:

```csharp
!RuntimeInformation.FrameworkDescription.StartsWith(".NET Framework", StringComparison.Ordinal);
```

**Comment by TylerLeonhardt** [comment]
PR out for this one with a move of our tests to PS7 and PS7.1 :)
