### ISSUE TITLE
Add /logLevel parameter to host process

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#132]
A `/logLevel` parameter should be added to the host process so that the user can control log output verbosity using an editor setting.

**Comment by rkeithhill** [comment]
This would apply to debugging as well as editing, right?  Would you leave the default to `Normal` or drop it down to `Warning` or `Error`?

**Comment by daviwil** [comment]
I'm setting it to Normal by default, which will give you the basic information messages around process lifecycle as well as all of the errors.  The setting in VS Code will apply to the language service but the user would have to change the package.json to change it for the debug adapter.  There may be another way to do it with launch.json, not sure.
