### ISSUE TITLE
Specify additional assemblies for code completion

### ISSUE THREAD

**Issue by yevgeni-zolotko** [PowerShell/PowerShellEditorServices#1322]
Is there a way to add custom "referenced" assemblies to be available in code completion - via `configuration `request or otherwise.
For example, I would like to have types from assembly "MyCustomAssembly.dll" to be available in PSES IntelliSense.
Importing via `import assembly` or `Add-Type` doesn't introduce the loaded types to code completion either.

**Comment by rjmholt** [comment]
`Add-Type` or `Import-Module` in the integrated console is how you do that. Intellisense is driven by the underlying PowerShell session, so importing your assembly into that should be sufficient. Bear in mind you can’t just type it into a file being edited, it must be executed in the session.

Can you go over what you’ve already tried in more detail?

**Comment by yevgeni-zolotko** [comment]
We are not using the server from vscode, but running it to be used against a custom client. Should we be executing commands like `Import-Module` in the PowerShell before starting the PSES startup script?

**Comment by rjmholt** [comment]
You’ll need to import the types into the hosting PowerShell process somehow. You could import them before starting PSES or by importing them in a profile or even adding them in the AdditionalModules parameter

**Comment by yevgeni-zolotko** [comment]
Executing `Add-Type -Path 'my-assembly.dll'` before running the PSES startup script works. Thank you.

**Comment by rjmholt** [comment]
I should say that I'm fairly sure this is what the `-AdditionalModules` parameter is meant for
