### ISSUE TITLE
The response to textDocument/signatureHelp is not per spec

### ISSUE THREAD

**Issue by rwols** [PowerShell/PowerShellEditorServices#1324]
```
:: --> PowerShellEditorServices textDocument/signatureHelp(7): {'position': {'line': 0, 'character': 8}, 'textDocument': {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP-PowerShellEditorServices/test.ps1'}}
:: <<< PowerShellEditorServices 7: {'signatures': None}
```
The value of the `signatures` key should be an array (so not an `array | null`).
If there are no signatures available, you can send `null` instead of `{"signatures": null}`.

**Comment by TylerLeonhardt** [comment]
Looks like this is the line where we're doing it wrong:

https://github.com/PowerShell/PowerShellEditorServices/blob/fdb20951c4e2b8978885b4c0dd72304131e3702c/src/PowerShellEditorServices/Services/TextDocument/Handlers/SignatureHelpHandler.cs#L68-L71

I guess we can just return `null`... although... maybe `new SignatureHelp()` should create an empty array for `Signatures`...

cc @david-driscoll

**Comment by TylerLeonhardt** [comment]
btw @rwols what client are you using?

**Comment by rwols** [comment]
I'm using [this plugin](https://github.com/sublimelsp/LSP) for SublimeText. I'm actually working on a convenience plugin that installs/updates the server [here](https://github.com/sublimelsp/LSP-PowerShellEditorServices).

**Comment by rwols** [comment]
> maybe new SignatureHelp() should create an empty array for Signatures...

That is certainly also a possibility.

**Comment by TylerLeonhardt** [comment]
@rwols if you want to contribute a call out to LSP-PowerShellEditorServices [in our README](https://github.com/PowerShell/PowerShellEditorServices#powershell-language-server-protocol-clients-using-powershell-editor-services) that'd be awesome :)

**Comment by TylerLeonhardt** [comment]
fix out for this ^

**Comment by TylerLeonhardt** [comment]
This is fixed. Automation will rev the version of the library that we use and it'll be in the next version of PSES

**Comment by rwols** [comment]
Thanks for the quick fix! I'm still busy getting things working for Windows, I'll make a PR for a call-out when the plugin is ready :)
