### ISSUE TITLE
The "tags" in a CompletionItem response should be an array, not null

### ISSUE THREAD

**Issue by rwols** [PowerShell/PowerShellEditorServices#1325]
I'm noticing that the "tags" of a completion item is `null`, but this violates the spec. You should leave the key out altogether if there are no tags.

**Comment by TylerLeonhardt** [comment]
I think this just needs to be marked optional:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/bdec4c73240be52fbb25a81f6ad7d409f77b5215/src/Protocol/Models/CompletionItem.cs#L25-L30

this is really a bug in csharp-language-server-protocol I think. cc @david-driscoll

**Comment by TylerLeonhardt** [comment]
fix out for this ^

**Comment by TylerLeonhardt** [comment]
This is fixed. Automation will rev the version of the library that we use and it'll be in the next version of PSES
