### ISSUE TITLE
Debugger should set working dir to something other than VSCode install dir

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#137]
I would propose that we set the current working dir to either the workspace root dir or the folder of the initial script file.  I've already run into issues with relative paths that stumped me for a bit until I realized the working dir wasn't set to what what I thought it was.  Do you think this could make it into 0.4.0?  It would help the debug experience.

**Comment by daviwil** [comment]
Yeah, definitely should go into 0.4.0. You could start by modifying the HandleLaunchRequest method in this file:

https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs

Before the ExecuteScriptAtPath call you could make another ExecuteCommand call to Set-Location for the script file's directory path. There may be a way to get the workspace path from some of their newer debugger protocol changes but I haven't looked at those closely yet. You might be able to look at this repo for ideas:

https://github.com/Microsoft/vscode-debugadapter-node

**Comment by rkeithhill** [comment]
I found this in the Node debug package.json file:
```json
				"configurationAttributes": {
					"launch": {
						"required": ["program"],
						"properties": {
							"program": {
								"type": "string",
								"description": "Workspace relative path to the program."
							},
							"args": {
								"type": "array",
								"description": "Command line arguments passed to the program.",
								"items": { "type": "string" },
								"default": []
							},
							"cwd": {
								"type": "string",
								"description": "Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.",
								"default": "."
							},
```
I've tried plugging this into my package.json but no luck. It is not clear to me with this approach *who* is supposed to set the CWD - VSCode or PSES.

**Comment by daviwil** [comment]
You shouldn't need to set the cwd, judging from the description here it sounds like they send the workspace path by default.  We just need to read that setting and set the working path ourselves.

Apparently we already have the "WorkingDirectory" variable on our LaunchRequest message type, I just haven't been using it:

https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Protocol/DebugAdapter/LaunchRequest.cs#L30

Theoretically this should be filled in by the debug client by default.

**Comment by rkeithhill** [comment]
Ah, well the json property is called "cwd".  Once I renamed the LaunchRequest.cs WorkingDirectory field to Cwd, the value was mapped correctly.

**Comment by rkeithhill** [comment]
BTW if I rename Arguments to just Args then the user can specify `"Args": ["-param1", "foo", "-param2", "bar"]` and that comes through.  In theory, we could apply those to the script execution. I'm just not sure how to call `AddParameter` on these values.  And what the `"Args":` format should be.
