### ISSUE TITLE
Debugger doesn't flush output reliably

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#138]
I've noticed while debugging that output from a line that has executed is not shown even though the script has hit a breakpoint on a subsequent line.  I can step once and that is usually enough to get the output to appear.  It would be nice though to have any pending output flushed on debugger stop.

**Comment by rkeithhill** [comment]
Wait a tic, I see you haven't checked that in.  Hmm, I wonder why I'm seeing this behavior then.

**Comment by daviwil** [comment]
Which script were you trying this with?  I'll try to see if I can reproduce the behavior.

**Comment by rkeithhill** [comment]
Put this in a file and set a breakpoint on the second line:
```powershell
$pwd
$pwd
```
The first $pwd doesn't display its output until you step over the breakpoint on the second one.

**Comment by daviwil** [comment]
I see the same behavior in the ISE too, I wonder if the debugging engine is hitting the breakpoint so fast that the output doesn't even get flushed to the PSHost layer.

**Comment by daviwil** [comment]
One thing I do notice though is that sometimes the debug adapter exits at the end of the script so fast that the final line of output might not get written (this is with a local build the buffering change).  I'll need to make sure it gets flushed before exiting.

**Comment by daviwil** [comment]
Yeah, this definitely comes from the PowerShell layer.  I just tried flushing buffered output when a breakpoint gets hit and nothing got written out.  I'll mark this as something to investigate for a future release.

**Comment by demyte** [comment]
@daviwil Any update on this one?

I am running 0.7.2 on Windows.

I have a simple script of:

> Write-Host "Hello"
> Write-Debug "Hello"
> Write-Output "Hello"

Shows nothing in the Debug window nor in the PowerShell Output window.

If I execute the lines using F8, I get output in the PowershellOutput window for the first and third commands.
