### ISSUE TITLE
[Revamp pipeline thread handling] Enable proper terminal color support on the host

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PowerShellEditorServices#1435]
PowerShell achieves terminal color support by communicating to the host a PSObject with properties with certain names (because that was how the awareness was added to PowerShell's own host capabilities).

This is available in PSES today through this:

https://github.com/PowerShell/PowerShellEditorServices/blob/4fa034626ef1df434f1b918639b47d708ba2d370/src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHost.cs#L82-L237

We need to restore this functionality in the new integrated console.

**Comment by andschwa** [comment]
Closing as duplicate.
