### ISSUE TITLE
[Revamp pipeline thread handling] Ensure multi-hop remoting works

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PowerShellEditorServices#1438]
Multi-hop remoting is a common scenario for the extension (and for PowerShell generally) and we need to make sure that it works as expected.

The steps are:

- From the extension/console, remote into a machine
- From that remoting session, remote into another machine
- Ensure that the console still works, and validate things like completions and file passthroughs

**Comment by andschwa** [comment]
@SeeminglyScience Did we test this, is it working?

**Comment by andschwa** [comment]
We're going to close this out and wait until we hear from users if it isn't working.
