### ISSUE TITLE
[Revamp pipeline thread handling] Support debug runspace

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PowerShellEditorServices#1447]
https://github.com/PowerShell/PowerShellEditorServices/blob/9e1a17a3ceabc1dc856ce90f4aac177c971c5c0a/src/PowerShellEditorServices/Services/PowerShellContext/Session/Capabilities/DscBreakpointCapability.cs#L90-L166

https://github.com/PowerShell/PowerShellEditorServices/blob/1ffe6db32e3aaeed0866497ed32a35e96f937390/src/PowerShellEditorServices/Services/DebugAdapter/DebugEventHandlerService.cs#L92-L114

https://github.com/PowerShell/PowerShellEditorServices/blob/29e44b6ebdc63de70bd06538db03f3298ba2cfc6/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L2496-L2512

https://github.com/PowerShell/PowerShellEditorServices/blob/29e44b6ebdc63de70bd06538db03f3298ba2cfc6/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L1514-L1517

https://github.com/PowerShell/PowerShellEditorServices/blob/9e1a17a3ceabc1dc856ce90f4aac177c971c5c0a/src/PowerShellEditorServices/Services/PowerShellContext/RemoteFileManagerService.cs#L631-L634

See also:

https://github.com/PowerShell/PowerShellEditorServices/blob/9e1a17a3ceabc1dc856ce90f4aac177c971c5c0a/src/PowerShellEditorServices/Services/PowerShellContext/Session/RunspaceDetails.cs#L15-L322

**Comment by rjmholt** [comment]
To solve in https://github.com/PowerShell/PowerShellEditorServices/pull/1459
