### ISSUE TITLE
Bump OmniSharp to v0.19.2

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShellEditorServices#1458]
Update [v0.19.1](https://github.com/OmniSharp/csharp-language-server-protocol/releases/tag/v0.19.1) contains a critical bugfix, https://github.com/OmniSharp/csharp-language-server-protocol/issues/562, necessary for us to complete https://github.com/PowerShell/vscode-powershell/issues/3294.

**Comment by rjmholt** [comment]
Unfortunately the latest Omnisharp update currently breaks integration with VSCode's debugging UI:

![debugging](https://user-images.githubusercontent.com/7009879/115282696-59e1b180-a0ff-11eb-8520-6623f1916b4b.gif)

**Comment by rjmholt** [comment]
Waiting on https://github.com/OmniSharp/csharp-language-server-protocol/pull/567 to fix this

**Comment by andschwa** [comment]
Thanks for your diligent work @rjmholt!

**Comment by andschwa** [comment]
I think we should also wait for https://github.com/OmniSharp/csharp-language-server-protocol/issues/556 and hopefully once it's resolved a v0.19.2 drop.

**Comment by andschwa** [comment]
This was resolved by #1460 (which is a beta of 0.19.2, but for now it counts). When a stable version is released, we'll update again.
