### ISSUE TITLE
PssaCmdletAnalysisEngine: CommandNotFoundException Get-ScriptAnalyzerRule 

### ISSUE THREAD

**Issue by dkattan** [PowerShell/PowerShellEditorServices#1497]
I actually think this may be a problem in PowerShell itself but I have no idea how you guys aren't seeing this in production.

For whatever reason modules imported by the InitialSessionState are not available to PowerShell when it is linked to a RunspacePool.

The only way I've gotten this exception to _not_ throw is to comment out https://github.com/PowerShell/PowerShellEditorServices/blob/a12edc99e24818ccbd2de9200962fb7eb96104fc/src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs#L331

Which essentially creates a brand new runspace for the powershell instance. I know this isn't optimal, but it magically finds Get-ScriptAnalyzerRule and Invoke-ScriptAnalyzer when I do, and everything appears performant and works as expected.

There's a note [here](https://github.com/PowerShell/PowerShellEditorServices/blob/a12edc99e24818ccbd2de9200962fb7eb96104fc/src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs#L340
) indicating that this exception is possible if the module path loaded is wrong. I don't think that's what's going on as I have validated the path, and it works with the adjustment above.

When using the RunspacePool, I've tried importing the module using Invoke-Expression in the same script as Get-ScriptAnalyzer, as well as using initialSessionState.importPSModulesFromPath and the same issue occurs.

**Comment by andschwa** [comment]
Sorry about the irony, but I can't repro this so I can't verify it or the fix. Is there any chance you can isolate what exactly is causing this to repro? If it were reproducing widely I'd expect more user reports about it.

**Comment by dkattan** [comment]
> Sorry about the irony, but I can't repro this so I can't verify it or the fix. Is there any chance you can isolate what exactly is causing this to repro? If it were reproducing widely I'd expect more user reports about it.

I'm back on this today, I'll see about getting better reproduction steps.
