### ISSUE TITLE
CodeActionHandler.cs: FileNotFoundException when using inmemory: protocol

### ISSUE THREAD

**Issue by dkattan** [PowerShell/PowerShellEditorServices#1498]
In WorkSpaceService.cs
https://github.com/PowerShell/PowerShellEditorServices/blob/a12edc99e24818ccbd2de9200962fb7eb96104fc/src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs#L193-L197

Consider adding
```
case: "inmemory":
``` 

as this is the default for the MonacoLanguageClient

Additionally for this to work, consider the following change to prevent a FileNotFoundException in CodeActionHandler.cs
https://github.com/PowerShell/PowerShellEditorServices/blob/a12edc99e24818ccbd2de9200962fb7eb96104fc/src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs#L60
```
IReadOnlyDictionary<string, MarkerCorrection> corrections = null;
try
{
    var file = _workspaceService.GetFile(request.TextDocument.Uri);
    corrections = await _analysisService.GetMostRecentCodeActionsForFileAsync(file).ConfigureAwait(false);
}
catch (Exception ex) //if (corrections == null)
{
    return Array.Empty<CommandOrCodeAction>();
}
```

**Comment by andschwa** [comment]
This seems reasonable to do. Any reason in particular you didn't open a PR for these changes (or those in #1495)?
