### ISSUE TITLE
Long-running requests should automatically cancel

### ISSUE THREAD

**Issue by kayladavis** [PowerShell/PowerShellEditorServices#15]
A user may want to cancel a request if it is taking too long. The editor service should handle for that.

When making a reference request or a definition request, we should be able to cancel the request if another (reference or definition request) is made before the current one has finished. It may make sense to also do this for an occurrences request.

**Comment by daviwil** [comment]
Tweaking the intent of this one a little bit.  I'm adding task timeout handling for any situation where it takes too long to complete a request due to the runspace being backed up.
