### ISSUE TITLE
NullReferenceException when $profile doesn’t exist

### ISSUE THREAD

**Issue by dkattan** [PowerShell/PowerShellEditorServices#1502]
https://github.com/PowerShell/PowerShellEditorServices/blob/f5006ae3748985a0ed111f08c0408dfcea562ff2/src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs#L349

Can we get a null check here to prevent profile loading if the $profile value is null?

**Comment by SeeminglyScience** [comment]
Explicit casts do not throw on null in C#.  Are you sure that's where the exception you're seeing is coming from?

**Comment by rjmholt** [comment]
> Can we get a null check here

AFAIK you're the only person to report this, and we'd be happy to accept a PR

**Comment by dkattan** [comment]
> Explicit casts do not throw on null in C#. Are you sure that's where the exception you're seeing is coming from?

You are correct, it is actually on line 382.

![image](https://user-images.githubusercontent.com/1424395/122570137-162cfa80-d011-11eb-9b7e-e06a3097a9ba.png)


> > Can we get a null check here
> 
> AFAIK you're the only person to report this, and we'd be happy to accept a PR

I'm working on a merge request now.
