### ISSUE TITLE
VSCode complains about error in PSES package.json file

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#154]
Is this a PSES issue or a VSCode issue:
![psespkgjsonerror](https://cloud.githubusercontent.com/assets/5177512/13024383/0e4f6c94-d1b1-11e5-867f-1772dbdf9587.png)

**Comment by daviwil** [comment]
This is an issue you can safely ignore.  Based on npm's package.json schema, they require that packages have names that don't have any uppercase characters.  VS Code has repurposed package.json as its own manifest format so the same rules really don't apply.  I think they just use the same linting for all package.json files regardless of whether it's a VS Code's extension package.json or not.

**Comment by rkeithhill** [comment]
Thanks for the explanation.
