### ISSUE TITLE
Revert language version fix and find another fix?

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShellEditorServices#1544]
In #1541 we updated the language version from 9.0 to 10.0 to workaround a bug with .NET 6 Preview 7; however, this isn't the greatest workaround because it requires everyone building PSES to update their dotnet:

```
CSC : error CS1617: Invalid option '10.0' for /langversion. Use '/langversion:?' to list supported values. [/Users/andschwa/src/PowerShellEditorServices/src/PowerShellEditorServices/PowerShellEditorServices.csproj]
```

We didn't realize this because the CI _always_ comes with an up-to-date dotnet.

The simply solution is for PSES devs to just delete `.dotnet` and let the build script install the latest, but perhaps we should fix it another way.

**Comment by andschwa** [comment]
Sorry @rjmholt.

**Comment by rjmholt** [comment]
I'm guessing setting LangVersion to `latest` isn't going to work for some target frameworks...

**Comment by andschwa** [comment]
Probably not, and I don't particularly want to just randomly adopt their newest language 😢

**Comment by rjmholt** [comment]
> just randomly adopt their newest language

It tends to be tethered to the framework version, but yeah it's probably not the right solution here.

Maybe we want a conditional entry to temporarily work around the issue? Not sure if there's an easy way to test the sdk version
