### ISSUE TITLE
GitHub Actions running (and failing) on forked repositories

### ISSUE THREAD

**Issue by corbob** [PowerShell/PowerShellEditorServices#1553]
Ever since I brought my master branch back in line with PowerShell/PowerShellEditorServices, I've been receiving an email that CodeQL failed every day. Could we configure the GitHub Actions to only fire if it's the main PowerShell repository?

**Comment by andschwa** [comment]
<img width="1682" alt="Screen Shot 2021-08-24 at 2 33 51 PM" src="https://user-images.githubusercontent.com/2226434/130693014-20999791-ba7c-44de-9140-b2ae862438d2.png">

Can you try disabling the workflow on your fork?

**Comment by corbob** [comment]
![2021-08-24_14-38-35](https://user-images.githubusercontent.com/30301021/130693586-44700286-831f-41f9-8fbb-2357af513998.png)

I didn't know that was an option now. I'll report in tomorrow if it sends me an email or not.

**Comment by corbob** [comment]
It looks like disabling the workflow did the trick. I'll go ahead and close this issue.

**Comment by andschwa** [comment]
FYI @rjmholt you can fix yours this way too.
