### ISSUE TITLE
[Revamp pipeline thread handling] Reinstate prompt handlers

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#1583]
In the migration from the PowerShellContext, this code was taken out:

https://github.com/PowerShell/PowerShellEditorServices/blob/4fa034626ef1df434f1b918639b47d708ba2d370/src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/PromptHandlers.cs#L15-L179

We should ensure that functionality is restored in the extension.

**Comment by andschwa** [comment]
Oh no @SydneyhSmith apparently this is why those interfaces disappeared...we took out the tests in #1660. I guess if users ask for this we'll work to bring it back.
