### ISSUE TITLE
Validate that stdout is not polluted and intercept shutdown requests from client in tests

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#1592]
After debugging integration test hangs for a few days for #1459, I discovered that test hangs were being caused by the following issue:

- Some functions were still writing output to the `PSHostUserInterface`
- We weren't changing the implementation of that to do nothing when `ConsoleReplEnabled` was `false`
- That meant we'd write random strings to stdout, which confused the client
- The client would interpret this as an error and send the server a `shutdown` request
- The server would comply, but we wouldn't see anything in the test to corroborate this, so the test would just hang

I've since implemented a dummy host in the server to enable this scenario (but I don't love it). I've also added debug logging for the stdio streams so the stream content can be viewed when a debugger is attached.

To improve on this, we should:

- Validate messages sent over the streams and throw if they are invalid
- See if we can hook into the client sending a shutdown message so we can monitor that and again log or fail tests when it happens
- Make the server exit the process when it's asked to shut down (not sure how to make this happen yet or I'd do it myself)

**Comment by andschwa** [comment]
I validated this! And fleshed out the null host.
