### ISSUE TITLE
Need to re-implement `ConsoleColorProxy`

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShellEditorServices#1607]
From Rob: we need to go implement this with @SteveL-MSFT and @daxian-dbw's help because it's an "obscure" interface.

_Originally posted by @andschwa in https://github.com/PowerShell/PowerShellEditorServices/pull/1459#discussion_r722721500_

**Comment by andschwa** [comment]
It's currently disabled:

https://github.com/PowerShell/PowerShellEditorServices/blob/7bf4299a1210828a3bb11fee91d0c4924f074e98/src/PowerShellEditorServices/Services/PowerShell/Host/ConsoleColorProxy.cs#L4-L151

**Comment by andschwa** [comment]
@SydneyhSmith We need to figure out if this is the "old-school" colors and if so, do we actually need to support it? Because as it is, the console _has_ colors (since everything is modern now and ANSI color escape sequence based, which all works).

**Comment by andschwa** [comment]
Ok, so yes, this would really only fix color support on _ancient_ (read: near end-of-life) Windows platforms such as Windows Server 2012R2). This is not a priority.

**Comment by SeeminglyScience** [comment]
I believe it's all color formatting in Windows PowerShell and also some in later versions (even on modern OSes)

Like if you do this:

```powershell
$Host.psobject.Properties.Add(
    [psnoteproperty]::new(
        'PrivateData',
        [pscustomobject]@{
            ErrorBackgroundColor = [ConsoleColor]::Black
            ErrorForegroundColor = [ConsoleColor]::DarkCyan
            ErrorAccentColor = [ConsoleColor]::Cyan
            FormatAccentColor = [ConsoleColor]::Green
            WarningForegroundColor = [ConsoleColor]::Yellow
            WarningBackgroundColor = [ConsoleColor]::Black
            DebugForegroundColor = [ConsoleColor]::Yellow
            DebugBackgroundColor = [ConsoleColor]::Black
            VerboseForegroundColor = [ConsoleColor]::Yellow
            VerboseBackgroundColor = [ConsoleColor]::Black
            ProgressForegroundColor = [ConsoleColor]::Black
            ProgressBackgroundColor = [ConsoleColor]::Yellow
        }))
```

Error formatting is fixed even in 7.3

**Comment by andschwa** [comment]
Is this something perhaps more easily fixed than Rob's comment led me to believe?

**Comment by SeeminglyScience** [comment]
I think it used to be pretty complicated to implement. Now though I think we route so much though `ConsoleHost` that I'm pretty sure we can directly surface it's `PrivateData` without even having to implement our own.

e.g. I think we can just do `PrivateData => _internalHost.PrivateData;`

**Comment by andschwa** [comment]
I'm down to try!
