### ISSUE TITLE
Pwsh 7: Could not resolve `Foreach-Object` 's `-Parallel` argument using ConvertTo-SplatExpression 

### ISSUE THREAD

**Issue by ninmonkey** [PowerShell/PowerShellEditorServices#1610]
## Issue:

Splat is outputting this
```ps1
$forEachObjectSplat = @{
    Parallel = -Parallel
}
Get-Process | ForEach-Object @forEachObjectSplat {
```

![image](https://user-images.githubusercontent.com/3892031/139493967-597fa6fe-d490-49e5-96fb-4b2eaad139e0.png)

## Expected Behaviour

`-parallel` should splat as a `bool`

## To reproduce

Use `ConvertTo-SplatExpression` on the `For-EachObject`

```ps1
$threadSafeDictionary = [System.Collections.Concurrent.ConcurrentDictionary[string, object]]::new()
Measure-Command -Expression { & {

        Get-Process | ForEach-Object -Parallel -ThrottleLimit 3 -UseNewRunspace {
            $dict = $using:threadSafeDictionary
            $dict.TryAdd($_.ProcessName, $_)
        }
    }
}

$threadSafeDictionary.Values | Format-Table -AutoSize
```

## Behavior

Creating new windows,  keeps reproducing the error
![parallel splat ┐ pwsh 7 1 ┐ part1- 2021-10-01](https://user-images.githubusercontent.com/3892031/139495173-57e38d9c-fc71-44f9-9a36-2fa51b1d7d53.gif)

![parallel splat ┐ pwsh 7 1 ┐ part2- 2021-10-01](https://user-images.githubusercontent.com/3892031/139495189-f472df76-e4eb-4b36-ad9c-0db436b75fa0.gif)

### test 1

| Addon                                          | Version   |
| ---------------------------------------------- | --------- |
| ms-vscode.powershell-preview                   | 2021.10.3 |
| TylerLeonhardt.vscode-inline-values-powershell | 0.0.5     |
| TylerLeonhardt.vscode-pester-test-adapter      | 0.0.23    |

```ps1
code --version
code version: 1.59.1, 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, x64
```

### test 2

| Addon                                          | Version   |
| ---------------------------------------------- | --------- |
|justin-grote.powershell-extension-pack |  0.0.5 |
|ms-vscode-remote.remote-ssh-edit |  0.65.8 |
|ms-vscode.powershell-preview |  2021.9.2 |
|nickdemayo.vscode-json-editor |  0.3.0 |
|PowerQuery.vscode-powerquery |  0.1.23 |
|rust-lang.rust |  0.7.8 |
|TylerLeonhardt.vscode-inline-values-powershell |  0.0.5 |

```ps1
PSVersion GitCommitId OS                           PSEdition
--------- ----------- --                           ---------
7.1.4     7.1.4       Microsoft Windows 10.0.19043 Core

code-insiders --version
1.62.0-insider, 284e0db6c4cac1e557a43cd6691babdaafc2e1a9, x64
```

**Comment by SeeminglyScience** [comment]
Tracking in SeeminglyScience/EditorServicesCommandSuite#69 (`ConvertTo-SplatExpression` isn't provided by the extension)
