### ISSUE TITLE
VSCode PowerShell Preview PSES no longer shows history from previous F8 command

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/PowerShellEditorServices#1627]
The current behavior of the PowerShell Extension is to show the history in the Terminal after using F5 or F8
- This is available with the up arrow to re-execute the previous command; however this is missing in the current preview.

Typo on my video: "Up arrow does **not** show history"

There are also some artifacts and clearing of the screen when executing the second command, however I didn't open this issue for that.

https://user-images.githubusercontent.com/3605266/141012338-b3f9dd95-575d-4dc5-a06f-bc7d8d98a37e.mp4

issue starts at 30 seconds onwards.

**Comment by brwilkinson** [comment]
Not sure if this is the correct place to open this, however it's related to the VSCode Preview PowerShell Extension.

**Comment by JustinGrote** [comment]
@brwilkinson  per the notes anything related to vscode-powershell should go there even if the fix is probably in PSES, just to make it simpler to triage issues. Thanks for the submission though! It's fine here.

**Comment by brwilkinson** [comment]
@JustinGrote  cool thanks, I will move it over and close this one.

**Comment by brwilkinson** [comment]
moved to https://github.com/PowerShell/vscode-powershell/issues/3683
