### ISSUE TITLE
Maintainers should not be able to push PRs without checks

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1637]
@andschwa now that we have a fairly reliable CI system, can you update settings to not allow pull requests to merge unless the CI checks pass? You as an admin will still be able to "force merge" if you need to for dumb CI reasons.

IMHO, this box should be greyed out for me as a maintainer unless checks pass and there's at least one other approved review:
![image](https://user-images.githubusercontent.com/15258962/143323505-d7b3dfc4-9690-4220-a4ea-2e93a4f93ba7.png)

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
(Step 7)

**Comment by andschwa** [comment]
I think that's a bug in the VS Code extension, as that rule is se
<img width="790" alt="Screen Shot 2021-11-29 at 11 24 07 AM" src="https://user-images.githubusercontent.com/2226434/143929804-a760bf8c-ae21-4708-b0c0-8f031e438414.png">
t
<img width="790" alt="Screen Shot 2021-11-29 at 11 24 31 AM" src="https://user-images.githubusercontent.com/2226434/143929816-82ae0425-08fc-4ee2-8fbf-dde8120c8140.png">
:

**Comment by andschwa** [comment]
@JustinGrote FWIW it's _only_ set for PRs made to the master branch, as that's all that really matters.

**Comment by JustinGrote** [comment]
Right, probably just a bug in the GitHub extension, sorry.

**Comment by andschwa** [comment]
No worries! Glad you double checked.
