### ISSUE TITLE
Add capabilities data to InitializeResponse body in debug adapter

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#164]
The VS Code team has added a capabilities list that our debug adapter can opt into:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L495

In the following issue, Isidor recommended that we set the `supportsEvaluateForHovers` to true so that data tips are evaluated correctly.  We should also determine which other capabilities we'd like to support and file separate issues for enabling those.

Related: https://github.com/Microsoft/vscode/issues/1804

**Comment by rkeithhill** [comment]
We should add support for this one as well: `supportsConditionalBreakpoints`.

**Comment by daviwil** [comment]
Yep, we'll take care of that in this issue: https://github.com/PowerShell/PowerShellEditorServices/issues/94
