### ISSUE TITLE
Regression: Most of FileInfo object properties is missing in debug view

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShellEditorServices#1649]
Most of *FileInfo* object properties is missing in debug view comparing to latest stable release of VSC for PowerShell (v2021.10.2)

Only small set of properties is visible:
```
#inculded in view:

PSPath
PSParentPath
PSChildName
PSDrive
PSProvider
PSIsContainer
Mode

#not included:

VersionInfo
BaseName
Target
LinkType
Name
Length
DirectoryName
Directory
IsReadOnly
Exists
FullName
Extension
CreationTime
CreationTimeUtc
LastAccessTime
LastAccessTimeUtc
LastWriteTime
LastWriteTimeUtc
Attributes
```

Latest preview version of VSC for PowerShell (v2021.12.0):
![image](https://user-images.githubusercontent.com/16168755/146919812-9c1d99e3-2706-4b85-b64a-f042a6f1150f.png)

**VS**

Latest stable version of VSC for PowerShell (v2021.10.2):
![image](https://user-images.githubusercontent.com/16168755/146920621-179271ae-9a2d-4c45-8c8a-71b4a29e2647.png)

**Comment by JustinGrote** [comment]
As @SeeminglyScience noted in a discussion, it looks like only non-NoteProperties are missing:
![image](https://user-images.githubusercontent.com/15258962/146959142-73648635-4a24-4870-8776-10faa6f654b3.png)

**Comment by JustinGrote** [comment]
I was able to reproduce this, on 7.2 some codeproperties also show up. Hmm...
![image](https://user-images.githubusercontent.com/15258962/147046001-acd8e337-b5b1-406c-b5a7-61024cdfc3cd.png)

**Comment by dkattan** [comment]
Could this potentially be related to: https://github.com/PowerShell/PowerShell/issues/10759

That issue has gotten some traction recently since I got to the bottom of the propertyname mismatch. 

Do the properties appear if you do:
```powershell
$item = Get-ChildItem "C:\Windows\WindowsUpdate.log" | ft
$item.PSObject.Properties.Name
```

Does it only happen on Windows PowerShell?

**Comment by JustinGrote** [comment]
@dkattan this test was on 7.2.1, I got the additional codeproperty objects but the core property objects don't show. That issue is more around format display of *serialized* objects, which might be related here. Haven't had time to fully dig into it yet.

**Comment by kborowinski** [comment]
@dkattan I don't think it is related at all. I don't serialize the *Get-ChildItem* output (I don't pipe to *Format-Table*) and  I get full property list on PowerShell 7.2 and PowerShell 5.1:

**PowerShell 7.2:**
![image](https://user-images.githubusercontent.com/16168755/147115594-a3c22226-b679-4b90-92f1-2770ff53e5d9.png)

**PowerShell 5.1:**
![image](https://user-images.githubusercontent.com/16168755/147115855-8d4dd812-59b6-4558-b876-4ca12e0b2aeb.png)

And when I rollback the PowerShell extension for VSC to latest stable version *(2021.10.2 that is)* I see all properties in the debug view. I think that it's related to recent changes in how PowerShell extension for VSC populates variables in the debug view.

*BTW: Format-Table from your example stripes all the FileInfo object properties obviously.*

**Comment by JustinGrote** [comment]
I didn't mean to imply it was a PS issue, I agree it's probably due to recent var changes, because we unified the code paths for both serialized and non-serialized objects and there's probably something in the reflection that is screwy.

**Comment by kborowinski** [comment]
@JustinGrote We are in agreement then 😉

@dkattan To add to my previous comment, bellow you have debug view from VSC with latest stable PowerShell extension (2021.10.2) running PowerShell 7.2 and PowerShell 5.1 and in both cases all properties are visible.

**VSC 1.63.2 (stable) with PowerShell extension 2021.10.2 (stable) and PowerShell 7.2:**
![image](https://user-images.githubusercontent.com/16168755/147120699-433e5ffc-aaa9-4982-8374-a11f11420146.png)

**VSC 1.63.2 (stable) with PowerShell extension 2021.10.2 (stable) and PowerShell 5.1:**
![image](https://user-images.githubusercontent.com/16168755/147120795-f477e6d0-0fe2-46e5-ba35-6e51a880c2d5.png)

**Comment by JustinGrote** [comment]
> @JustinGrote We are in agreement then 😉
> 
> @dkattan To add to my previous comment, bellow you have debug view from VSC with latest stable PowerShell extension (2021.10.2) running PowerShell 7.2 and PowerShell 5.1 and in both cases all properties are visible.

Yes this should be a decent workaround until we figure out why it's not pulling all of the properties

**Comment by JustinGrote** [comment]
Looks like for FileInfo objects specifically a GetValueInvocationException is getting swallowed and causing the silent failure of the remaining properties
```
Exception thrown: 'System.Management.Automation.GetValueInvocationException' in System.Management.Automation.dll
```

**Comment by JustinGrote** [comment]
@andschwa this might fall into your wheelhouse, its failing to fetch the property because a runspace isn't present
```
Exception has occurred: CLR/System.Management.Automation.GetValueInvocationException
Exception thrown: 'System.Management.Automation.GetValueInvocationException' in System.Management.Automation.dll: 'Exception getting "BaseName": "There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: $this.Name"'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Management.Automation.PSInvalidOperationException : There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: $this.Name
   at System.Management.Automation.ScriptBlock.GetContextFromTLS()
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.PSScriptProperty.InvokeGetter(Object scriptThis)
```

**Comment by andschwa** [comment]
@SeeminglyScience I wonder if this has to do with the last change we made here https://github.com/PowerShell/PowerShellEditorServices/pull/1635/commits/a0ab8e99b2a756af3546914ccf1c0418e20e4f8d or if this is related to the issue I noted we had to re-open here: https://github.com/PowerShell/PowerShellEditorServices/issues/86

**Comment by andschwa** [comment]
@kborowinski Can you prepare the the `n-1` Preview extension, that is, https://github.com/PowerShell/vscode-powershell/releases/tag/v2021.11.1-preview?

**Comment by kborowinski** [comment]
@andschwa Interestingly on 2021.11.1 properties are also incomplete in debug view like on 2021.12.0:
![image](https://user-images.githubusercontent.com/16168755/147151646-6544b879-87af-490d-9977-05e4b7113abf.png)

*FYI: I could not get debugging to work at all on 2021.11.0 and 2021.10.3 (PowerShell Integrated Consol crashes)*

**Comment by SeeminglyScience** [comment]
> @andschwa this might fall into your wheelhouse, its failing to fetch the property because a runspace isn't present

So you remember when I said "script properties might blow up though". Yeah turns out script properties blow up, we need to make sure we're excluding them. Or marshal back to the pipeline thread to get the value.

**Comment by JustinGrote** [comment]
@SeeminglyScience excluding them I can do for now, I may need help with the second part.

**Comment by JustinGrote** [comment]
Exclusion worked, tho I'm getting duplicate properties in some cases for some reason, looking into that:
![image](https://user-images.githubusercontent.com/15258962/147161765-169cec67-84cb-4388-956b-e0a82bd6c2dc.png)

The problem happens when calling SMA.PSPropertyInfo.Value. @SeeminglyScience is there a way to construct the PSPropertyInfo so that it is in the context of the runspace so when this getter is called it is able to fetch correctly?

**Comment by JustinGrote** [comment]
@SeeminglyScience here's where it happens:
https://github.com/PowerShell/PowerShellEditorServices/blob/15650c35341ea6999d33bf431882922aaf0c1d0c/src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs#L44-L47

**Comment by JustinGrote** [comment]
https://stackoverflow.com/questions/55776105/how-to-get-scriptproperty-values-of-psobject-properties-in-c

Seems to suggest a better approach would be to retrieve the associated script and run it inside the runspace, would need to be careful it doesn't pollute the history for instance.

**Comment by SeeminglyScience** [comment]
You just need to be sure you're on the pipeline thread when you retrieve the value. I believe `PowerShellContextService` has an `InvokeOnPipelineThreadAsync` method. That said, it may be difficult to transition to the pipeline thread and back for every single property. It may be better to retrieve all values at once while on the pipeline thread and then relinquish. Otherwise I think it likely we'll be setting ourselves up for reliability issues.

**Comment by andschwa** [comment]
@JustinGrote You can use this method on the host to execute an arbitrary C# function within the PowerShell context:

https://github.com/PowerShell/PowerShellEditorServices/blob/149f5ac1089fef8344f8a5849a211a1ba9a88431/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L307-L314

**Comment by JustinGrote** [comment]
I am

**Comment by iSazonov** [comment]
I prepared a workaround fix https://github.com/PowerShell/PowerShell/issues/10759#issuecomment-1017706145 - feel free to grab and pull PR.

**Comment by andschwa** [comment]
Hold up, after looking at what @iSazonov linked, can I get a confirmation that this is a bug in PSES? That thread makes it appear that this is actually an upstream regression in PowerShell 7. Let me know!

**Comment by iSazonov** [comment]
I don't think any workaround is needed in PSES since it was a change in PowerShell itself. It's not hard to fix it there and even port it back to current LTS version.

**Comment by andschwa** [comment]
Thanks @iSazonov! I'll mark this as resolved for now.
