### ISSUE TITLE
Recover PRs lost in pipeline rewrite rebase 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PowerShellEditorServices#1677]
When rebasing the pipeline rewrite work we werent pulling in the changes we made, just overwriting them with rewritten code that wasn't reconciled with updates...as a result of this a number of PRs need to be rewritten/re-added to the code base. these are the PRs we know of that need to be recovererd: 

- [x] https://github.com/PowerShell/PowerShellEditorServices/pull/1514
- [x] https://github.com/PowerShell/PowerShellEditorServices/pull/1522
- [x] https://github.com/PowerShell/PowerShellEditorServices/pull/1570
- [x] https://github.com/PowerShell/PowerShellEditorServices/pull/1571

**Comment by andschwa** [comment]
Thanks for capturing these @SydneyhSmith. Good news: we've managed to already get 3/4 of these.
