### ISSUE TITLE
PS 5.1: Wait-Debugger does not trigger debug mode

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1681]
![image](https://user-images.githubusercontent.com/15258962/150899402-a2d50306-1a23-43e2-ba64-47e24fa224e8.png)

This works in PS7. I think it may be due to how "BreakAll" works and may have changed in 7. This may be something that is just considered 5.1 deprecated behavior.

**Comment by SeeminglyScience** [comment]
5.1 needs `& { Wait-Debugger }` even outside of PSIC. I believe you are correct that it's the change around `BreakAll`. Doesn't immediately enter the debugger but instead triggers on the next sequence point which never comes.

**Comment by JustinGrote** [comment]
@SeeminglyScience sounds good, I'll mark this as answered just it's here in case someone else comes across it.
