### ISSUE TITLE
Problems with GetText()

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/PowerShellEditorServices#1682]
I have a number of functions in my VSCode profile that relies on EditorServices. In previous versions, I used to be able to run code like this to get selected text in a file.

```powershell
$context = $psEditor.GetEditorContext()
$range = $context.SelectedRange
$context.CurrentFile.GetText($range) 
```
But now, in with both the Windows PowerShell and PS 7.2.1 integrated terminal I get an error `Cannot find an overload for "GetText" and the argument count: "1".`

Eventually, I came up with this:

```powershell
$context = $psEditor.GetEditorContext()
$fr = [Microsoft.PowerShell.EditorServices.Extensions.FileRange]::new($context.SelectedRange.Start,$context.SelectedRange.end)
$context.CurrentFile.GetTextLines($fr) 
```

In Windows PowerShell this works as expected. But it fails in PowerShell 7.

![image](https://user-images.githubusercontent.com/12089920/151015562-f2a8936b-2224-4c1d-bcd4-8a1af01b1c51.png)

![image](https://user-images.githubusercontent.com/12089920/151015666-5b35e128-6e13-4698-94f1-928ebe227848.png)

It would help if there were consistency between PowerShell hosts.

**Comment by SeeminglyScience** [comment]
This is due to some unfortunate side effects caused by our use of assembly load contexts in 7.

For a workaround, you can assembly qualify the type expression:

```powershell
[Microsoft.PowerShell.EditorServices.Extensions.FileRange, Microsoft.PowerShell.EditorServices]
```

This will work in both 5.1 and 7, though is unfortunately quite verbose.
