### ISSUE TITLE
Variable Expansion: ScriptProperty ToStrings are slow to perform

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1686]
![image](https://user-images.githubusercontent.com/15258962/151281274-b443b5f7-c8f3-47e4-abf4-298a17384a98.png)

Per @SeeminglyScience it's probably because the ToString is trying to marshal to the pipeline thread and deadlocking.

**Comment by JustinGrote** [comment]
Looks like it doesn't happen unless $this is involved (this probably gets translated into something that doesn't require the pipeline to execute)
![image](https://user-images.githubusercontent.com/15258962/151477226-ba3fdf3d-d9af-47ac-8bb5-45e012999d76.png)

**Comment by JustinGrote** [comment]
Narrowed it down to this loop for enumerables that is "slow", I'll dig deeper into `VariableDetails` later.
https://github.com/PowerShell/PowerShellEditorServices/blob/624fe30eda7b7dc918978e238a59b26b81a40dc7/src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs#L338-L344

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience looks like it's not hard-hanging, just a performance issue. Could this have to do with the marshaling still?

Yep!

In certain circumstances (like this one) it will timeout after 250ms and then just invoke it anyway from a different thread (while still targeting the same runspace) potentially causing state corruption. So I'd say that still perfectly explains it and potentially makes it a little bit more scary.

**Comment by JustinGrote** [comment]
Here's the culprit: 
https://github.com/PowerShell/PowerShellEditorServices/blob/624fe30eda7b7dc918978e238a59b26b81a40dc7/src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs#L198

If you set it to null instead of `SafeToString()`, everything is fast again.

**Comment by JustinGrote** [comment]
More specifically:
https://github.com/PowerShell/PowerShellEditorServices/blob/3274c230cc6675859d5c89d6c176219c2c9430f7/src/PowerShellEditorServices/Utility/Extensions.cs#L25

@SeeminglyScience how would I get this obj.ToString() method on the correct pipe? It does feel like about a 250ms delay on each invocation.

**Comment by JustinGrote** [comment]
Adding @SeeminglyScience as I've hit my limits on figuring this out for now :)

**Comment by andschwa** [comment]
And fixed, with your test too!
