### ISSUE TITLE
Crash when `prompt` is undefined in the runspace

### ISSUE THREAD

**Issue by dkattan** [PowerShell/PowerShellEditorServices#1699]
When "prompt" isn't defined in the runspace the fallback to DefaultPrompt doesn't work because we aren't catching the CommandNotFoundException

https://github.com/PowerShell/PowerShellEditorServices/blob/b433b0f2d1b0e9b93466b5e307a202bfe290c841/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L662-L664

**Comment by JustinGrote** [comment]
Thanks! I don't want to know how you discovered this :P
