### ISSUE TITLE
Cancel Keystroke should not end a debugging session in the pipeline

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1708]
To reproduce:
```
Hit F5 to start debug
Wait-Debugger
Hit ctrl-c, note that it doesnt end the PSES session
sleep 5
Hit ctrl-c, note that the PSES debug session dies
```

**Comment by andschwa** [comment]
I'm going to drop a new preview, let's see if this still repros.

**Comment by andschwa** [comment]
Yeah this is working as intended. We wired up `OnCancelKeyPress` to stop the debugger here: https://github.com/PowerShell/PowerShellEditorServices/commit/0f52aa2fe126add8f44852a21e3d3ee454bd8f18

**Comment by JustinGrote** [comment]
@andschwa confirmed working fine in new preview, thanks! I did notice ctrl-c with `sleep 5` will end the debug session if running a "naked" psinteractive session, reopening to confirm if that's what we want or if we want to fix that too.

To repro:
Launch config
```
			{
				"name": "PS: Interactive",
				"presentation": {
					"group": "Powershell"
				},
				"request": "launch",
				"type": "PowerShell"
			},
```

`sleep 5` and hit ctrl-c, it will end the session.

**Comment by andschwa** [comment]
That makes sense, I don't see anyway we'd be able to differentiate debugged tasks in an PS Interactive session. Technically they're _all_ under the debugger.

**Comment by andschwa** [comment]
The fix for this is out in [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell-preview)!
