### ISSUE TITLE
Intellisense breaks if you quickly delete and re-type after last intellisense

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1720]
This might be upstream omnisharp related...

### Reproduce
1. Type `[cm` and get CmdletBindingAttribute recommendation.
1. Quickly type backspace-backspace-cm
1. No intellisense appears and error shows in PSES terminal:
`[Warn  - 12:01:38 PM] Microsoft.PowerShell.EditorServices.Handlers.PsesCodeActionHandler: textDocument/codeAction skipping diagnostic with empty Code field: PowerShell Missing ] at end of attribute or type literal. | `

![image](https://user-images.githubusercontent.com/15258962/154861952-c46cc0e3-802a-440b-8905-fc00ad9e7bf8.png)

**Comment by StevenBucher98** [comment]
Thanks @JustinGrote, does the intelliSense recover after this happens?

**Comment by JustinGrote** [comment]
@StevenBucher98 seems to, yeah

**Comment by SeeminglyScience** [comment]
I can't actually tell if intellisense is broken or if it's really just not technically hit an intellisense trigger character. <kbd>Ctrl</kbd> + <kbd>Space</kbd> seems to work fine even when done rapidly.

**Comment by SydneyhSmith** [comment]
This may be fixed with our recent releases @JustinGrote are you still experiencing this issue?
