### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShellEditorServices#1733]
This covers the desire to go back through recently merged PRs (and my own Git stashes) to see what bugs we fixed that could be covered with a regression test (for stability purposes). @SydneyhSmith we can use this for tracking!

## Completed test work:
- https://github.com/PowerShell/PowerShellEditorServices/pull/1651
- https://github.com/PowerShell/PowerShellEditorServices/pull/1522
- https://github.com/PowerShell/PowerShellEditorServices/pull/1820 / PSES #1695
- https://github.com/PowerShell/PowerShellEditorServices/pull/1821 / https://github.com/PowerShell/PowerShellEditorServices/pull/1807
- https://github.com/PowerShell/PowerShellEditorServices/pull/1828 / https://github.com/PowerShell/vscode-powershell/issues/3718
- https://github.com/PowerShell/PowerShellEditorServices/pull/1830 / https://github.com/PowerShell/vscode-powershell/issues/3965
- https://github.com/PowerShell/PowerShellEditorServices/pull/1832 / https://github.com/PowerShell/PowerShellEditorServices/pull/1604
- https://github.com/PowerShell/vscode-powershell/issues/3980 / https://github.com/PowerShell/PowerShellEditorServices/pull/1857
- https://github.com/PowerShell/PowerShellEditorServices/pull/1864 / https://github.com/PowerShell/vscode-powershell/issues/2697
- https://github.com/PowerShell/PowerShellEditorServices/pull/1866 / https://github.com/PowerShell/vscode-powershell/issues/4073
- https://github.com/PowerShell/PowerShellEditorServices/pull/1858 / https://github.com/PowerShell/vscode-powershell/issues/3715
- https://github.com/PowerShell/PowerShellEditorServices/pull/1861 / https://github.com/PowerShell/vscode-powershell/issues/3655
- https://github.com/PowerShell/PowerShellEditorServices/pull/1710 / https://github.com/PowerShell/PowerShellEditorServices/issues/1699
- https://github.com/PowerShell/PowerShellEditorServices/pull/1870 / https://github.com/PowerShell/vscode-powershell/issues/3252
- https://github.com/PowerShell/PowerShellEditorServices/pull/1874 / https://github.com/PowerShell/PowerShellEditorServices/issues/1663
- https://github.com/PowerShell/PowerShellEditorServices/pull/1846 / https://github.com/PowerShell/PowerShellEditorServices/issues/1672
- https://github.com/PowerShell/PowerShellEditorServices/pull/1890 / https://github.com/PowerShell/PowerShellEditorServices/issues/1887
- https://github.com/PowerShell/PowerShellEditorServices/pull/1893 / https://github.com/PowerShell/PowerShellEditorServices/issues/1891
- https://github.com/PowerShell/PowerShellEditorServices/issues/1663 / https://github.com/PowerShell/PowerShellEditorServices/pull/1874
- https://github.com/PowerShell/vscode-powershell/issues/3683 / https://github.com/PowerShell/PowerShellEditorServices/pull/1914

### Debugging 
- https://github.com/PowerShell/PowerShellEditorServices/pull/1685
- https://github.com/PowerShell/PowerShellEditorServices/pull/1704
- https://github.com/PowerShell/vscode-powershell/issues/3832
- https://github.com/PowerShell/vscode-powershell/issues/3849
- https://github.com/PowerShell/PowerShellEditorServices/pull/1762
- https://github.com/PowerShell/PowerShellEditorServices/pull/1778
- https://github.com/PowerShell/vscode-powershell/issues/3944
- https://github.com/PowerShell/vscode-powershell/issues/3950

### Host
- https://github.com/PowerShell/PowerShellEditorServices/issues/1667
- https://github.com/PowerShell/vscode-powershell/issues/3685
- https://github.com/PowerShell/PowerShellEditorServices/pull/1692
- https://github.com/PowerShell/vscode-powershell/issues/3807
- https://github.com/PowerShell/PowerShellEditorServices/issues/1639
- https://github.com/PowerShell/PowerShellEditorServices/pull/1781
- https://github.com/PowerShell/vscode-powershell/issues/4010
- https://github.com/PowerShell/PowerShellEditorServices/issues/1603
- https://github.com/PowerShell/vscode-powershell/issues/3786

### IntelliSense
- https://github.com/PowerShell/PowerShellEditorServices/pull/1799 (this may not belong in this list)
- [`SymbolService.FindFunctionDefinitionAtLocation()`](https://github.com/PowerShell/PowerShellEditorServices/pull/1890#issuecomment-1215890680) 

### PSSA 
- https://github.com/PowerShell/PowerShellEditorServices/pull/1718
- https://github.com/PowerShell/PowerShellEditorServices/pull/1749
- https://github.com/PowerShell/vscode-powershell/issues/3928

### Startup 
- https://github.com/PowerShell/PowerShellEditorServices/pull/1514
- https://github.com/PowerShell/PowerShellEditorServices/pull/1641

**Comment by SydneyhSmith** [comment]
> @SydneyhSmith How are we tracking in here which are done or not?

Was thinking moving from the remaining work section to the completed work section

**Comment by SydneyhSmith** [comment]
Next item is to create a doc of manual tests to complete for releases...assigning to myself
