### ISSUE TITLE
Fix attach to process debugging

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#1736]
See PowerShell/vscode-powershell#3849

**Comment by JustinGrote** [comment]
As a "nice to have" on this, PSES could watch for a runspace in the PSIC to go to InBreakpoint state, and then advertise a new "child" debug session in vscode that enters at that breakpoint. How that would look in terms of the PSIC (or a new dummy PSIC or something) is TBD, but seems feasible once the foundation aspect of this is sorted.

**Comment by SeeminglyScience** [comment]
So what's kind of complicated about that, is if PSES isn't involved in the runspaces creation, we don't actually have much in the way of hooks.

iirc a runspace with the default host (literally `DefaultHost`, not the one from `pwsh.exe`) just straight up ignores breakpoints. On top of that, what do we do when *multiple* runspaces hit a breakpoint. Part of the issue is we don't have a way to globally freeze a process like dotnet does. There's no central tie in to runspaces like there is for threads in dotnet.

Can you tell I've thought about this a lot? 😁 I'd love to get to closer parity with how flawlessly omnisharp handles multiple threads, but we may very well need better support from the engine to do so.

**Comment by JustinGrote** [comment]
At least on the multiple runspaces part, at the vscode level we can expose that as multiple debug sessions in the dropdown, but what gets tricky is handling the messaging there via omnisharp, yes. Also IMHO wouldn't be expected to freeze all of the session if one runspace goes into breakpointing, all the other runspaces would continue to operate. That would for sure make things like race conditions harder to troubleshoot etc. but I think most runspace usage in PS is fan-out non-related isolated scriptblocks (foreach -parallel, start-threadjob, and the like)  so I don't think this is a big issue.

So I mean there's `Get-Runspace`, is there not a C# level way of hooking into that info?

**Comment by SeeminglyScience** [comment]
> but what gets tricky is handling the messaging there via omnisharp, yes.

Oops my bad! By omnisharp I meant more the CLR's debugging infrastructure. Poor choice of words on my part since we also happen to use the omnisharp team's LSP implementation 😁 

> Also IMHO wouldn't be expected to freeze all of the session if one runspace goes into breakpointing, all the other runspaces would continue to operate.

That's definitely how I would want it. It would be the only safe way to examine the state of the other runspaces at the same time, and would prevent the inevitable issue of multiple runspaces hitting breakpoints at the same time.

> That would for sure make things like race conditions harder to troubleshoot etc. but I think most runspace usage in PS is fan-out non-related isolated scriptblocks (foreach -parallel, start-threadjob, and the like) so I don't think this is a big issue. 90% of the time that I've wanted this, it's because my threadjob isn't working and I wish I could just breakpoint it rather than have to throw in a wait-debugger or comment out or have a flag to say "don't do this in a runspace so I can debug it"

I would argue that's not too dissimilar to the use case of threads in C# either. Often many of the threads are only vaguely related to each other, but stopping all execution to examine one is still critical imo.

> So I mean there's `Get-Runspace`, is there not a C# level way of hooking into that info?

There's no event that triggers saying that a runspace is created. Like we could run `Get-Runspace` to figure out what's out there, but if a runspace is created mid script we would have no hooks into that process.
