### ISSUE TITLE
Attribute Argument Completions don't work unless at least one letter is specified

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1737]
![image](https://user-images.githubusercontent.com/15258962/157075590-d2c8c765-d719-4f54-9120-0b3a6b6c4c1f.png)

![image](https://user-images.githubusercontent.com/15258962/157075677-730fa903-97ea-4d6f-b954-d4c403776aa7.png)

**Comment by andschwa** [comment]
Closing as external, @JustinGrote you can open an issue in the PS repo if you want 😄
