### ISSUE TITLE
Switch to time-oriented milestone naming strategy

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#174]
The PowerShell team is starting to track work items on GitHub by looking at issue milestones.  The expectation is that each milestone will be marked with a name based on the year and month in the form YYMM.  For example, March 2016 would be `1603`.

Going forward we should use this milestone naming strategy barring the introduction of other options.  I might see if I can negotiate using labels with this format instead of milestones since I prefer the version-based milestone name format.

**Comment by rkeithhill** [comment]
So is `1603` effectively the `0.5.0` release?

**Comment by daviwil** [comment]
Not exactly...  That's the main thing I don't like about this.  My intent is to have (at least) 1 release out per month but these milestone markers won't capture that accurately.  I'll ask around and see if I can use labels instead.

**Comment by daviwil** [comment]
Though I suppose labels also are tricky because you can't "close" them like you can milestones.  We'd just end up with a bunch of YYMM labels gunking up the label list...

**Comment by daviwil** [comment]
OK, on second thought, I think we can skip this :)  Milestones can have a registered end date.  I think I can use that to generate the YYMM milestone info for our tracking system so that we don't need to change our existing milestone naming strategy.  Closing this for now.
