### ISSUE TITLE
Powershell Intellisense in Terminal

### ISSUE THREAD

**Issue by IllinoisDOI** [PowerShell/PowerShellEditorServices#1742]
Does PowerShell have intellisense in the Terminal command line and if so how do you turn it on in Visual Studio Code?  I use it all the time in the ISE.

**Comment by JustinGrote** [comment]
It doesn't have the "pop-up" style intellisense of ISE, this is basically impossible to implement due to the vscode terminal APIs.

**Comment by IllinoisDOI** [comment]
Thank you!  It’s too bad I love that feature on ISE.  It helps a person learn the language.

From: Justin Grote ***@***.***>
Sent: Monday, March 14, 2022 4:57 PM
To: PowerShell/PowerShellEditorServices ***@***.***>
Cc: Powell, David L. ***@***.***>; Author ***@***.***>
Subject: [External] Re: [PowerShell/PowerShellEditorServices] Powershell Intellisense in Terminal (Issue #1742)


It doesn't have the "pop-up" style intellisense of ISE, this is basically impossible to implement due to the vscode terminal APIs as they exist today.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1Q-of3uSDcYuJ8eSKPZQb782yTpSTmY-T2xD7GfyymrwIN-2FKr2T0QDcFMrRBARMtCediw3PUW-nYMEyBlFoh7rFPH44-uvaB4yuLil2FgjoE-C9nlu42i5s6pWpfIPiaQmsg44WhViEXrb4wSAFBmy6q8hPprILGtGh8JOoYAg8r6n35MZUSEZ75N3oBp__C0l_M34qTPxcV5CqmUZp_wV5iAceC4R8KM0d2E_f1iLZ52Hfl8-KNN0nc8bImW5KDsEABz7TaCHiblMDYpnJNt4HBT3VryinkPdmjvfryl0m6hFuo42PbcnBBeCHTjO-GsNAc5f7beaPSFNlxZNEiNP_0gRYwaY1Z0zcgp0YvBKxKn4rTVImrrwTw-QG3hk2QVLbrD9PWjtnZtBBLCznGhvJKzVe8GzpVxZNJ5GxQjM/https%3A%2F%2Fgithub.com%2FPowerShell%2FPowerShellEditorServices%2Fissues%2F1742%23issuecomment-1067336750>, or unsubscribe<https://secure-web.cisco.com/1XNea_SQFv_cPfV7XOUBBvwm1I4V_EPrQrHorYgs5K6S2VoYOnXjXV2zSoLNpoYt1s-Mirlb4YyADeDz0I8S8dT77TxlnskhJNjlsdcHQpheY9fVKHy8EZzV9x5ZnuM3rg4ruyaAiUPiDjDMS1rmAeNqlBcRH0pQnqsftKK05vKz-n3h8HFQKjh65wjb_QgWgMmAJ6tgy7PKQuPMBOdUL3lm-1G6uZE0UuEnE_yuTQz0WAifZRQvze81HZ93OJzfNjQHCKVsmgQFkzh2_w_TKj-Z8bdKZq_p4XHverqbky1sYdumviZHpK3XvM-Z-EV2YMFJwOCivBypgHeT4BVbA7YSKF758zscN-ZwsVTqqbMHco3ZwbNTd8dl7lrLtB3WKBzdaiywttGPzMLuWLs6Xdb10HZKrpatqRXr-qSauBCk/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ6ZEEKST5VCL66CZQP53SDU76YZHANCNFSM5QWRUROQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>


State of Illinois - CONFIDENTIALITY NOTICE: The information contained in this communication is confidential, may be attorney-client privileged or attorney work product, may constitute inside information or internal deliberative staff communication, and is intended only for the use of the addressee. Unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful. If you have received this communication in error, please notify the sender immediately by return e-mail and destroy this communication and all copies thereof, including all attachments. Receipt by an unintended recipient does not waive attorney-client privilege, attorney work product privilege, or any other exemption from disclosure.
