### ISSUE TITLE
Investigate the UX around setting breakpoints in existing sessions

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#1756]
I was helping someone troubleshoot what a breakpoint wasn't getting hit and after they stopped the debugger and restarted it magically started working.

I think we're probably only setting breakpoints when `startDebugging` is called and I want to check if the breakpoint events are hooked up properly.

**Comment by JustinGrote** [comment]
Breakpoints do wire up if you set new ones in the course of execution (it triggers a set-breakpoint action), at least for a simple script, there may be certain scenarios it doesn't stick.

**Comment by SeeminglyScience** [comment]
Yeah that's what I gotta figure out. I know it doesn't work right in attach but that might be an engine limitation
