### ISSUE TITLE
Update all async API methods to use "Async" suffix

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#177]
In our work to clean up the API for a stable 1.0 release later this year, we'll need to decide whether we want to use the "Async" suffix on any async methods so that their usage is clear.  I personally don't like the suffix but I can understand why it's useful.  I wonder if the general guidelines for the usage of this suffix will go away as more and more .NET API methods become async.

Thoughts?

**Comment by rkeithhill** [comment]
I think async methods should be suffixed with Async. The Microsoft prescribed guidance is:

> The name of an async method, by convention, ends with an "Async" suffix.

From https://msdn.microsoft.com/en-us/library/hh191443.aspx.  

I see Stephen Cleary using the convention consistently in the "Concurrency in C# Cookbook".  Yep, been reading through it.  Thanks for the recommend.  :-)

**Comment by daviwil** [comment]
It's a good book!  Alright, we'll use *Async.  It'd definitely eliminate confusion about which methods should be called with await.  Any new async methods you add in the meantime, feel free to use the Async suffix.

**Comment by rkeithhill** [comment]
Will do.

**Comment by dee-see** [comment]
Is this still planned? I don't mind doing it. Should the PR be against the 2.0.0 branch?

**Comment by tylerl0706** [comment]
It's on the backlog for sure - no one's actively working on it AFAIK. Against 2.0.0 is probably the right approach!

**Comment by dee-see** [comment]
Ok I'll pick this one up then if it's up for grabs for anyone.

Should a method that returns a `Task` but isn't marked with `async` be suffixed with -Async anyway?

**Comment by tylerl0706** [comment]
If it returns a task, then the function is expecting it to be awaited so I say add it.

**Comment by NageshAndani** [comment]
This issue needs to be closed as it is fixed by @dee-see  #792
