### ISSUE TITLE
Revamp logger/logging

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PowerShellEditorServices#1796]
We have a bunch of issues around logging to fix:
* When we look for logs, what we're expecting is never there
* The way we use the logger itself is explicitly marked as "inefficient" and wrong
* The logger values are defined in three different ways
* Most of the places we log an exception, we're not actually logging it

We should do this when we do telemetry, as part of an "observability" project.

**Comment by andyleejordan** [comment]
@JustinGrote pretty much fixed all of this.
