### ISSUE TITLE
Typed Variables should intellisense hashtable properties

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1852]
### Summary of the new feature / enhancement

This:
![image](https://user-images.githubusercontent.com/15258962/177668095-fd7cded7-5d9f-4055-b9e3-d1970621f2d7.png)

Should work the same as this:
![image](https://user-images.githubusercontent.com/15258962/177668045-734a2ed4-edc9-4939-b2d3-2375d024f284.png)

**Comment by ALIENQuake** [comment]
@SeeminglyScience The `.Ast.GetScriptBlock()` ❤️

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience The `.Ast.GetScriptBlock()` ❤️

yeah in this case that just makes it so the editor command stays in the session state (module) that's current. A little different from the use cases I've suggested it to you for, it's a very versatile trick 😁
