### ISSUE TITLE
Simplify PSES CLI so startup with non-Code editors is easier

### ISSUE THREAD

**Issue by andyleejordan** [PowerShell/PowerShellEditorServices#1855]
It takes _way_ too many arguments to launch PSES correctly, which is blocking #1829. Once we simplify this, we could conceivably add a `-lsp` flag to PowerShell itself that would simplify it even further.

**Comment by smartguy1196** [comment]
How definitive is this? Do you intend to completely rewrite the CLI/introduce "breaking changes" with this? I imagine that any changes you make would be backward compatible, but I'm asking, because my PSES manual controller is dependent on how your CLI works.

**Comment by andschwa** [comment]
I don't _intend_ to make breaking changes. The best coverage I have for that is

https://github.com/PowerShell/PowerShellEditorServices/blob/9416a8ae9c7df5a2539731388753e558193c37fb/test/emacs-test.el#L48-L54

and 

https://github.com/PowerShell/PowerShellEditorServices/blob/9416a8ae9c7df5a2539731388753e558193c37fb/test/vim-test.vim#L6-L13

**Comment by fai8146767** [comment]
### ****
