### ISSUE TITLE
Function reference not counted in codelens when on same line as definition

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShellEditorServices#1889]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Create a function and invoke it on the same line. See image.

### Expected behavior

```console
Invocation is counted in codelens
```

### Actual behavior

```console
Invocation isn't counted in codelense.
Go to reference detects the invocation as expected.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

2022.8.2 preview

### Visuals

![image](https://user-images.githubusercontent.com/3436158/184547912-b7f4540a-2af6-4aa7-a6e9-a65a26824e38.png)

This issue also means this will show 2 references in code lense because it counts the function-name in definition itself:

```powershell
function
funcNewline {
    'hello'
}

funcNewline
```

**Comment by fflaten** [comment]
Looks like the problem is here where it only compares file and startline.
https://github.com/PowerShell/PowerShellEditorServices/blob/948dffe080cb93b6c2d6b8fb5544788d2bcb5a83/src/PowerShellEditorServices/Services/CodeLens/ReferencesCodeLensProvider.cs#L170-L183

Suggestions
1) **Quick fix:** Compare reference startcolumn not equal

2) Should CommandAst use the same `SymbolType.Function` as definitions? Not extend with a new `SymbolType.Command` for invocations? Then we could use that for found references in [FindReferencesVisitor.VisitCommand(CommandAst)](https://github.com/PowerShell/PowerShellEditorServices/blob/948dffe080cb93b6c2d6b8fb5544788d2bcb5a83/src/PowerShellEditorServices/Services/Symbols/Vistors/FindReferencesVisitor.cs#L96-L104)? *I assume that's the source, haven't stepped through yet*

**Comment by andschwa** [comment]
Theoretically fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/1984
