### ISSUE TITLE
Debug pause seems to be broken in 0.5.0

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#189]
Open up the examples folder, select DebugTest.ps1, press F5 to start debugging and then press the `pause` or `stop` buttons.  The debug host appears to be hung from the VS Code UI.

**Comment by daviwil** [comment]
It's working for me, see anything interesting in the logs?

**Comment by rkeithhill** [comment]
Hmm, at home with 0.5.0 installed it seems to be working fine.  I'd tried this earlier at work today.  Let me try it again tomorrow and see if I can figure out if I had something misconfigured.

**Comment by rkeithhill** [comment]
I wonder if I was seeing [this issue](https://github.com/PowerShell/PowerShellEditorServices/issues/196) but on the Alpha build before it made its way to the Insiders channel?  If so, maybe we close this as a duplicate?

**Comment by daviwil** [comment]
You're probably right! Yeah, let's close it as a duplicate of #196.

**Comment by rkeithhill** [comment]
Duplicate of [#196](https://github.com/PowerShell/PowerShellEditorServices/issues/196)
