### ISSUE TITLE
Pester symbols for setup/teardown blocks

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShellEditorServices#1892]
### Summary of the new feature / enhancement

Add document symbols for Pester's setup/teardown blocks for outline/navigation-purposes
- BeforeAll
- BeforeEach
- AfterAll
- AfterEach
- BeforeDiscovery

The blocks are unnamed, but outline shows order and nesting so they still make sense.

### Proposed technical implementation details (optional)

Only document symbols for outline. No references/definition or code lense.

**Comment by fflaten** [comment]
If this makes sense to support, I can offer to look into it. Feels like I'm getting acquainted with the symbol providers lately 😄

**Comment by fflaten** [comment]
Maybe also `InModuleScope <Module>`. Not as important, though it would make so much sense with the new experimental vscode sticky scroll which reuse the same symbols.
![image](https://user-images.githubusercontent.com/3436158/184674132-30c79b96-032a-4f36-a70b-7f02c311fc0d.png)

@nohwnd Thoughts on this (issue as a whole)?

**Comment by nohwnd** [comment]
> @nohwnd Jakub Jares FTE Thoughts on this (issue as a whole)?

I like it. 🙂
