### ISSUE TITLE
CodeLens range not following LSP-spec

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShellEditorServices#1904]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Debug extension or see LSP log while it's looking up code lenses for a function definition, Pester block etc.

### Expected behavior

```console
interface CodeLens {
	/**
	 * The range in which this code lens is valid. Should only span a single
	 * line.
	 */
	range: Range;
...

Source: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeLens
```

### Actual behavior

```console
Range is for full definition, spanning multiple lines.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

2022.8.3 preview

### Visuals

![image](https://user-images.githubusercontent.com/3436158/185794657-15605eae-52ee-4857-98ee-d3d7071ab5b2.png)

**Comment by fflaten** [comment]
Code lens should also follow the symbol name. Currently it's placed above extent start (function keyword), but should follow symbol name in case function-keyword is followed by a linebreak.

Now:
![image](https://user-images.githubusercontent.com/3436158/185795272-fd8688b9-3538-43db-90fd-f94eb0fab5e9.png)

Suggestion:
![image](https://user-images.githubusercontent.com/3436158/185795376-5fdb251b-7c57-48d2-bf07-a36d11bff11d.png)

Like C#:
![image](https://user-images.githubusercontent.com/3436158/185795481-aaf4e00b-b1c7-4bc7-a27b-91cdcc096f46.png)

**Comment by andschwa** [comment]
I think fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/1984
