### ISSUE TITLE
Debug adapter should show validation error when launch.json 'args' parameter is not an array

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#191]
Apparently Visual Studio Code does not prevent the user from specifying a single string for the "args" parameter even though our schema calls for an array.  We'll need to find some way to send back an appropriate error when we can't deserialize this object due to a string being present in this field.

More info: https://github.com/PowerShell/vscode-powershell/issues/118

Alternatively we could just accept the string but it would be hard to represent it correctly in the schema.  It's probably better to just show an error and force a single way to provide parameters.

**Comment by rkeithhill** [comment]
Isn't it the VSCode schema that dictates that `args` should be an array?

**Comment by daviwil** [comment]
Apparently it's dictated by our own schema that we define in our package.json.  They only warn the user if they enter a value of a type that isn't accepted.

**Comment by rkeithhill** [comment]
Ah, in the debuggers -> initialConfigurations.  Gotcha.

**Comment by SydneyhSmith** [comment]
Closing as we are already tracking in above VSCode issue
