### ISSUE TITLE
gh-pages branch does not work (404 error) 11 SEP 2022

### ISSUE THREAD

**Issue by smartguy1196** [PowerShell/PowerShellEditorServices#1930]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Load GH-pages URL for this repo like this one from the README.MD ($psEditor API):

http://powershell.github.io/PowerShellEditorServices/guide/extensions.html

Results in 404 error

### Expected behavior

```console
Loads webpage
```

### Actual behavior

```console
404 error
```

### Error details

```console
See attached image
```

### Environment data

```PowerShell
Chrome v105.0.5195.102 - Windows 10
```

### Version

N/A

### Visuals

![image](https://user-images.githubusercontent.com/12621101/195235633-6e1e400e-0e33-44a9-a59f-f9892ca1288a.png)

**Comment by andschwa** [comment]
The site was taken down as it was years out of date.

**Comment by smartguy1196** [comment]
@andschwa you didn't remove the link from the readme

**Comment by andschwa** [comment]
I didn't know they were there 🤷 thanks for the PR!
