### ISSUE TITLE
Replace WriteSessionObject code with a Session.Text.Json implementation

### ISSUE THREAD

**Issue by smartguy1196** [PowerShell/PowerShellEditorServices#1939]
### Summary of the new feature / enhancement

[This block of code](https://github.com/PowerShell/PowerShellEditorServices/blob/3602eec8cc2ab016b4b720263368cbecde77cc7d/src/PowerShellEditorServices.Hosting/Configuration/SessionFileWriter.cs#L122) Serializes JSON by running PowerShell code in C#, which introduces a bug and also introduces bloat. This bug is corrected on [Line 138](https://github.com/PowerShell/PowerShellEditorServices/blob/3602eec8cc2ab016b4b720263368cbecde77cc7d/src/PowerShellEditorServices.Hosting/Configuration/SessionFileWriter.cs#L138), but it would be better to ~~just use C# in C#~~ use System.Text.Json in this file.

### Proposed technical implementation details (optional)

Here is an [example of how to use System.Text.Json](https://stackoverflow.com/a/58294305/10534510)

I propose that we use features built-in with C# instead of trying to do it with PowerShell

**Comment by smartguy1196** [comment]
On an unrelated note, this is definitely one of the funniest instances of bloat code in this repository.

There's a few [other possible instances of bloat code that I have found](https://hackaday.io/project/187723-source-code-analysis-powershelleditorservices/log/213061-bloat-code-tracker), but this one is my favorite

**Comment by andschwa** [comment]
This issue (and your blog posts) are not constructive, please review this community's [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) before participating in the future. Thank you!

**Comment by smartguy1196** [comment]
Apologies. Removing myself, unsubbing, and closing issue.
