### ISSUE TITLE
Add support for running a script without debugging it

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#194]
This is exposed in VSCode via the <kbd>Ctrl</kbd>+<kbd>F5</kbd> keyboard shortcut or the `Debug: Run` command.  I'm not sure that needs to be different here other than to not set any breakpoints but presumably VSCode won't set any since it is not Debug.  This "might" be trivial.  :-)  

BTW this will be a few VSCode feature in the upcoming March release - see https://github.com/Microsoft/vscode/issues/2780#issuecomment-195310582

**Comment by rkeithhill** [comment]
Which keyboard shortcut should we use for Expand Alias as it will need to change from Ctrl+F5.  PSReadline sample uses <kbd>Alt</kbd>+<kbd>%</kbd> IIRC

**Comment by dfinke** [comment]
Ctrl+Alt+E ?

**Comment by rkeithhill** [comment]
I have also found that <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>r</kbd> is available - `r` for resolve or `e` for expand.  Both would work but I lean towards @dfinke suggestion.

**Comment by daviwil** [comment]
Yeah, I like Ctrl+Alt+E too.
