### ISSUE TITLE
RequestRefactor hotkey throws an `InternalError` when calling `$CommandSuite.RequestRefactor($PSCmdlet)` 

### ISSUE THREAD

**Issue by ninmonkey** [PowerShell/PowerShellEditorServices#1959]
- [edit-services-ClrCallStack.log](https://github.com/PowerShell/PowerShellEditorServices/files/10048162/edit-services-ClrCallStack.log)
- [editor-services-log.page1.md](https://github.com/PowerShell/PowerShellEditorServices/files/10048163/editor-services-log.page1.md)

### Theorized Causes?

It seems to always be about a cancellation, and the UI was flickering back and forth.
Could the new **quick fix** feature be fighting for control with the PSES?

### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Refactor is crashing.

As far as I can tell I can't get more exception information (using powershell)

### Location of the exception:
`Documents\PowerShell\Modules\EditorServicesCommandSuite\1.0.0\EditorServicesCommandSuite.psm1`
```ps1
$null = $CommandSuite.RequestRefactor($PSCmdlet).
    ConfigureAwait($true).
    GetAwaiter().
    GetResult()
```

### single exception 

using a key with nothing bound to it other than this

```json
   {        
        "key": "ctrl+k",
        "when": "editorLangId == 'powershell'",
        "command": "PowerShell.InvokeRegisteredEditorCommand",
        "args": {
            "commandName": "Invoke-DocumentRefactor"
        },
    },
    {
        "key": "ctrl+shift+s",
        "command": "PowerShell.InvokeRegisteredEditorCommand",
        "args": {
            "commandName": "ConvertTo-SplatExpression"
        },
        "when": "editorLangId == 'powershell'"
    },
```

to reproduce
```ps1
import-module EditorServicesCommandSuite -Force
Import-CommandSuite
```

- hit `ctrl+shift+s` to splat something ... it works
- hit `ctrl+k` to refactor something ... exception

### Expected behavior

```console
Show the refactor menu
```

### Actual behavior

```console
The SplatExpression hotkey works
The Refactor one throws.
```

### Error details

- [editor-services-log.page1.md](https://github.com/PowerShell/PowerShellEditorServices/files/10048163/editor-services-log.page1.md)

### Environment data

```ps1
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```ps1
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.0.0      beta4      EditorServicesCommandSuite          {Get-CommandSuiteSetting, New-CommandSuiteSettingF…
Script     0.2.0                 PowerShellEditorServices.Commands   {Clear-Host, ConvertFrom-ScriptExtent, ConvertTo-S…
Binary     0.2.0                 PowerShellEditorServices.VSCode     {Close-VSCodeHtmlContentView, New-VSCodeHtmlConten…
```

### Version

ms-vscode.powershell@2022.11.0

### Visuals

![image](https://user-images.githubusercontent.com/3892031/202876209-092cc3c5-e87f-40af-ac69-33c4b46c9556.png)

**Comment by SeeminglyScience** [comment]
Thanks Jake! Lookin' into it

**Comment by SeeminglyScience** [comment]
Non-ESCS repro:

```powershell
$eoeType = [Microsoft.PowerShell.EditorServices.Extensions.EditorObjectExtensions, Microsoft.PowerShell.EditorServices]
$pcdType = [Microsoft.PowerShell.EditorServices.Extensions.Services.PromptChoiceDetails, Microsoft.PowerShell.EditorServices]

$task = $eoeType::GetExtensionServiceProvider($psEditor).EditorUI.PromptSelectionAsync(
    'Example message',
    @(
        $pcdType::new('Label 1', 'Greyed out bit I think'),
        $pcdType::new('Label 2', 'woooot')
    ) -as $pcdType.MakeArrayType())

while (-not $task.AsyncWaitHandle.WaitOne(200)) { }
$result = $task.GetAwaiter().GetResult()
$result
```

**Comment by SeeminglyScience** [comment]
Nah nothing like that, it's just the `ShowChoicePromptAsync` public API that is broken. Still workin' on it.
