### ISSUE TITLE
SuppressMessageAttribute not working correctly in VSCode but works under raw Invoke-ScriptAnalyer

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#201]
Here's the modified code in `Examples\DebugTest.ps1`:
```powershell
function Write-Item {
    [Diagnostics.CodeAnalysis.SuppressMessage("PSProvideDefaultParameterValue")]
    param(
        [Parameter()]
        $itemCount
    )

    $i = 1

    while ($i -le $itemCount) {
        $str = "Output $i"
        Write-Output $str
        # In the gutter on the left, right click and select "Add Conditional Breakpoint"
        # on the next line. Use the condition: $i -eq 25
        $i = $i + 1

        # Small delay to allow you to test the Debug pause feature
        Start-Sleep -Milliseconds 200
    }
}

function Do-Work($workCount) {
    Write-Output "Doing work..."

    Write-Item $workcount

    Write-Host "Done!"
}

Do-Work 50
```

When I run this in VSCode debugger, I get:

![a](https://cloud.githubusercontent.com/assets/5177512/14120160/d24d4ea6-f5ae-11e5-9f5c-fe797857dfa7.png)

If I drop to the command line and run `Invoke-ScriptAnalyzer DebugTest.ps1` - I get no errors e.g.:
```
10> Invoke-ScriptAnalyzer .\DebugTest.ps1

RuleName                            Severity     FileName   Line  Message
--------                            --------     --------   ----  -------
PSUseApprovedVerbs                  Warning      DebugTest. 20    The cmdlet 'Do-Work' uses an unapproved verb.
                                                 ps1
PSAvoidUsingWriteHost               Warning      DebugTest. 23    File 'DebugTest.ps1' uses Write-Host. Avoid using
                                                 ps1              Write-Host because it might not work in all hosts,
                                                                  does not work when there is no host, and (prior to
                                                                  PS 5.0) cannot be suppressed, captured, or
                                                                  redirected. Instead, use Write-Output,
                                                                  Write-Verbose, or Write-Information.
```

So this appears to be an issue with the extension and *not* PSScriptAnalyzer. @joeyaiello

**Comment by daviwil** [comment]
I get the same error when running the script in the ISE.  The problem with this code is that SuppressMessageAttribute takes two required parameters to its [constructor](https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.suppressmessageattribute.suppressmessageattribute(v=vs.110).aspx):

```csharp
public SuppressMessageAttribute(
	string category,
	string checkId
)
```

Script Analyzer isn't actually invoking the script so I suppose it works there because they're just scanning the AST for that attribute?  I don't think we have a bug in this case.

**Comment by rkeithhill** [comment]
OK I see what's going on.  I was told they interpret the attribute specially by looking at the AST like you say.  But that doesn't account for the fact that these scripts need to run outside the Invoke-ScriptAnalyzer command.

**Comment by rkeithhill** [comment]
This is really an issue with the PSScriptAnalyzer. I submitted an issue there. See https://github.com/PowerShell/PSScriptAnalyzer/issues/499
