### ISSUE TITLE
Only Snippets in intellisense (no modules)

### ISSUE THREAD

**Issue by scottmckendry** [PowerShell/PowerShellEditorServices#2048]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Using PowerShell Editor Services in neovim with the following LSPConfig:

```lua
local bundle_path = vim.fn.stdpath("data") .. "/mason/packages/powershell-editor-services"
local command_fmt = [[& '%s/PowerShellEditorServices/Start-EditorServices.ps1' -BundledModulesPath '%s' -LogPath '%s/powershell_es.log' -SessionDetailsPath '%s/powershell_es.session.json' -FeatureFlags @() -AdditionalModules @() -HostName nvim -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal]]
local temp_path = vim.fn.stdpath("cache")
local command = command_fmt:format(bundle_path, bundle_path, temp_path, temp_path)
lspconfig.powershell_es.setup {
  on_attach = on_attach,
  capabilities = capabilities,
  filetypes = { "ps1" },
  bundle_path = vim.fn.stdpath("data") .. "/mason/packages/powershell-editor-services",
  cmd = { "pwsh", "-NoLogo", "-Command", command },
}
```
As part of troubleshooting, I set the cmd to include my profile which had this line:

```powershell
Get-Module -ListAvailable | Import-Module
```

However, still no modules in Intellisense.

### Expected behavior

```console
Typing `Get-C` in a ps1 buffer should display Get-ChildItem in autocomplete
```

### Actual behavior

```console
Type `Get-C` in a ps1 buffer only shows snippets
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

3.8.7 - [Mason Registry](https://github.com/mason-org/mason-registry/blob/main/packages/powershell-editor-services/package.yaml)

### Visuals

Example of missing IntelliSense 
![image](https://github.com/PowerShell/PowerShellEditorServices/assets/39483124/67a9f597-6757-4d65-873c-db681632b19b)

Output of :LspInfo
![image](https://github.com/PowerShell/PowerShellEditorServices/assets/39483124/c857bfd3-2ee6-4d90-9c3c-19c0ef1ab98e)

**Comment by andyleejordan** [comment]
How are you setting up "IntelliSense" aka completion requests in NeoVim? The only "snippets" that should exist in the realm of using just PSES are from PSSA, which comment-help is, so at least the analysis service (PSSA) is working.

**Comment by scottmckendry** [comment]
I'm using [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) for code completion. With the default capabilities that come with NVChad [here](https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/lspconfig.lua).

**Comment by andyleejordan** [comment]
I think you need to set it up then...from the `lspconfig` readme:

> Manual, triggered completion is provided by Nvim's builtin omnifunc. For autocompletion, a general purpose [autocompletion plugin](https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion) is required.

For `nvimp-cmp` it looks like it must be explicitly setup to use LSP completions, the readme has an example:

```
sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'vsnip' }, -- For vsnip users.
      -- { name = 'luasnip' }, -- For luasnip users.
      -- { name = 'ultisnips' }, -- For ultisnips users.
      -- { name = 'snippy' }, -- For snippy users.
    }
```

**Comment by andyleejordan** [comment]
My best guess...the default configuration you're loading from https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/powershell_es.lua probably needs to be revised to advertise completion capabilities, I sort of found an example of that in https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/clangd.lua.

**Comment by scottmckendry** [comment]
That's what I'm doing in my config (I think). I pull in the default capabilities from the NVChad lsp config with this line:

```lua
local capabilities = require("plugins.configs.lspconfig").capabilities
```
Which should look something like this:

```lua
M.capabilities = vim.lsp.protocol.make_client_capabilities()

M.capabilities.textDocument.completion.completionItem = {
  documentationFormat = { "markdown", "plaintext" },
  snippetSupport = true,
  preselectSupport = true,
  insertReplaceSupport = true,
  labelDetailsSupport = true,
  deprecatedSupport = true,
  commitCharactersSupport = true,
  tagSupport = { valueSet = { 1 } },
  resolveSupport = {
    properties = {
      "documentation",
      "detail",
      "additionalTextEdits",
    },
  },
}
```
I've had success with this method using [go](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/gopls.lua) and [bicep](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/bicep.lua) LSPs but PowerShell eludes me...

**Comment by andyleejordan** [comment]
I think you're missing this part:

```
completionItemKind?: {
		/**
		 * The completion item kind values the client supports. When this
		 * property exists the client also guarantees that it will
		 * handle values outside its set gracefully and falls back
		 * to a default value when unknown.
		 *
		 * If this property is not present the client only supports
		 * the completion items kinds from `Text` to `Reference` as defined in
		 * the initial version of the protocol.
		 */
		valueSet?: [CompletionItemKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemKind)[];
	};
```

**Comment by scottmckendry** [comment]
Thanks, unfortunately, no luck getting this going on my end. I've also raised this as an issue on the nvim-lsp repo:
https://github.com/neovim/nvim-lspconfig/issues/2747

I did come across a log file generated by PSES with this line:
```log
2023-08-05 21:35:20.494 +12:00 [WRN] Tried to send request or notification before initialization was completed and will be sent later {"Id":1,"Error":{"Code":-32800,"Data":null,"Message":"Request Cancelled","$type":"ErrorMessage"},"Method":"initialize","$type":"RequestCancelled"}
```

Not sure if this helps at all.

**Comment by andyleejordan** [comment]
Hm, the thing that reminds me of is https://github.com/OmniSharp/csharp-language-server-protocol/issues/588

That was a bug in our LSP library because the spec is very confusing about the ordering of the initialize and initialized requests. Might be worth looking into for nvim-lspconfig, but could also be a red herring.

**Comment by ogios** [comment]
same issue, any updates?

**Comment by scottmckendry** [comment]
> same issue, any updates?

No progress on Windows 11. However, PSES on Linux is working. Tested in Ubuntu 22.04 (WSL) and Arch running essentially identical neovim configurations. 

The language server starts on Windows, but doesn't attach to the active buffer. Every other LSP-compatible language I've tried on Windows works fine, but PSES does not. 

I also tried turning on verbose logging to see if I could see anything that might be useful. No errors or warnings. Also I'm no longer able to replicate the error in my previous comment. Seems like to LSP implementation just isn't Windows-friendly.

**Comment by andyleejordan** [comment]
Hm, are there over LSP plugins for Vim that could be tried?

**Comment by scottmckendry** [comment]
I can confirm that [coc-powershell](https://github.com/coc-extensions/coc-powershell) works on Windows. But it's not as good as the native nvim lsp.

I'm not the first person to run into [this issue](https://github.com/neovim/nvim-lspconfig/issues/2465#issuecomment-1678168102). 

[Another example](https://neovim.discourse.group/t/help-with-powershell-es/2176/2)

**Comment by scottmckendry** [comment]
@andyleejordan @ogios I've opened a [new issue](https://github.com/neovim/nvim-lspconfig/issues/2810) in the nvim-lspconfig repo. If you have anything you can add that the maintainers might find helpful that would be appreciated 👍🏻
