### ISSUE TITLE
FYI you can disable this feature with:

### ISSUE THREAD

**Issue by TheOriginalPiff** [PowerShell/PowerShellEditorServices#2056]
FYI you can disable this feature with:
```powershell
Import-Module posh-git
$global:GitPromptSettings.WindowTitle = $null
```

_Originally posted by @rkeithhill in https://github.com/PowerShell/PowerShell/issues/19515#issuecomment-1514135087_

**Comment by andyleejordan** [comment]
I don't think you meant to open this here?
