### ISSUE TITLE
Getting a completion item on ::MethodName

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#208]
Now that we have completion items working on static methods, I noticed this incorrect completion item/suggestion:

![vscode_badcompletion](https://cloud.githubusercontent.com/assets/5177512/14359580/6286e390-fcaf-11e5-96fb-8549fe165e4a.png)

I suspect this has something to do with what VSCode thinks is a language word based on the regex/tm file??

**Comment by daviwil** [comment]
Hmm...  Are we actually returning the `::` in the label?  I wouldn't think so, so maybe they're adding that?  Would be a little strange...

**Comment by daviwil** [comment]
Briefly looked into this, looks like VS Code is giving a bogus completion because we aren't returning any completion results at this point...  Not sure how to disable that.

**Comment by rkeithhill** [comment]
Ah, so VSCode is falling back to "dumb" auto-completion mode.  It would be nice if there were a way to tell VSCode not to do that when the language service has told it there aren't any valid completions based on what the user is trying to complete.  Oh well, that's probably not going to happen.  Go ahead and close this.

**Comment by tylerl0706** [comment]
This is still an issue, unfortunately. Should we open an issue on VSCode or just close this, you think?

**Comment by rkeithhill** [comment]
I don't there is anything we can do about this, so I'm closing it.
