### ISSUE TITLE
Debugger doesn't resume after pausing debug

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#211]
Take the shipping 0.5.0 bits and open the Examples folder and select DebugTest.ps1.  Run the debugger and press the debug pause button after a second of two of seeing output.  On my machine the pause button doesn't change back to run and pressing it doesn't start the script running again.  I see the same behavior on the daily bits of the extension & vscode.

**Comment by rkeithhill** [comment]
OK this is weird.  I have two different machines with what I believe are clean VSCode 0.10.11 bits and PSES 0.5.0 bits (no dev bits).  On my machine at work (the most likely to be "clean"), the behavior is as described above.  At home, I can pause and resume but if I change DebugTest.ps1 line 21 to `Do-Work 50000` and then execute, pause and resume I get the "error cancelled" popup after the program finishes.  Both behaviors lead me to believe there might be something wrong with how we pause or resume.

**Comment by rkeithhill** [comment]
On today's alpha build, I still notice that `Error Canceled` popup after a debug session where I have paused the debugger and resumed.  The last part of the debug log doesn't seem quite right:
```
    Execution completed, terminating...

4/30/2016 5:42:38 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "terminated",
      "body": null
    }

4/30/2016 5:42:38 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "output",
      "body": {
        "category": "stdout",
        "output": "Done!\n\r\nPS C:\\Users\\Keith\\.vscode-alpha\\extensions\\ms-vscode.PowerShell-0.5.0\\examples\r\n"
      }
    }

4/30/2016 5:42:38 PM [NORMAL] - Method "Shutdown" at line 96 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Debug adapter is shutting down...

4/30/2016 5:42:38 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 12,
      "command": "disconnect",
      "arguments": {
        "restart": false
      }
    }

4/30/2016 5:42:38 PM [VERBOSE] - Method "AbortExecution" at line 542 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\Session\PowerShellContext.cs

    Execution abort requested...

4/30/2016 5:42:38 PM [NORMAL] - Method "Main" at line 170 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host exited normally.
```

First we tell the client we are terminating before all the output is flushed out.  Then we get the request to `disconnect` after we have already started to shutdown.  That said, the only difference I see in a working run (no pause, just run to completion) is the `Execution abort requested...` line above isn't in the "no error" log below:
```
    Execution completed, terminating...

4/30/2016 5:47:56 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "terminated",
      "body": null
    }

4/30/2016 5:47:56 PM [VERBOSE] - Method "WriteMessage" at line 58 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs

    WRITE MESSAGE:
    
    {
      "type": "event",
      "event": "output",
      "body": {
        "category": "stdout",
        "output": "Done!\n\r\nPS C:\\Users\\Keith\\.vscode-alpha\\extensions\\ms-vscode.PowerShell-0.5.0\\examples\r\n"
      }
    }

4/30/2016 5:47:56 PM [NORMAL] - Method "Shutdown" at line 96 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\Server\DebugAdapter.cs

    Debug adapter is shutting down...

4/30/2016 5:47:56 PM [VERBOSE] - Method "ReadMessage" at line 111 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs

    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 6,
      "command": "disconnect",
      "arguments": {
        "restart": false
      }
    }

4/30/2016 5:47:56 PM [NORMAL] - Method "Main" at line 170 of C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices.Host\Program.cs

    PowerShell Editor Services Host exited normally.
```

**Comment by daviwil** [comment]
That's pretty wacky.  Seems like partially a message ordering bug on their side?  The debug adapter shutdown logic is a little messy (my fault) and needs to be improved.  I need to get back to the work I was referring to in this issue: https://github.com/PowerShell/PowerShellEditorServices/issues/110

**Comment by daviwil** [comment]
Just tried to repro this, I'm able to resume from the debugger just fine in 1.1.0 with the latest PSES repo bits.  However, I do get the `Canceled` error when the debugger stops, either from stopping it manually or letting execution complete.  Can you try this with 1.1.0 and see if you have trouble resuming?  We might be able to punt this to the next release.

**Comment by rkeithhill** [comment]
I can't repro this at home. I'll try again when I get into work on my work machine.

**Comment by daviwil** [comment]
I wonder if this issue is gone now?

**Comment by rkeithhill** [comment]
I can't repro it on my work machine with 0.7.1 installed.  I'm going to close this.  If I see it again, I'll open a new issue.
