### ISSUE TITLE
Shipped binaries should be strong-named

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellEditorServices#212]
I need this for VSIX support in PoshTools. Maybe have a SN version of the NuGet package?

**Comment by daviwil** [comment]
I'll just strong-name the assemblies for the 0.6.0 release forward.  You looking at integrating again?

**Comment by adamdriscoll** [comment]
That would be awesome. Was starting to look at it again, yeah.

**Comment by adamdriscoll** [comment]
Also, FYI. 

![image](https://cloud.githubusercontent.com/assets/1256531/14831603/10c1425a-0bbc-11e6-9aa0-ac84f44c18e3.png)

**Comment by daviwil** [comment]
Hmm, are you using 0.5.0 (or synced to latest master)?  I added some code in that release to make Script Analyzer optional so it shouldn't crash if that assembly isn't found.

**Comment by adamdriscoll** [comment]
I added the NuGet Packages.

![image](https://cloud.githubusercontent.com/assets/1256531/14832315/3fd89540-0bbf-11e6-9793-7876c79d23d6.png)

![image](https://cloud.githubusercontent.com/assets/1256531/14832319/4bba6532-0bbf-11e6-962c-5d11f04fbe4a.png)

**Comment by adamdriscoll** [comment]
You can probably disregard this crash. I bet it's how I signed the binaries that is causing the issue.

**Comment by daviwil** [comment]
Ahhh!  Yes, that's definitely the issue.  I was using a similar auto-strong naming tool when pulling PSES dev binaries into the ISE Preview and had the same problem.

**Comment by daviwil** [comment]
Bah, I'm going to have to do this for the next release.  I need to set up delay signing on the assemblies to make this work and I don't have time at the moment to get that going.  I'm planning to release another update soon once the new PSScriptAnalyzer release drops so I can get everything strong-named then.  Is that OK?

**Comment by adamdriscoll** [comment]
Yeah. That's ok!

**Comment by tylerl0706** [comment]
Spoke to @daviwil offline about this. I don't think we have a need for this right now but if you see otherwise, let me know and we can absolutely reconsider!
