### ISSUE TITLE
Start-EditorServices.ps1 terminates on first request when started from Emacs (eglot)

### ISSUE THREAD

**Issue by macmacy** [PowerShell/PowerShellEditorServices#2142]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/PowerShellEditorServices/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with _PowerShell Editor Services itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance, and is not an issue with my editor.
- [X] I have verified that I am using the latest version of PowerShell Editor Services.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I use Emacs+eglot with other language servers: OmniSharp, pyright, clangd, but cannot make it work with PowerShellEditorServices. The services command starts but exists after a while. Last message in log is `Could not write to output handler, perhaps serialization failed?`.

### PowerShell Version

```console
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Editor Version

```console
GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-08-02
```

### PowerShell Editor Services Version

```console
3.17.0 (latest)
```

### Steps to Reproduce

I have PSES configured in  .emacs like that:

```
(add-to-list
 'eglot-server-programs
 `(powershell-mode
       . ("pwsh" "-NoLogo" "-NoProfile" "-Command" , "c:/bin/PowerShellEditorServices/PowerShellEditorServices/Start-EditorServices.ps1"
          "-HostName" "Emacs" "-HostProfileId" "Emacs" "-HostVersion" "1.0.0"
          "-BundledModulesPath", "c:/bin/PowerShellEditorServices"
          "-LogPath" ,"c:/users/mmaczynski/AppData/Roaming/.pses-session/logs.log" "-LogLevel" "Diagnostic"
          "-SessionDetailsPath" ,"c:/users/mmaczynski/AppData/Roaming/.pses-session/session.json"
          "-Stdio")))

(add-hook 'powershell-mode 'eglot-ensure)
```

When I load .ps1 file, or execute ` M-x eglot` when in powershell-mode, the Start-EditorServices is started but exists after a while, logging the following in session log file:

```
2024-02-28 14:18:59.973 +01:00 [VRB] Could not write to output handler, perhaps serialization failed?
System.Threading.Channels.ChannelClosedException: The channel has been closed.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at OmniSharp.Extensions.JsonRpc.OutputHandler.ProcessOutputStream(CancellationToken cancellationToken)
```

I guess the server process exits on my first attempt to edit a file e.g. starting to type "Get-" or executing `M-x eglot-rename`

### Logs

log files from PSES session directory:
[logs.log](https://github.com/PowerShell/PowerShellEditorServices/files/14435118/logs.log)
[StartEditorServices.log](https://github.com/PowerShell/PowerShellEditorServices/files/14435126/StartEditorServices.log)

The content of Emacs eglot events buffer:
[eglotlog.txt](https://github.com/PowerShell/PowerShellEditorServices/files/14435139/eglotlog.txt)

**Comment by andyleejordan** [comment]
FWIW I'm trying to simplify this setup for you: https://github.com/PowerShell/PowerShellEditorServices/pull/2129 but I need to get back to this PR.

**Comment by macmacy** [comment]
Thank you for your fast response. Your suggestion was correct: after changing `-BundledModulesPath` it started to work. Awesome! Thank you very much. However, the problem is probably not only my misconfiguration. Initially I used PSES zipped release binaries, not repository. The directory structure was like that (release ZIP unpacked):

```
C:\BIN\POWERSHELLEDITORSERVICES
├───docs
├───Plaster
├───PowerShellEditorServices
├───PSReadLine
├───PSScriptAnalyzer
└───_manifest

```
This is why I set up bundled modules path to `c:/bin/powershelleditorservices` - this is where modules seems to be, and there is no modules subdir here.  And this **does not work**. However, when I built from sources, my directory structure is like that:

```
C:\BIN\POWERSHELLEDITORSERVICES
├───.github
├───.vsts-ci
├───docs
├───module
│   ├───docs
│   ├───Plaster
│   ├───PowerShellEditorServices
│   ├───PSReadLine
│   └───PSScriptAnalyzer
├───src 
└───tools
```

With such structure and setting `-BundledModulesPath` to `"c:/bin/PowerShellEditorServices/module"` - **it works**.
Which seems a bit strange to me, as the structure under C:\BIN\POWERSHELLEDITORSERVICES in first case looks same as under 
C:\BIN\POWERSHELLEDITORSERVICES\modules in second case. However - something makes difference here.
Anyway - with project built from sources and parameters set up as in emacs-test.el - it works fine. 
Thanks once again!

**Comment by andyleejordan** [comment]
Well...that's strange. I'll take a look.

**Comment by andyleejordan** [comment]
Well this encouraged me to get back to https://github.com/PowerShell/PowerShellEditorServices/pull/2129; when we get this released would you test it out for us?

**Comment by macmacy** [comment]
Absolutely - just drop me a note here.

**Comment by andyleejordan** [comment]
@macmacy it's out if you want to give it a try! https://github.com/PowerShell/PowerShellEditorServices/releases/tag/v3.18.0

**Comment by macmacy** [comment]
I was trying to test it with v3.18.0, but it looks like PS files were signed in different way and current certificate is not accepted on my system. It was **not** the issue with previous release. This is how it looks like now:

```
PS C:\bin\_PowerShellEditorServices> Get-AuthenticodeSignature  .\PowerShellEditorServices\Start-EditorServices.ps1|fl

SignerCertificate      : [Subject]
                           CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           33000003AE2D3551C8538F551D0000000003AE

                         [Not Before]
                           16.11.2023 20:08:59

                         [Not After]
                           14.11.2024 20:08:59

                         [Thumbprint]
                           F9A7CF9FBE13BAC767F4781061332DA6E8B4E0EE

TimeStamperCertificate : [Subject]
                           CN=Microsoft Time-Stamp Service, OU=nShield TSS ESN:9600-05E0-D947, OU=Microsoft America Operations, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Time-Stamp PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           33000001EF893F56A158CCA8DA0001000001EF

                         [Not Before]
                           06.12.2023 19:45:48

                         [Not After]
                           05.03.2025 19:45:48

                         [Thumbprint]
                           4B708F358316DE6B5131DA615B5F1EDC93ED20FF

Status                 : NotTrusted
StatusMessage          : File C:\bin\_PowerShellEditorServices\PowerShellEditorServices\Start-EditorServices.ps1 is signed but the signer is not trusted on this system.
Path                   : C:\bin\_PowerShellEditorServices\PowerShellEditorServices\Start-EditorServices.ps1
SignatureType          : Authenticode
IsOSBinary             : False
```

At explorer, it looks like that:
![bad-cert](https://github.com/PowerShell/PowerShellEditorServices/assets/1330373/38613da4-2206-473c-b2e4-0a6bcf31ac9d)

seems that there is something wrong with this certificate indeed.

**Comment by andyleejordan** [comment]
Hm, I'm going to suggest redownloading to ensure the integrity of the bits, and check your system time? Did you download this exact asset https://github.com/PowerShell/PowerShellEditorServices/releases/download/v3.18.0/PowerShellEditorServices.zip? I just downloaded the release form GitHub and inspected the certificate, it looks correct and not revoked:

![image](https://github.com/PowerShell/PowerShellEditorServices/assets/2226434/29501246-e0b9-4416-b539-c24a92d132f1)

**Comment by andyleejordan** [comment]
Here's the SHA256 sum:
```
> certutil -hashfile "~\Downloads\PowerShellEditorServices.zip" sha256
SHA256 hash of ~\Downloads\PowerShellEditorServices.zip:
b5624eeae84e4a23e1ef2b9516d29a9e0df02640470987a9f95757c05faee926
CertUtil: -hashfile command completed successfully.
```

**Comment by andyleejordan** [comment]
Awesome! Just FYI with the simplification, I think you can _just_ run this code now to setup (note the removal of most of the silly unnecessary arguments:

```elisp
(add-to-list
 'eglot-server-programs
 `(powershell-mode
       . ("pwsh" "-NoLogo" "-NoProfile" "-Command" , 
          "c:/bin/PowerShellEditorServices/PowerShellEditorServices/Start-EditorServices.ps1"
          "-LogPath" ,"c:/users/mysername/AppData/Roaming/.pses-session/logs.log" "-LogLevel" "Diagnostic"
          "-SessionDetailsPath" ,"c:/users/myusername/AppData/Roaming/.pses-session/session.json"
          "-Stdio")))
```
