### ISSUE TITLE
Timing issue in LanguageServer initialization

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#221]
After updating it appears PowerShellEditorServices is not properly starting.

I am getting the following error.

"No Handler found for the command: 'PowerShell.RunSelection'. An etension might be missing an activation event."

Tried restarts and a reboot. Will try reinstalling the extension next.

**Comment by gerane** [comment]
hmm, still present after a reinstall.

**Comment by rkeithhill** [comment]
I can't repro this.  Are you on VSCode 1.1.0 or an Insider's or Alpha build of VSCode?

**Comment by daviwil** [comment]
I think he told me on Twitter that he's using the Insider build.  Usually I see this error when PSES crashes at startup but it started up fine for him when he launched it directly.  Might be something wonky with the extension code.

**Comment by gerane** [comment]
The Editor Services is actually running, but f8 is totally broken. Intellisense is working, but f8 gives that error. I just updated my main desktop and seeing the same issue.

**Comment by gerane** [comment]
I'm on 1.1.0 insider

**Comment by gerane** [comment]
I restarted my desktop and it started working, but i've restarted my laptop VM a few times and still seeing the issue. I will see what I can figure out.

**Comment by gerane** [comment]
Here is what I am seeing in the console

```
workbench.main.js:117 Cannot read property 'getActiveEditor' of undefined: TypeError: Cannot read property 'getActiveEditor' of undefined
    at t.getActiveEditorInput (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:101:19916)
    at e.getActiveEditorInput (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:94:11666)
    at t.getFilePath (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:82:9120)
    at t.Object.defineProperty.get [as file] (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:82:8609)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:23:4134
    at String.replace (native)
    at t.e.__resolveString (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:23:4103)
    at t.e.resolveAny (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:23:3923)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:103:7306
    at Array.forEach (native)e.onUnexpectedError @ workbench.main.js:117
workbench.main.js:31 WARNING: Promise with no error callback:2
```

**Comment by gerane** [comment]
Here is one thing i've noticed. On my desktop, when it wasn't working I placed $psEditor in a script and ran it in the debugger. It was null. The same happens right now on my laptop that f8 is broken on. 

Now that my desktop is working, $psEditor properly returns an object.

**Comment by daviwil** [comment]
Huh...  Interesting.  I wonder if they changed the API?  Have you tried in non-Insider VS Code on your VM?

**Comment by gerane** [comment]
Well, I think something is hanging. If I reload the editor on my desktop, and execute f8 right as it comes back up, I get that error. If I wait a couple seconds and then try it again, it works. It makes me think the editor services are not fully loading or getting partially hung up or something. 

I will go download the Normal one and give that a try after lunch.

**Comment by daviwil** [comment]
Yeah, it takes a couple seconds before PSES is fully initialized.  Maybe on your VM it just takes a bit longer and it eventually works?

**Comment by gerane** [comment]
Nope, never loads.

I just finished installing the non-insider version and it is working in it. I will use it on my laptop for the time being until this get figured out. Let me know if there are any sort of tests or things you'd like me to try.

**Comment by daviwil** [comment]
OK maybe the Insider build has broken it somehow, I'll take a look there.

**Comment by gerane** [comment]
Well, it eventually started working on my Desktop with Insider. I am not sure what it was that made it start working on my Desktop though.

**Comment by lucdekens** [comment]
For the record, I'm on Windows 10 build 10586, no insider build, and I experienced this as well.
After a couple of restarts, it started working again.
Anything I can do when it happens to help analyse the issue?

**Comment by daviwil** [comment]
I've got a pretty clear picture of what's happening now.  There appears to be a timing issue that's causing the language server's initialization to not complete.  This causes the error you see and the subsequent lack of IntelliSense.  Will get an update shipped this week to resolve this issue.

Related bug: https://github.com/PowerShell/vscode-powershell/issues/183

**Comment by gpuido** [comment]
Same here, if I open a folder with about a 100 files, the service is rarely available. 
But if I run vscode on just a file it's always available.
the profile.ps1 is never executed so It's easy to check availability with a Write-Host "Profile loaded" in it.

**Comment by daviwil** [comment]
Interesting...  The number of files in the folder shouldn't have a direct impact on the initial loading sequence.  I might need to see if there's something happening there that I didn't expect.

**Comment by gpuido** [comment]
Also, if the git diff markers (red & green lines next to the line numbers column) appear then the profile is never loaded.

**Comment by gpuido** [comment]
I mean, if the git diff markers shows before the profile is loaded then it never will.

**Comment by selfvoid** [comment]
Guys, any workaround?

**Comment by daviwil** [comment]
There isn't one unfortunately since it's caused by how long the language server startup takes.  I'll have a fix out in a day or two.

**Comment by daviwil** [comment]
Fix was pretty simple.  I'll see if I can get the update out today!

**Comment by daviwil** [comment]
Just shipped the 0.6.1 update, let me know if things are working right for you now!

**Comment by selfvoid** [comment]
Works now! Brilliant! Many thanks!

**Comment by daviwil** [comment]
Glad to hear it!

**Comment by KushGoswami** [comment]
Hello, I am having same issue with VS Code, I am on VS code version 1.1.1 and I am using Windows 7 and Power shell version 2.0 , Is it not supported on Win 7 with PS 2.0 ??

**Comment by rkeithhill** [comment]
The extension supports PowerShell v3 and higher.  V2 is not supported.  [V5 is available](https://www.microsoft.com/en-us/download/details.aspx?id=50395) for Windows 7. I'd recommend that if you can update.  Where I work we updated all our Windows 7 machines to at least V4.
