### ISSUE TITLE
Editor Commands are not receiving $host.ui.PromptForChoice output

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#222]
https://gist.github.com/gerane/1925324d7ea7e3c767eb45abcde91e8b

The above is an example. The output shows the prompt times out and never gets the selection selected by the user. It works when running via f8.

David said he was able to reproduce.

**Comment by daviwil** [comment]
Yep, will be looking into this.  Something is causing the choice result to not be received when PromptForChoice is run inside of an editor command.

**Comment by daviwil** [comment]
Done ;)

**Comment by gerane** [comment]
Sweet. When is the next update getting pushed out?

**Comment by daviwil** [comment]
Trying to make it happen, waiting on binary signing to be approved...  If not today then tomorrow morning

**Comment by gerane** [comment]
Sweet!

**Comment by daviwil** [comment]
Shipped!

**Comment by gerane** [comment]
You are the man. Irwin has competition.

**Comment by daviwil** [comment]
Haha, I don't know that I can compete on his level
