### ISSUE TITLE
Visual indicator for language server initialization status

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/PowerShellEditorServices#227]
When many modules and PSSnapins are loaded, it might take some time before Intellisense is ready.
It would be handy if there would be an indication of the status of Intellisense (working, ready...)

**Comment by daviwil** [comment]
Yeah, that's a good idea.  I've considered having some messages that appear if initialization takes longer than some short amount of time (> 750ms ?) just to let the user know that loading is still in progress.

**Comment by lucdekens** [comment]
That would work as well, a message in a status field that initialisation is still "working"

**Comment by daviwil** [comment]
I am reluctant to add important status info as status bar text in VS Code because I find that it's harder to notice the text change there than in the ISE.  I think the colors of the status bar make it harder to notice changes.

**Comment by daviwil** [comment]
I guess it could be enough if the user knew where to look, though!

**Comment by lucdekens** [comment]
There aren't many options available that I could think off.
But in the end, any indicator, wherever, would work for me.

**Comment by daviwil** [comment]
VS Code has some nice unintrusive popup message UI that would work well for this I think.  The trick would be to only show them if initialization is taking a little longer than expected.  I'll give that a try and if it turns out to be annoying I'll try changing the status bar text.

**Comment by gerane** [comment]
Do any other languages function similar to the PowerShellEditorServices? If so, how do they handle this sort of behavior?

**Comment by tylerl0706** [comment]
@daviwil we have this visual indicator in the status bar now:
![image](https://user-images.githubusercontent.com/2644648/33848136-b2b5f5a0-de61-11e7-8198-0bfc28f25f1a.png)

Is that enough of an indicator that PSES is starting up or is that separate?

**Comment by tylerl0706** [comment]
Gonna close this since we have that indication :) if you see otherwise, please file a new issue!
