### ISSUE TITLE
Improve region collapse

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/PowerShellEditorServices#228]
Some limited region collapse is available, but it seems to be missing for functions, help blocks...

**Comment by daviwil** [comment]
Yep, this is a problem with VS Code's code folding feature.  We're tracking this at the VS Code extension repo here:

https://github.com/PowerShell/vscode-powershell/issues/177

I'll close this issue since it's specific to VS Code.  I'd recommend subscribing to the other!
