### ISSUE TITLE
VS Code debugger client disconnects if any output is written to stdout

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#233]
An example:

``` powershell
Start-Process -NoNewWindow -Passthru -Wait
```

Start-Process will start writing to StdOut and will cause the debugger to Error and stop. Code will show an error similar to:

```
Unexpected token L. Stopping the debug adapter.
```

**Comment by daviwil** [comment]
Thanks Brandon!  Basically the problem here is that anything written to stdout will interfere with the communication between VS Code and the PowerShell debug server.  I'm currently switching to a named pipes communication channel instead so this issue should be resolved in the future.

**Comment by rjmholt** [comment]
@tylerl0706 this looks like it should be easy to fix now

**Comment by tylerl0706** [comment]
This was probably fixed when we added the integrated console. I'm just gonna close it. If anyone still sees this issue, please open a new issue!
