### ISSUE TITLE
Set current directory to workspace path when EditorSession is created

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#237]
Currently when a workspace is opened in VS Code the working directory of the PowerShell session is `c:\Program Files (x86)\Microsoft VS Code`.  We should set the current directory to the workspace path so that executed commands will be relative to the expected path.

**Comment by lucdekens** [comment]
That would be a good default.

But could we also have a settings.json entry if we want to point to another folder ?
For example, when I'm writing scripts to produce reports, I prefer the resulting reports in a dedicated folder, not between my script folders.

**Comment by daviwil** [comment]
Great idea!  What should the setting be called for that?  Ideas:

- `initialSessionPath`/`Directory`
- `initialWorkingPath`/`Directory`

**Comment by lucdekens** [comment]
InitialWorkingDirectory sounds good, but I can live with either of these.

**Comment by rkeithhill** [comment]
@daviwil Could this be an extension setting like `powershell.developer.editorServicesInitialWorkingDirectory` that defaults to workspaceRoot?  Or should we just slam it and not make it configurable?  Not really sure if it would be useful to set to something else.  

This could also be something somebody could change via their VSCode_profile.  You'd need to decide whether to set this before or after profile processing - considering that the profile could change the working dir.

**Comment by daviwil** [comment]
@rkeithhill good point on doing it before profile processing, hadn't thought about that.  I think having a setting is kindof nice because it makes it clear that this is a configurable option.  However, it's kindof moot if the user can just do this in their profile or workspace startup script.

What do you think, should we just simplify and allow configurating of starting path via profile?  We'd still set it to workspaceRoot by default before profiles get loaded.

**Comment by rkeithhill** [comment]
Probably better to start "simplified".  You could always add a setting later if folks really need it.  Certainly the **default** working directory is pretty useless.  One other thing to think about, is if we ever get a edit time REPL console in VSCode.  Would we set that to start in `workspaceRoot` or `$home`?  Does that have to be the same as the editor host's working dir or can it be set differently?

**Comment by daviwil** [comment]
That's basically the scenario I filed this for.  When I hit F8 in the editor currently, the working directory by default is the VS Code bin path in Program Files.  I'd prefer if the path is initialized to be the workspace path so that relative paths in dot source references, etc will resolve correctly when I'm hitting F8 in a script in the workspace.

**Comment by rkeithhill** [comment]
>> relative paths in dot source references, etc will resolve correctly when I'm hitting F8 in a script 

I think that depends on the directory structure though.  That would certainly work for the `module` folder structure we've been showing in the VSCode-Powershell Examples folder and what Plaster generates with the NewModuleTemplate example.  But some folks have been saying they'd put their module source a level down in a subfolder e.g. <ModuleName>.  In that scenario, the relative paths in script are mean to be relative to `${workspaceRoot}\<ModuleName>`.  

Now maybe I misinterpreted this request but even if I did, there's probably going to be folks that don't have their script running from workspaceRoot.  Perhaps their script gets put under `src` or something?  I guess for those folks, they can always set the current dir in the workspace init script or VSCode profile script.  Sorry, just thinking out loud here.  :-)

**Comment by daviwil** [comment]
Yep, I'm just thinking about the common case where someone opens a folder and wants to start working on files in that folder.  I'd definitely say anyone who wants the working path to be something else should use a profile or workspace init script.
