### ISSUE TITLE
Allow a function/scriptblock used with Register-EditorCommand to have parameters

### ISSUE THREAD

**Issue by lucdekens** [PowerShell/PowerShellEditorServices#239]
A function or scriptblock that is used with Register-EditorCommand would profit from the ability to receive parameters that are passed on the invocation.

For example: a command to correct casing on a line could have a parameter that says for how many lines.

**Comment by lucdekens** [comment]
Oops, just noticed there is already such a request

**Comment by daviwil** [comment]
Yep, this is something I'll look into.  For now you can use $host.UI.Prompt* methods to show prompts in VS Code inside of editor commands.  I'll close this so we can continue discussion on issue #220.  Thanks!
