### ISSUE TITLE
Redesign client/server model to more cleanly handle connections

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#245]
I'm currently in the process of introducing a new named pipe channel as the standard communication channel between the editor and language/debug servers.  This change has exposed a design flaw in the current client/server channel model where we don't really account for the state where the channel has been started but a connection hasn't been made yet.

After quite a lot of thinking and working on the issue, it seems that this is going to take a larger refactoring to make sure that the whole model will operate cleanly and effectively.  For now I've got a hacky solution worked out so I'm filing this issue to track the need for a real solution in the near future.

**Comment by gerane** [comment]
Is this related to the stdout etc?

**Comment by daviwil** [comment]
This work is done now, forgot to close it!
