### ISSUE TITLE
Logger shouldn't hold log file open for the life of the language service

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#248]
We should come up with an efficient way to batch writes to the log file without keeping it open for the entire language/debug server session.  This would help with other filesystem operations that might need to occur on the folder where the log file is being written.

Related issue: https://github.com/PowerShell/vscode-powershell/issues/207

**Comment by rjmholt** [comment]
Serilog should have a way to fix this

**Comment by rjmholt** [comment]
@SeeminglyScience

**Comment by rjmholt** [comment]
I think this has been fixed by Serilog's inclusion
