### ISSUE TITLE
ExtensionService should load the new BuiltInCommands.ps1 file

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#255]
@gerane has contributed a new BuiltInCommands.ps1 file which begins our support for built-in, community developed editor commands.  We need to evaluate this file when the ExtensionService is started up so that those commands always appear in the session.

Relevant PR: https://github.com/PowerShell/PowerShellEditorServices/pull/254

**Comment by daviwil** [comment]
Going to have to put this off one more release, just didn't have time to get it in for this one.

**Comment by TylerLeonhardt** [comment]
What if we just created a profile if it doesn't exist and add these as default commands?

**Comment by TylerLeonhardt** [comment]
It looks like that file was removed? I think this issue might be a relic of the past. I'll close it for now, let me know if anyone feels differently.
