### ISSUE TITLE
Add Save() and IsSaved/IsModified to FileContext API

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShellEditorServices#258]
Is there any method to save a file opened in the editor? Ideally, to save if it
is modified. If there is a way to check the modified state then I am just
looking for a way to save.

The context. I am working on `Invoke-TaskFromVSCode`, similar to [`Invoke-TaskFromISE`](https://github.com/nightroman/Invoke-Build/blob/master/Invoke-TaskFromISE.ps1).
The script with tasks should be saved before invoking the current task from it.

In ISE it looks like

``` powershell
$file = $psISE.CurrentFile
if (!$file.IsSaved) {
    $file.Save()
}
```

**Comment by nightroman** [comment]
Here is the current [Invoke-TaskFromVSCode.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Invoke-TaskFromVSCode.ps1). For now it requires a user to save the current build script manually before invoking a task. It would be very useful to make this saving automatic.

**Comment by daviwil** [comment]
Hey Roman, I can definitely add a 'Save' function and I believe I should be able to add an 'IsModified' field to show whether the file hasn't yet been saved.  I will try to get this in for the 0.7.0 release which should be out in the second half of July once I'm back from vacation.

**Comment by nightroman** [comment]
@daviwil 

When can we expect this little, useful, and long awaited piece of API?
I am not trying to push, just asking for some sort of planning.

**Comment by daviwil** [comment]
In the next feature update! $psEditor coverage is the short term priority now.

**Comment by nightroman** [comment]
This little feature would be very useful. Is it still on the radars?

I would use it right away for `Invoke-TaskFromVSCode` and make some Invoke-Build users a little bit happier.

**Comment by tylerl0706** [comment]
@nightroman it's on my radar now 😃 I'll look into this.

**Comment by tylerl0706** [comment]
@daviwil + @rkeithhill: It looks like `$psEditor` doesn't have a concept of `$psEditor.CurrentFile`. Is there another way to do it at the moment (via `Window` or `Workspace`) or would the addition of such a property (`CurrentFile`) need to happen as well as giving the FileContext API a Save() and IsSaved/IsModified?

**Comment by tylerl0706** [comment]
Ah. `$psEditor.GetEditorContext().CurrentFile` is the way to do it. 👍

**Comment by tylerl0706** [comment]
I have half of this in a PR so far:
https://github.com/PowerShell/vscode-powershell/pull/1139
https://github.com/PowerShell/PowerShellEditorServices/pull/590

I need to think about the IsModified method a bit more.

**Comment by nightroman** [comment]
@tylerl0706 Thank you!

> I need to think about the IsModified method a bit more.

If `Save` does not actually save to disk if the file is not modified then it's not a big deal for now.
But `IsModified` is useful on its own, indeed (though not in my scenario).

**Comment by tylerl0706** [comment]
> If `Save` does not actually save to disk if the file is not modified then it's not a big deal for now.

From a PSES perspective, it doesn't actually save to disk at all. It simply sends the "editor/saveFile" event to the editor - in our case, vscode. VSCode then handles the saving using the extensions API.

I can add an additional check to see if the file is dirty before it actually calls the VSCode save function.

Would that do what you need in the short term?

I'm still thinking on `IsModified`

**Comment by nightroman** [comment]
> I can add an additional check to see if the file is dirty before it actually calls the VSCode save function.

Yes, this will do the trick in the short term.

**Comment by nightroman** [comment]
I see it working great in 1.6.0. Thank you so much!
I will update my *Invoke-TaskFromVSCode.ps1* shortly.
