### ISSUE TITLE
Microsoft.PowerShell.EditorServices.Host.exe process constantly uses one CPU core

### ISSUE THREAD

**Issue by kieferrm** [PowerShell/PowerShellEditorServices#262]
Moved from https://github.com/Microsoft/vscode/issues/9503:
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Open VSCode
2. CPU utilization increases with 100/# of cores, which is takes constantly by the process Microsoft.PowerShell.EditorServices.Host.exe

**Comment by tylerl0706** [comment]
@ykuijs looks like you opened this on VSCode a long while back. Are you still seeing this issue?

**Comment by ykuijs** [comment]
@tylerl0706, No I haven't seen this issue anymore recently. You can close this issue

**Comment by tylerl0706** [comment]
Thanks!
