### ISSUE TITLE
Editor Services memory consumption is large due to Script Analyzer

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#269]
I'm not sure if this existed previous to 0.6.2 but given the small number of changes to 0.6.2, it must have. Anyway, while working on Plaster in VSCode today I noticed that the PSES language server process was consuming ~278 MB!  I created a dump file and loaded it into 2015 to analyze the managed memory.  This is what I see:

![pses-memory-hog](https://cloud.githubusercontent.com/assets/5177512/17645942/be3e19a2-6171-11e6-93b9-5c13520580d4.PNG)

If I burrow into the PSSA helper class I see:

![pses-pssa-mem-hog](https://cloud.githubusercontent.com/assets/5177512/17645962/bdd1b914-6172-11e6-8635-0ca85f738344.png)

Note that helper is a static, so it will never get collected and anything it has a reference to will never get collected on down the line.  Looking inside it, we see that it is holding onto a **lot** of AST:

![pses-helper-mem-hog](https://cloud.githubusercontent.com/assets/5177512/17645981/57e67198-6173-11e6-9a52-ab29daeb6c2e.PNG)

The DMP file is about 610 MB and I could make it available via my OneDrive account but I suspect you could recreate it pretty easily.  I'm on VSCode 1.4.0, Windows 10 1607 and PSSA 1.5.0.

**Comment by daviwil** [comment]
Yikes, good old 'Helper' class finally comes home to roost.  This was something I had pointed out a while back but we never got around to refactoring the code to get rid of it.  If nothing else we should definitely not be consuming so much memory over time.

Tagging @kapilmb so that he sees this analysis.

**Comment by kapilmb** [comment]
Looks like an instance of [VariableAnalysis class](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/VariableAnalysis.cs) is taking up a lot of memory. Will have a look at it.

**Comment by daviwil** [comment]
Awesome, thanks Kapil!

**Comment by kapilmb** [comment]
It turns out PSSScriptAnalyzer keeps adding ASTs to the `dictionary` without removing them even after having no use of them. But since, EditorService now uses `Invoke-ScriptAnalyzer` to get the diagnostic markers, this would not be an issue. I think we can close this issue now.
