### ISSUE TITLE
start-job failing

### ISSUE THREAD

**Issue by eric-jesover** [PowerShell/PowerShellEditorServices#272]
version 6.0.0.9

start-job -Name "Testing" -ScriptBlock {get-process}
receive-job -id xxx

the output is 
[localhost] The background process reported an error with the following message: -Version : The term '-Version' is not
recognized as the name of a cmdlet, function, script file, or operable program. .
    + CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : 2100,PSSessionStateBroken

this working correctly on 5.1.14393.0 on windows 10

**Comment by eric-jesover** [comment]
wrong depot :(

**Comment by daviwil** [comment]
No problem Eric!
