### ISSUE TITLE
Two errors immediately upon opening .ps1 file

### ISSUE THREAD

**Issue by philkloose** [PowerShell/PowerShellEditorServices#273]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601
- Powershell Extension Version 0.7.0

Steps to Reproduce:

1. Open fresh instance of VS Code.
2. Open any .ps1 file.
3. Note 2 errors at the top of the page

- **Error** Could not start language service: undefined
- **Error** Couldn't start client PowerShell Editor Services

[ExtensionFailedLoad.txt](https://github.com/PowerShell/PowerShellEditorServices/files/427119/ExtensionFailedLoad.txt)

**Comment by daviwil** [comment]
Hi Phil, there's an issue affecting older versions of PowerShell right now.  I'll be shipping an update to the extension early next week to address this.  I apologize for the trouble!
