### ISSUE TITLE
language-server-protocol ?

### ISSUE THREAD

**Issue by xied75** [PowerShell/PowerShellEditorServices#274]
Dear Team,

So excited to have all your hard work in the open now. May I ask a question: months ago Microsoft plus RedHat announced this: https://github.com/Microsoft/language-server-protocol which is meant to be a standard protocol for language services, it seems we are not using it here, is there any specific reason? Any plan to adopt that next?

Best regards,

**Comment by daviwil** [comment]
Hi Dong,

We are using that exact protocol already :)  The only difference is that we're a little behind on using the latest state of the protocol.  I'm also responsible for making a .NET library that is capable of communicating between language clients and servers, so as soon as that effort gets going we'll be updating to the latest protocol spec.

Are you thinking of using PowerShell Editor Services as a language server to another editor/product?

**Comment by xied75** [comment]
Hi @daviwil,

That is great. But I didn't see you listed here: https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

I'm in the middle of making a UWP app for Source Code reading, something like a Kindle Reader but for reading code. As you know the Syntax Highlighting, Go to Definition, etc. are supposed to be handled within the language server side, the UWP UI should be a client to consume that. From my understanding that current language servers can't run in UWP, is that correct?

It is interesting that you are working on the .NET lib, one question I have is can we somehow make the communication work in a UWP setting, in that the UWP is working inside a sandbox and can't have a background server always running, (i.e. needs to handle suspension etc.) Would be great to know how you think about this.

**Comment by ant-druha** [comment]
Hi guys. Sorry to jump into this thread but I'm also interested in adopting LSP for enhancing PowerShell support to IntelliJ editor in [this plugin](https://plugins.jetbrains.com/plugin/10249). Would you be so kind to advise me on up to date resources for implementing it via Host Process JSON-based API. Will it be ok for me to use the API, provided in [Using Host Process](http://powershell.github.io/PowerShellEditorServices/guide/using_the_host_process.html) docs? If not, will there be an updated version of documentation? If not, I will makes sense to use VSCode language client sources to get the API? Thanks in advance!

**Comment by tylerl0706** [comment]
@daviwil would be the best person to answer this.

**Comment by ant-druha** [comment]
Thank you @tylerl0706. I've checked now the [all supported message types](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs#L83). And now trying it with [intellij-lsp](https://github.com/gtache/intellij-lsp/tree/master/intellij-lsp) plugin and see the communication somehow works, though there are issues like [589](https://github.com/PowerShell/PowerShellEditorServices/issues/589). 
Though the **intellij-lsp** plugin does good job, in it's current shape it is not flexible enough for me. So I guess I will need to do my own extension client. Hence it would be great to understand the current state of things. Looking forward to reply. Thanks.

**Comment by rjmholt** [comment]
We're on that wiki page now. I'll close this issue and reopen if there are any further issues.
