### ISSUE TITLE
Add correct dependency to get OS/process info in CoreCLR

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#278]
To use the new `System.Runtime.InteropServices.RuntimeInformation` class to gather OS and process information for our initial logging in EditorServicesHost I'll need to pull in the expected dependency package since PowerShell doesn't seem to ship with it.  This work won't be possible until we start the conversion over to the dotnet-cli tools.

**Comment by tylerl0706** [comment]
Interesting - this still a problem since we've switched to dotnot-cli tools?

**Comment by daviwil** [comment]
This required some dependency that I didn't have access to at the time.  This is the place in the code where it was necessary:

https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Host/EditorServicesHost.cs#L130

I think it should be fixable now but it isn't a super high priority.

**Comment by rjmholt** [comment]
This is done!
