### ISSUE TITLE
Intellisense doesn't always work for powershell

### ISSUE THREAD

**Issue by 4c74356b41** [PowerShell/PowerShellEditorServices#279]
Sometimes in VScode powershell code doesn't have intellisense at all. Sometimes for some commands, sometimes for all commands.

![_](https://cloud.githubusercontent.com/assets/16194643/18000379/622396c8-6b86-11e6-9203-11df401c1573.png)

**Comment by rkeithhill** [comment]
Try switching the file type from 'Plain Text' to 'PowerShell' by clicking on 'Plain Text' in the status bar. Or you can save the file with a .ps1 extension. 

Keep in mind that VSCode is an editor for many different languages, not just PowerShell.

**Comment by 4c74356b41** [comment]
Well, it seems to work this way, but it takes intellisense like 10 seconds to kick in, is this expected? I have core i5 4200, 8gb ram, 256gb ssd...

**Comment by rkeithhill** [comment]
The issue with performance has been submitted and is being tracked here: https://github.com/PowerShell/vscode-powershell/issues/166

> can I set default to PowerShell somewhere?

Looking through VSCode settings, I don't see a setting for this.  It's a good idea though.  You might want to submit that to http://github.com/microsoft/vscode/issues.

**Comment by daviwil** [comment]
@4c74356b41 it could just be taking a little bit of time for the language service to get started up.  I need to add some "Loading" text in the status bar to make sure users are aware that the language service hasn't fully loaded yet.

**Comment by 4c74356b41** [comment]
well, it doesn't matter how long since vscode started. everytime you type a new commandlet (i mean, not the one not used before but any new commandlet) it won't show intellisense for like 5-10 seconds...

**Comment by daviwil** [comment]
Understood.  Do you mind sending some logs so I can take a look?  Zip up this folder and drop the zip file into the issue comment box:

`$HOME\.vscode\extensions\ms-vscode.PowerShell-0.7.1\logs`

**Comment by 4c74356b41** [comment]
ehm, sorry, but there's nothing in vscode directory... where should I look?

**Comment by daviwil** [comment]
There must be if you're using the extension :)  The line I gave you was meant to be run in PowerShell, you can try checking this path directly:

`c:\Users\<your username>\.vscode\extensions\ms-vscode.PowerShell-0.7.1\logs`

Let me know if that doesn't work for you

**Comment by 4c74356b41** [comment]
oh, sorry, i was looking in the application directory.
[logs.zip](https://github.com/PowerShell/PowerShellEditorServices/files/439968/logs.zip)

**Comment by 4c74356b41** [comment]
btw, I have another PC at my work, and I observe the same behaviour.

**Comment by 4c74356b41** [comment]
sorry to derail, is there an ability to launch\test\debug powershell in vscode? if so kindly point me to an article or something?

**Comment by rkeithhill** [comment]
@4c74356b41 Check out the [Debugging with Visual Studio Code section](https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md)

**Comment by 4c74356b41** [comment]
thanks. 

<#   
this is not recognized in vscode
in a sense that you can't collapse this.
#>

**Comment by daviwil** [comment]
Yeah, this is a limitation in VS Code currently.  All code folding is done based on indentation and without any awareness of language constructs.  If you indent the lines within the comment block it will be collapsible.  I'm pushing them to start making progress on this soon.

**Comment by 4c74356b41** [comment]
ic, any info on my logs?

**Comment by daviwil** [comment]
Hey @4c74356b41, looks like no verbose logs are being written out.  Can you add this setting in VS Code, reproduce the issue again, and send the new logs?

`"powershell.developer.editorServicesLogLevel": "Verbose"`

Thanks!

**Comment by 4c74356b41** [comment]
I think I've figured this out, sometimes PS session will crash and VSCode won't restart it
