### ISSUE TITLE
Migrate project to .NET CLI

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#281]
Since we officially support multiple platforms now, it's time to get the project moved over to .NET CLI.  This should hopefully make the project easier to clone, build, and contribute to across our platforms.

**Goals**
- Single build script that works across all platforms and on CI systems (AppVeyor, Travis CI)
- Do all project work in VS Code (develop, build, test)
- Potentially get a good debugging setup going so that we can launch VS Code in dev mode and attach to PSES with the original VS Code instance's debugger

**Comment by pcgeek86** [comment]
+1

**Comment by daviwil** [comment]
This has been done for a while, forgot to close it.
