### ISSUE TITLE
Split the Editor Services PSHost implementation into a separate project

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#292]
While working on making Editor Services run inside of the standard PowerShell console host, I came to the realization that PSES should not provide its own PSHost implementation.  Instead, Editor Services should be usable in _any_ PowerShell host implementation and blend in cleanly.  This means that the current PSHost implementation (plus other console management abstractions) don't need to be a core part of Editor Services any longer.

In fact, it's better if that code can be extracted from the project entirely so that the Editor Services project can focus completely on providing language and debugging services to editors from within any PowerShell host (even if the editor has implemented its own custom host).

From the original hosting code, we could start a new common library to simplify the hosting of PowerShell inside of a .NET application.  Since this code may be more generally valuable, it makes sense to live in its own project.  If people are interested in seeing that happen we could get such a project kicked off in a few months.

In the meantime I'll be extracting the current hosting code from Editor Services.  Any future development on the shared PSHost library should start from the code inside of commit dba6515.

**Comment by tylerl0706** [comment]
> we could start a new common library to simplify the hosting of PowerShell inside of a .NET application
This would use PowerShell Standard?

Also, I thought that that our own implementation of PSHost was need, no?

**Comment by daviwil** [comment]
I think I've moved on from this idea, gonna close it for now.  I think it'd be better to find ways to make PowerShell's PSHost APIs better and the ConsoleHost more reusable.
