### ISSUE TITLE
Consider using Microsoft.Extensions.Logging to replace Logger class

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#293]
I'm considering getting rid of the current `Logger` class and replacing it with [`Microsoft.Extensions.Logging`](https://github.com/aspnet/Logging) so that multiple logging providers can be used at once.  This would allow us to write not only to a log file but also send log messages to other sinks like a real-time log viewer or the host editor.

Haven't fully decided yet whether this will be a beneficial change, would certainly be interested to hear feedback.

**Comment by randomchance** [comment]
I think this is a solid change, logging is one of those things that tends to be simple until it isn't, and then you outsource it.

**Comment by daviwil** [comment]
Absolutely!  I'm also thinking it's good to standardize on a common framework that might also be used by other modules/apps so that PSES logging can be integrated with other logs if used in a larger context.

**Comment by tylerl0706** [comment]
This would be nice

**Comment by daviwil** [comment]
I think I looked into this last year sometime and wasn't totally satisfied for some reason.  I think it's because enabling structured logging would mean taking a dependency on a third-party OSS library like serilog, which I really didn't want to do.  Keeping PSES' DLL count low seemed like a better priority.

That said, it'd be nice to make PSES's logging code more structured so that its easily parseable by code/scripts.

**Comment by rjmholt** [comment]
We've now taken on Serilog as a dependency since it just fixed a lot of issues for us in an easy way. I think we can close this issue for now and if there are any further items for discussion we can reopen.
