### ISSUE TITLE
Update to latest PSScriptAnalyzer

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#294]
We're currently shipping 1.7.0 and should update to 1.8.0 (at least) for the upcoming 0.8.0 release.  It has a few goodies we want IMO: https://github.com/PowerShell/PSScriptAnalyzer/blob/development/CHANGELOG.MD

**Comment by kapilmb** [comment]
We do not ship PSScriptAnalyzer with VSCode anymore. EditorServices depends on an already installed PSScriptAnalyzer module.

**Comment by daviwil** [comment]
For the moment we do still ship PSSA with the VS Code extension, but I'd like to avoid that in the future.  I'll  make sure we're tracking that appropriately.  For 0.8.0 we'll need to include PSSA until we do the work to make a smooth transition to a non-bundled PSSA.

**Comment by daviwil** [comment]
Tracking the unbundling of the module here: https://github.com/PowerShell/vscode-powershell/issues/360

**Comment by kapilmb** [comment]
Got it!

**Comment by daviwil** [comment]
I'm bundling PSScriptAnalyzer 1.9.0 with the 0.8.0 release of the VS Code extension.
