### ISSUE TITLE
Move code for finding available ports from bootstrapper script to EditorServicesHost

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#296]
The `Start-EditorServices.ps1` bootstrapper script currently scans for available TCP ports before starting up the language and debug services.  This should not happen in the bootstrapper, but somewhere inside of the C# code.  This logic should be moved.

**Comment by tylerl0706** [comment]
Looks like this is still a thing. Any reason why we should do this?

**Comment by daviwil** [comment]
We need to scan for available ports so that we don't try to use one that's already in use, but that code definitely shouldn't be in Start-EditorServices.ps1.  It'd be nice if we could port it to C# in the PowerShellEditorServices.Host assembly, that'd simplify Start-EditorServices a lot.

**Comment by rjmholt** [comment]
@tylerl0706 This should be easy to fix now

**Comment by rjmholt** [comment]
Closing, since we no longer use TCP
