### ISSUE TITLE
Investigate if Wait-Debugger can be made to work with the PSES

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#299]
Not sure if this is possible but at the very least if I run a script from the PSES debugger it would be nice if the Wait-Debugger command would pause the PSES debugger.

**Comment by tylerl0706** [comment]
Can you explain this one a little more?

**Comment by rkeithhill** [comment]
`Wait-Debugger` is a command that you can put in a script that will stop the script at that point in the debugger.  I think this is probably CLI debugging oriented but it would be nice if we could use the extension/VSCode to do the debugging after that command has been invoked.  I think of it kind of like calling DebugBreak() (or System.Diagnostics.Debugger.Break()).

**Comment by rkeithhill** [comment]
And indeed it does work!  Cool.
