### ISSUE TITLE
Add support for module debugging

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#305]
In addition to debugging scripts, we should also support the debugging of modules.  If the user sends a .psd1 file as the script to debug, we could just load that module into the session and then allow the user to type whatever commands they like in the debug console to execute the module code where they've set breakpoints.

We could also allow a way for the user to specify a "startup script" inline, basically just a few lines of script code that get executed just after the module is loaded.

**Comment by Josverl** [comment]
My suggestion for implementation would be to scaffold a simple pester test for that module 
then 'the few lines of script' can be added by the user to debug ,
and as a bonus the user is developing unit tests at the same time.

A simple scaffold for the base module tests can be generated using plaster, or any other template, with some additional hints on where to add the test code.
optionally the pester tests can be specifically decorated with a 'debug' tag to avoid running too many tasks

**Comment by daviwil** [comment]
Didn't realize this issue was still open!  Module debugging is now fully possible with the proper debugging configuration.  In VS Code it's as simple as setting a breakpoint in your module using `Set-PSBreakpoint` and then loading/running your module code.

I do like the idea of generating basic tests from a module though, that might be better suited as a separate issue.
