### ISSUE TITLE
High CPU usage in MessageReader.ReadNextChunk

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#31]
Bug details from @rkeithhill:

It seems that the app is stuck in a loop in MessageReader here:

``` csharp
       private async Task<bool> ReadNextChunk()
        {
            // Do we need to resize the buffer?  See if less than 1/4 of the space is left.
            if (((double)(this.messageBuffer.Length - this.bufferEndOffset) / this.messageBuffer.Length) < 0.25)
            {
                // Double the size of the buffer
                Array.Resize(
                    ref this.messageBuffer, 
                    this.messageBuffer.Length * 2);
            }

            // Read the next chunk into the message buffer
            int readLength =
                await this.inputStream.ReadAsync(
                    this.messageBuffer,
                    this.bufferEndOffset,
                    this.messageBuffer.Length - this.bufferEndOffset);

            this.bufferEndOffset += readLength;

            return readLength >= 0;
        }
```

The ReadNextChunk() method hits the await inputStream.ReadAsync and returns immediately with 0 bytes read.  Rinse and repeat and that is why, I think, the CPU usage is high.  I wonder if the bool check above should be readLength > 0. If I set a conditional breakpoint on the that (readLength == 0), it only seems to break when I exit VS Code.  And the docs on ReadAsync say this:

A task that represents the asynchronous read operation. The value of the TResult parameter contains the total number of bytes read into the buffer. The result value can be less than the number of bytes requested if the number of bytes currently available is less than the requested number, or it can be 0 (zero) if the end of the stream has been reached.

If I change that line to readLength > 0, then VS Code seems to auto-complete cmdlet names just fine and on exit of VSC, the services will exit. However, if I have a debugger attached when VSC closes, I get an uncaught ArgumentNullException.  I suspect that is because caller of ReadNextChunk() tries to have messageContent (which is null), parsed e.g.:

```
            // Return the parsed message
            return this.messageParser.ParseMessage(messageContent);
```

The last message it was processing I think is:

```
System.Text.Encoding.ASCII.GetString(this.messageBuffer)
"Content-Length: 158\r\n\r\n{\"seq\":1,\"type\":\"request\",\"command\":\"geterr\",\"arguments\":{\"delay\":750,\"files\":[\"c:/Users/hillr/.vscode/extensions/vscode-powershell/examples/DebugTest.ps1\"]}}58\r\n\r\n{\"seq\":1,\"type\":\"request\",\"command\":\"geterr\",\"arguments\":{\"delay\":750,\"files\":[\"c:/Users/hillr/.vscode/extensions/vscode-powershell/examples/DebugTest.ps1\"]}}\0\0\0\0…
```

**Comment by tylerl0706** [comment]
@daviwil did you ever get that interim fix in?

**Comment by daviwil** [comment]
I think so, we haven't had reports of this issue in a really long time.  I'll close it for now!
