### ISSUE TITLE
Re-Registering an Editor Command without -SuppressOutput requires Reload

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#319]
I'm not sure if this was intended or not, but wanted to ask if this was working as intended.

If you have an Editor Command that is registered, and you Register it again without -SuppressOutput
it will continue to Suppress all output until a reload of the Editor. It can be a little confusing because it registers any other changes you might make to the Editor Command.

**Comment by daviwil** [comment]
That seems pretty weird, I'll look into it.  Thanks!

**Comment by gerane** [comment]
Not that big of a deal, but figured I'd report it.

**Comment by SeeminglyScience** [comment]
Hey @gerane, can you confirm if this is still happening for you?  I can't get it to reproduce.

**Comment by tylerl0706** [comment]
Hey @gerane, I'm going to close this issue since it's been inactive for some time now. If you're still seeing the issue, let me know and we can reopen!
