### ISSUE TITLE
Proposal: Symbol categories to surface for "Go to Symbol" feature

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#33]
Visual Studio Code has two related features that this proposal addresses: Go to Symbol and Go to Symbol by Category accessed with `Ctrl+Shift+O` or `Ctrl+P, @` and `Ctrl+P, @:`.  For a JavaScript file, the follow symbols are shown:

![image](https://cloud.githubusercontent.com/assets/5177512/11170661/17f67184-8b98-11e5-9db1-fcc6943117ca.png)

And by category:

![image](https://cloud.githubusercontent.com/assets/5177512/11170671/64817e04-8b98-11e5-887d-d83b960889a9.png)
## PowerShell Symbol Categories

For PowerShell, I propose the following categories:
- functions (both simple and advanced as well as filters)
- workflows
- configurations
- classes
- properties (properties within classes)
- methods (methods within classes)
- enums
- variables (script-scope only)

Filters could be a category but they are not significantly different from functions and with the advent of advanced functions, I don't believe filters are widely used anymore.

The JavaScript support only shows global variables - not function-scoped variables.  I suggest that we only show script-scope variables as well (assuming this can be determined from the AST).  If scope can't be determined from the AST then I propose not showing variables.

**Comment by tylerl0706** [comment]
Looks like this work is done 😄 
![image](https://user-images.githubusercontent.com/2644648/33737035-a6e6aa28-db49-11e7-809b-c1e3a89df079.png)

Please reopen if you see otherwise.
