### ISSUE TITLE
Syntax coloring issue with regex

### ISSUE THREAD

**Issue by fromthewoods** [PowerShell/PowerShellEditorServices#374]
I searched around and couldn't find any existing issues that address what I'm seeing, so apologies if this is already known.

I have a simple regex pattern `[ValidateScript({$_ -match '^([\d\w]+\.){2,3}[\d\w]+$'})]`
that vscode seems to not be able to handle and I assume it's an issue with PSEditorServices.
![image](https://cloud.githubusercontent.com/assets/5445673/23099888/57b1ac7e-f62e-11e6-9dec-101459052f48.png)

PowerShell ISE handles the same pattern properly.
![image](https://cloud.githubusercontent.com/assets/5445673/23099889/65633cac-f62e-11e6-816d-36f6ff88c990.png)

**Comment by fromthewoods** [comment]
Did I put this in the wrong repo? Should this be in [PowerShell / vscode-powershell](https://github.com/PowerShell/vscode-powershell) or [Microsoft / vscode](https://github.com/Microsoft/vscode) ?

**Comment by rkeithhill** [comment]
It should go in https://github.com/powershell/editorsyntax.

**Comment by daviwil** [comment]
This issue was moved to PowerShell/EditorSyntax#37
