### ISSUE TITLE
Setting variable values in the debugger is broken

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#376]
I think this happen with the `0.9.0` release.  I'm running VSCode 1.10.2 on Windows 10 AU.  Here is the error I'm seeing:

![image](https://cloud.githubusercontent.com/assets/5177512/23781396/3f7b3f5e-050a-11e7-9df5-b0962bb1a3a2.png)

**Comment by tylerl0706** [comment]
I can't repro this anymore 😄 if you're still seeing it, reopen/open a new issue!

**Comment by daviwil** [comment]
I think we may have fixed it in the middle of last year with some other changes.
