### ISSUE TITLE
0.10.0 formatting broke magic foreach

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShellEditorServices#380]
`(0 .. 10).Foreach{$_}` is formatted into `(0 .. 10).Foreach {$_}` which the compiler will not accept.

Same thing with `.Where{}`

**Comment by powercode** [comment]
It can be worked around by using the `.Foreach( {$_} )` construct instead, but it is bad since it breaks scripts by just saving them when auto formatting is enabled.

**Comment by daviwil** [comment]
Hey Staffan, thanks for filing this!  @bgelens also noticed it.  We'll get it fixed :)

**Comment by daviwil** [comment]
Hey @kapilmb, here's one more formatting issue we need to look into.  Looks like there are two cases where we should be making an exception for the "space before open brace" rule, `.Foreach{` and `.Where{`, both of which have special behavior in PowerShell.

**Comment by kapilmb** [comment]
Oops, looks like this flew under my radar. Will have a fix soon!
