### ISSUE TITLE
Don't need to ship vshost binaries

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#39]
The following vshost files are in the extension's bin dir:
```
Microsoft.PowerShell.EditorServices.Host.vshost.exe
Microsoft.PowerShell.EditorServices.Host.vshost.exe.config
Microsoft.PowerShell.EditorServices.Host.vshost.exe.manifest
```
No need to ship these.  Could say the same for the XML (doc comment) files as well.

**Comment by rkeithhill** [comment]
Check. I see the vshost binaries are no longer there.  How about the XML files?  They're not huge (< 1 MB combined) but unnecessary, right?

**Comment by daviwil** [comment]
Yep, also unnecessary.  I'm being a bad PowerShell user and copying things by hand right now.  For the next release I'll automate the packaging and leave out all the extraneous stuff :)
