### ISSUE TITLE
PSES is adding errors into Integrated Terminal when exe\cmd scripts are executed

### ISSUE THREAD

**Issue by gerane** [PowerShell/PowerShellEditorServices#396]
When executing external commands like git.exe, vsce.cmd, and similar. Also noticed it will error if I run help using pscx and it is using **more.com** for pagination. When the command finished an error is added to the output.

Example: `help commandname -full` 

![2017-03-20_12-40-49](https://cloud.githubusercontent.com/assets/6662208/24113348/883bc1e2-0d6a-11e7-8319-5f5da3816ba2.png)

Another example using vsce to publish an extension.

![errorsterminal](https://cloud.githubusercontent.com/assets/6662208/24113368/963b8958-0d6a-11e7-8a49-9fb1361bc1f3.png)

And here is an example when using git status

![2017-03-20_12-43-13](https://cloud.githubusercontent.com/assets/6662208/24113436/d23e5fe8-0d6a-11e7-9fb8-c31e6342b7c5.png)

Here are the logs from the vsce command. This is how they have looked for these.

https://gist.github.com/gerane/6e8f221cfa6789fb6b191917bdb3cca1

**Comment by rkeithhill** [comment]
Certain exe's have a habit of tweaking the console mode. https://github.com/PowerShell/PowerShell/issues/1177

PS Core has supposedly started to always restore the console mode after invoking an exe (better double check that with @lzybkr).  But for <= v5, you have to do that yourself.  We found this with posh-git and use this code to reset the console mode: https://github.com/dahlbyk/posh-git/blob/develop/src/ConsoleMode.ps1

**Comment by daviwil** [comment]
Thanks Keith!  I can't get the other Keith's repro to work for this on PS 5.1, have you found another way to repro the issue?

**Comment by rkeithhill** [comment]
Hmm, not yet. Although I have seen this issue on and off with git.exe starting to generate error records (NativeCommandError) in PowerShell.exe while testing posh-git.  https://github.com/dahlbyk/posh-git/issues/404

We never did figure this out.  We closed it "assuming" it wasn't a posh-git issue.

**Comment by daviwil** [comment]
See this comment for possible fix: https://github.com/PowerShell/vscode-powershell/issues/972#issuecomment-327878407
