### ISSUE TITLE
Improve parameter Intellisense sorting

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#40]
Right now, command-specific parameters are mixed in with common parameters.  

![vscintellisense](https://cloud.githubusercontent.com/assets/5177512/11246425/d83fb44e-8dd4-11e5-9419-df74a24ff0d0.png)

Ideally, I'd love to see VSC support a tabbed Intellisense popup (like I've seen before in VS) where there would be two tabs as shown I the C# popup:

![vsintellisense](https://cloud.githubusercontent.com/assets/5177512/11246396/bacbbc50-8dd4-11e5-9422-dcbad1d81eef.png)

Where the first tab would show the command-specific parameters and the second tab would show common parameters.

If VSC doesn't support this then I propose that the parameters are listed in the following order:
* Sorted non-common parameters
* Line separator (if possible)
* Optional common parmeters
* Line separator (if possible)
* Sort common parameters

For example, this is an example of the above for Stop-Process:
```
Force
Id
InputObject
Name
PassThru
----
Confirm
WhatIf
----
Debug
ErrorAction
ErrorVariable
InformationAction
InformationVariable
OutBuffer
OutVariable
PipelineVariable
Verbose
WarningAction
WarningVariable
```
I think this order would be more useful to PowerShell scripters.  Personally, I'm almost always more interested in the command-specific parameters.

**Comment by rkeithhill** [comment]
I looked at this a bit over the weekend.  It appears the extension is passing the parameters in the same (non-alpha) order to VSCode that I observe in ISE.  VSCode must be sort the list.  That's too bad, wish we could suppress that.

**Comment by daviwil** [comment]
For the JSON protocol there's a 'SortText' field that I haven't been using yet.  I bet we'd get the right ordering if we prefix the label text to populate SortText based on the type of parameter.  Something like:

```
1 Force
1 Id
...
----
2 Confirm
2 WhatIf
----
3 Debug
3 ErrorAction
3 ErrorVariable
...
```

Could also just use an ordered integer converted to a string if you want to completely eliminate the sorting.  Check out the CreateCompletionItem method in `src\PowerShellEditorServices.Protocol\Server\LanguageServer.cs`.

**Comment by rkeithhill** [comment]
Will do.  Thanks.

**Comment by rkeithhill** [comment]
So just putting an increasing integer converted to string in the SortText field didn't do the trick.  Guess I need to read up on the CompletionItem semantics.

**Comment by daviwil** [comment]
There are docs for the CompletionItem parameters on this page:

https://code.visualstudio.com/docs/extensionAPI/vscode-api

sortText should work, but maybe there's a bug?  Also filterText looks interesting, I wonder if it can help you do the other idea you had about having different IntelliSense sections.

**Comment by rkeithhill** [comment]
This has been fixed. The sort order for parameters should be the same as you see in ISE now.  This will require an updated VSCode (>= 0.10.7) in order to get the preferred sort order (since there was a bug in VSCode where it ignored the sortText field).
