### ISSUE TITLE
Sync up with new CompletionItemKinds

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#407]
See https://github.com/Microsoft/vscode/issues/2628#issuecomment-289692132

Will have to wait until these are available in VSCode.

**Comment by daviwil** [comment]
Thanks!  Yeah, there's also a larger issue of needing to update to the latest language server protocol, need to get that going soon.

**Comment by tylerl0706** [comment]
I think this work is already done since we're on the latest version of the LSP. Is that true?

**Comment by rkeithhill** [comment]
The work for file/folder is done but there is a bit more work do here for enum values and probably some other completion item types.

**Comment by daviwil** [comment]
They keep adding more stuff to LSP 3.0 so it was never fully "done" :)  I may try to get caught up on this soon while I'm hooking things up in Atom.
