### ISSUE TITLE
Enable piping multiple file paths through `psedit` to open those files

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShellEditorServices#413]
This would be a time saver. List files in the integrated console and pipe the list to `psedit` to be opened in vs code.

```powershell
ls *.log | psedit
```

The current implementation does not support multiple files and does not flow as easy.
```powershell
psedit (ls *.log)
```

**Comment by daviwil** [comment]
Love this idea, I'll see how we can make it happen.

**Comment by daviwil** [comment]
Ahhh, I think I misunderstood this one.  I was thinking you could do something like `Get-Process | psedit` and throw the output of a command into a new untitled buffer.  I'll file a separate issue for that :)
