### ISSUE TITLE
Enable piping text to `psedit` to open a new untitled buffer

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#414]
It should be possible to pipe text from an arbitrary command into `psedit` to open a new untitled file buffer.  For example:

`Get-Process | psedit`

**Comment by tylerl0706** [comment]
It would be cool if we could get this in 1.6.0. I'd love to see if I could get this working.

**Comment by daviwil** [comment]
This would definitely fit with a `New-EditorFile` cmdlet.  Could have an optional pipeline param that accepts a string with the new file contents.

**Comment by tylerl0706** [comment]
That'd be great!

**Comment by tylerl0706** [comment]
Now that we've changed `psedit` to `Open-EditorFile` and want to add a `New-EditorFile` maybe we should consider creating a PowerShell module that EditorServices can import into it's session rather than calling the script block here:
https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Session/RemoteFileManager.cs#L39-L96

**Comment by tylerl0706** [comment]
Open-EditorFile
New-EditorFile
Get-EditorFile
Close-EditorFile
Delete-EditorFile
Rename-EditorFile

**Comment by rkeithhill** [comment]
From a maintenance point of view, it would be much nicer to edit those functions as PowerShell script vs C# strings.  :-)  Although, would we ship the module only with PSES?  Would there be any need to put it on PSGallery?

**Comment by tylerl0706** [comment]
@rkeithhill even if we only ship it with PSES, it's probably still cleaner to pull the strings out into it's own PowerShell script.

That said, it _could_ go on the gallery and then brought in for a release. That way we could separate it into its own repo.

I wonder how testing that module would work. 🤔

**Comment by SeeminglyScience** [comment]
I feel like I'm missing something.  Those strings are just implementation detail for creating/cleaning up the function that opens files in remote sessions.  Most of them aren't actually functions.

I'm all for getting the functions you listed implemented though.  But I'd be hesitant to load them into every runspace we enter.

**Comment by tylerl0706** [comment]
Right, we're talking about expanding on the function that opens files. I'd rather not implement other functions (like `New-EditorFile` in a string in C#) It would be more valuable to have this pulled out to a PowerShell module so that the creating/cleaning is just a matter of importing and removing the module.

That also enables us to add other functions like the ones I mentioned above. We'd just add them to the module rather than messing with strings in C#.

**Comment by tylerl0706** [comment]
what's the issue loading them into every runspace? It's not _that_ much logic, is it?

I think your hesitation is valid though which got me thinking...

what if *-EditorFile was a totally separate module and the user had the option to install it or not.

They could install it via `Install-Module` and use it. That way those that want it can have it, but it doesn't bloat up the runspaces.

^ (half thought - not fully thought out)

**Comment by SeeminglyScience** [comment]
@tylerl0706 Oh yeah they should definitely be in a module.  Anything the user would actually call I think. 
 Aside from the proxy psedit command. Any reason we wouldn't put them in [commands](https://github.com/PowerShell/PowerShellEditorServices/tree/master/module/PowerShellEditorServices/Commands)?

> what's the issue loading them into every runspace? It's not that much logic, is it?

I guess it depends on what they do.  For most things we'd need to set up events to forward back to the main session.  If it was just loading functions then yeah it'd probably be fine.

**Comment by tylerl0706** [comment]
Now I feel like _I'm_ missing something 😄 

> Aside from the proxy psedit command

Are you saying psedit can't go in "commands"? If so why can't it? If it can, I think it totally should go in commands.

**Comment by SeeminglyScience** [comment]
@tylerl0706 it most certainly can, in fact [it already is](https://github.com/PowerShell/PowerShellEditorServices/blob/38c14502f73c6eb2de3b00be74135e43c2420205/module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1#L80) :P

I was talking about the proxy psedit for remote sessions

**Comment by tylerl0706** [comment]
I see. So I guess the question is, what would we want to be loaded in a remote session?

I would think maybe `open-editorfile` and `new-editorfile`... That's it.

Side thought, do you think we could get away with folding new file creation into `open-editorfile` 

Maybe that's not PowerShell-y 🤔

**Comment by SeeminglyScience** [comment]
Actually if open created files with a `Force` parameter that'd be pretty PowerShell-y. Plenty of precedent for that I think

**Comment by tylerl0706** [comment]
and piping into `Open-EditorFile` would still be PowerShell-y if given a `-Force`?

**Comment by tylerl0706** [comment]
```powershell
irm mysite.com/foo.ps1 | open-editorfile foo.ps1 -force
```

**Comment by SeeminglyScience** [comment]
Yeah, `New-Item`'s `Value` parameter takes pipeline input.  I don't see why not.
