### ISSUE TITLE
F5 on Untitled-1 file in 0.12.1 with existing .vscode\launch.json from prev version hangs debugger

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShellEditorServices#417]
This is the log.
[EditorServices.txt](https://github.com/PowerShell/PowerShellEditorServices/files/894657/EditorServices.txt)

and the launch.json
[launch.txt](https://github.com/PowerShell/PowerShellEditorServices/files/894658/launch.txt)

**Comment by daviwil** [comment]
This issue was moved to PowerShell/vscode-powershell#650
