### ISSUE TITLE
Return consistently-cased file paths to the editor

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#420]
Since VS Code is case-sensitive regarding file paths, it will show two editor tabs for the same file when debugging if a breakpoint is hit in a file where the casing is different from the tab it's already open in.

**Comment by daviwil** [comment]
Potentially related to this issue in VS Code: https://github.com/Microsoft/vscode/issues/12922

**Comment by TylerLeonhardt** [comment]
This seems like the mentioned vscode bug and we should close this as upstream
