### ISSUE TITLE
Support for Bitness Selection

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellEditorServices#43]
The ISE and PoshTools allows you to select the bitness of the PowerShell host. PSES should probably build the host in two different configurations so that this is possible.

**Comment by daviwil** [comment]
Yep, definitely need to have 2 host EXEs, one for each bitness like PoshTools has.

**Comment by daviwil** [comment]
I believe this one is fixed already by Adam's PR:

https://github.com/PowerShell/PowerShellEditorServices/pull/92
