### ISSUE TITLE
$psEditor.GetEditorContext() doesn't work with untitled-1 unsaved file

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShellEditorServices#434]
Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred."
At line:1 char:1

**Comment by daviwil** [comment]
Thanks for catching that one!

**Comment by daviwil** [comment]
I screwed up the issue tag for this, but this has been fixed now as of https://github.com/PowerShell/vscode-powershell/pull/811, will be in 1.2.1.
