### ISSUE TITLE
Debugging Workflow Dependencies

### ISSUE THREAD

**Issue by alohaninja** [PowerShell/PowerShellEditorServices#440]
VS Code PS extension enables you to debug worfklows, but you cannot **Step-Into** function dependencies that are loaded by the workflow. 

The workaround for me was to convert my workflows back to functions which prevents me from using `-parallel` and `-throttlelimit` flags for parallel processing.

**Comment by daviwil** [comment]
Thanks Aaron!  Are you able to debug workflows successfully using the ISE?  Since the workflow engine converts the PowerShell code to a different runtime I'm not sure how that would work in practice.

**Comment by tylerl0706** [comment]
Feel free to open another issue if you can confirm this works in the ISE but not in VSCode!
