### ISSUE TITLE
Variable

### ISSUE THREAD

**Issue by NumberX** [PowerShell/PowerShellEditorServices#442]
I développe a extension debug for lldb in vscode. 
I see in your  debug extension , you have add a auto variable, can you tell me how we can add another type  of variable in variable windows  in vscode.
Cordialement.

**Comment by rkeithhill** [comment]
Sorry for the delayed response.  We create a "synthetic" scope for Auto e.g.:
```csharp
        public VariableScope[] GetVariableScopes(int stackFrameId)
        {
            int localStackFrameVariableId = this.stackFrameDetails[stackFrameId].LocalVariables.Id;
            int autoVariablesId = this.stackFrameDetails[stackFrameId].AutoVariables.Id;

            return new VariableScope[]
            {
                new VariableScope(autoVariablesId, VariableContainerDetails.AutoVariablesName),
                new VariableScope(localStackFrameVariableId, VariableContainerDetails.LocalScopeName),
                new VariableScope(this.scriptScopeVariables.Id, VariableContainerDetails.ScriptScopeName),
                new VariableScope(this.globalScopeVariables.Id, VariableContainerDetails.GlobalScopeName),
            };
        }
```
Where the VariableScope is just a class to hold the scope id and name.  Then as we are process stack frames, we determine which variables should also be put in the Auto scope in addition to their actual scope (Local, Script, Global).

**Comment by tylerl0706** [comment]
Hope Keith answered your question :)
