### ISSUE TITLE
Consider moving to netstandard2.0

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#449]
It seems this isn't necessary just yet for PowerShell 6.0.0-beta1, the netstandard1.6 binaries load just fine there.  We should evaluate what we'd gain by moving to netstandard2.0 in terms of APIs, though.

This work was started here but not merged yet: https://github.com/PowerShell/PowerShellEditorServices/pull/448

**Comment by rjmholt** [comment]
@tylerl0706 is this a performance thing?

**Comment by tylerl0706** [comment]
I'd say so. Ultimately when we drop v3 v4 we can start converting everything to Standard 2.0 and then drop .NET Framework 4.5.1.

**Comment by SydneyhSmith** [comment]
Closing in light of the preview extension
