### ISSUE TITLE
Support Plaster 1.1.0

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#461]
Plaster 1.1.0 hasn't been released yet, but anyone who tries to use Plaster from GitHub with the PowerShell extension will see errors like this:

![image](https://cloud.githubusercontent.com/assets/79405/26327475/77e3aa24-3ef4-11e7-80de-d9b32560dbc8.png)

We need to support the changes that have been made to Plaster so that the language server doesn't crash.

Thanks @bgelens!

**Comment by rkeithhill** [comment]
I haven't done enough testing on PS Core 6 Beta on .NET Core 2 either.  I can test on Ubuntu easily enough.

**Comment by daviwil** [comment]
We have to use Travis CI for Linux and macOS. I had started looking into it in the past but haven't got anything working yet.  It'd be good to find a replicable Travis CI setup for all these projects!

**Comment by rkeithhill** [comment]
Yeah, having cross platform Pester testing would be nice.

**Comment by PowerSchill** [comment]
The goal would be to add Linux and macOS testing to the Plaster repo or here?

**Comment by daviwil** [comment]
Both!  We'd test PSES here and Plaster at the Plaster repo.

**Comment by tylerl0706** [comment]
@daviwil looks like we're beyond this issue as Plaster 1.1.3 ships with the vscode extension. Is this about something else?

**Comment by daviwil** [comment]
Nope, just didn't remember to close it.
