### ISSUE TITLE
Potential naming and conceptual changes in Host and Protocol layers

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#471]
I've been refactoring a lot of code in the Host and Protocol assemblies to enable the new PSES-as-a-framework model and it's given me a chance to think about the names of the classes there.  For example, EditorServicesHost is a bad name because PowerShell already has a concept of a "host."

After some thought, I think I want to make the following conceptual changes:

- What we called `EditorServicesHost` before should be called an `EditorServer` because it provides a server that hosts language and debugging services
- The `LanguageServer` and `DebugAdapter` should be called `LanguageService` and `DebugService` because those are the only two high-level services that we provide (I'm removing the concept of *Service in the core assembly)

Specific areas where I could use some feedback:

- `EditorServer` isn't really great either because it's not exactly a server for an editor.  Doesn't make sense to call it `ServicesServer` or `EditorServiceServer` because that's too redundant.  I've considered `ExtensionServer` because it's the server side of an extension to the host editor, but that also seems misleading in some ways.
- `LanguageService` doesn't really capture the whole story of what it provides, though it does parallel the concept of a "Language Server" so it might be OK.  Open to suggestions on what could be a better name for this one.
- Should it be `DebugService` or `DebuggerService`?  I'm leaning toward the latter because it's clearer but I could be wrong.

Thoughts?

**Comment by dfinke** [comment]
Could you say a bit more about PSaaF? What are you thinking to integrate this into or wants this integrated?

**Comment by rkeithhill** [comment]
RE `EditorServicesHost`, could we use just `EditorServices` which is comprised of language services and debug services.  FWIW I like `LangaugeServices` based on my (limited) experience with VS and VSIP pkgs. From the MSDN docs:
> The purpose of a language service in Visual Studio is to provide language-specific support for editing source code in the integrated development environment (IDE). You implement a language service as part of a VSPackage.

`DebugService` sounds right to me.  And is in line with the docs on creating a custom`debug` engine for VS: https://msdn.microsoft.com/en-us/library/bb145934.aspx

RE `DebugService` vs `DebugAdapter` - don't we still need a layer between the PSES general purpose language/debug services and an editor-specific adapter like the current one we have for the VSCode debug adapter and language protocols?  It would be interesting to try to adapt PSES to another editor (ISE / Sublime) just to make sure we aren't getting too VSCode specific.  Or are we OK with focusing only on VSCode?

**Comment by tylerl0706** [comment]
@daviwil Looks like the renaming happened. Can we close this?
