### ISSUE TITLE
PSRemotingDataStructureException thrown when stopping debugger in remote session

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#495]
This seems to have appeared after the 1.2.0 release (or possibly 1.1.0).  If you enter a remote PSSession and start debugging a script there, clicking the Stop button will cause a PSRemotingDataStructureException to be thrown which stops the pipeline and causes the command loop to halt (without crashing the server).

Not sure what's causing this exception yet, need to investigate it.

**Comment by daviwil** [comment]
Current work on a fix is here: https://github.com/daviwil/PowerShellEditorServices/commit/08799a27ea8438b4f8882a65f6c914a39ca06fbb

**Comment by tylerl0706** [comment]
I can't seem to repro this - is it cool if I close it?

**Comment by daviwil** [comment]
Close it for now, if anyone else sees it we can reopen.

**Comment by tylerl0706** [comment]
Thanks!
