### ISSUE TITLE
Construct $psEditor at runtime using Add-Member

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#506]
This is an early idea, so please feel free to give feedback and tell me if I sound crazy ;)

I'm gradually converting the PSES codebase over to the "feature component and provider" model which will allow us to separate certain features out into individual modules for greater flexibility.  The core extensibility mechanism is done through components written in C# but we also need to make sure that we provide a nice scripting interface where necessary so that C# code isn't needed.

One idea I had is to allow extension modules to dynamically add new methods and properties to the base $psEditor object module using the `Add-Member` cmdlet.  This would allow new functionality to be added to the right place without having to add a new top-level object on $psEditor for each extension module.

For example, the first module I plan to create in this model is "Microsoft.PowerShell.EditorServices.VSCode" which will provide functionality that only applies to the PowerShell extension in VS Code.  The default $psEditor.Window object would have methods that are generally applicable to editors that leverage PSES, but the VSCode module would be able to add a `ShowDocumentPreview` method there which causes VS Code to show a document preview for a particular file (like a Markdown or HTML file).

Another option is to eschew an object model completely and go with a cmdlet-based model, though I'm not entirely sure what that would look like.

Thoughts?

**Comment by SeeminglyScience** [comment]
I don't see a big problem with it, except I would avoid `ScriptMethod` because there isn't a way (that I know of) to declare parameters or return type in a way discoverable by `Get-Member`.  I can't think of any issues with `CodeMethod` though.

Would it be better to use `Update-TypeData`? You could assign the members to a `PSTypeName`, and then add or remove groups of members at a time by adding or removing the type name.

**Comment by tylerl0706** [comment]
This is an interesting idea that I think we should still discuss. Correct me if I'm wrong, but "Microsoft.PowerShell.EditorServices.VSCode" exists now, right? And is used to render HTML in VSCode?

**Comment by daviwil** [comment]
I've actually moved away from this line of thinking after filing this.  Instead of adding a bunch of stuff onto $psEditor in undiscoverable ways, it makes more sense to have extension modules expose PowerShell commands.  The PowerShellEditorServices.VSCode module is the first example of such an API extension.  I think this issue can be closed for now.
