### ISSUE TITLE
ISE Theme improvement

### ISSUE THREAD

**Issue by stefanstranger** [PowerShell/PowerShellEditorServices#511]
Please change the setting for the ISE Theme so you can see the dash when interactively typing to:
```
"colors": {
		"activityBar.background": "#E1ECF9",
		"activityBar.foreground": "#A9A9A9",
		"activityBarBadge.background": "#A9A9A9",
		"editor.lineHighlightBackground": "#add8e6",
		"editor.selectionBackground": "#94c6f7",
		"statusBar.background": "#999999",
		"statusBar.debuggingBackground": "#FF4500",
		"statusBar.noFolderBackground": "#999999",
		"terminal.background": "#012456",
		"terminal.foreground": "#F5F5F5"
	}
```

Changed editor.lineHighlightBackground setting from **#94c6f7** to **#add8e6**

/Stefan

**Comment by stefanstranger** [comment]
Can be deleted published in wrong repo. Check https://github.com/Microsoft/vscode/issues/28525

/Stefan

**Comment by daviwil** [comment]
It actually belongs in the https://github.com/PowerShell/vscode-powershell repo :)

**Comment by daviwil** [comment]
This issue was moved to PowerShell/vscode-powershell#864
