### ISSUE TITLE
Feature Request - Region support [#region myRegion]

### ISSUE THREAD

**Issue by CombineLabs** [PowerShell/PowerShellEditorServices#527]
Not sure if was working and now broken if never added

This would be super useful to me =)

#region myRegion
#endregion

**Comment by daviwil** [comment]
This is an ongoing feature request against VS Code itself, still needs to become aware of language-specific folding blocks.  Keep an eye on this issue to know when it gets resolved.

https://github.com/Microsoft/vscode/issues/3422

Closing this in favor of the other issue.  Thanks!
