### ISSUE TITLE
Consider a standard PowerShell name for psedit and make psedit an alias

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#528]
Perhaps we call the command `Open-FileInVSCode` or if it is editor independent - `Open-FileInEditor`?

**Comment by daviwil** [comment]
We can definitely do that.  Once I start adding workspace cmdlets I'll alias `Open-TextDocument` (or whatever I call the noun) as `psedit`.

**Comment by tylerl0706** [comment]
This looks like a low hanging fruit.

**Comment by daviwil** [comment]
It'll be easy but we should probably discuss naming and whatnot first

**Comment by tylerl0706** [comment]
I like `Open-FileInEditor` since it's not specific to VSCode but it's specific to say that the file will open in the editor.

Thoughts?

**Comment by daviwil** [comment]
I think we need a more noun-centric approach, like `WorkspaceFile` or `TextDocument` so that there can be `Open`, `New`, `Save`, `Close,` etc verbs.  I think at the time I filed this I was trying to make up my mind whether I wanted to use the Language Server Protocol nomenclature of `TextDocument` or something else.  I suppose it could be `EditorFile`.

@rkeithhill and @SeeminglyScience, any other possibilities here?

**Comment by SeeminglyScience** [comment]
I think it's important that `Editor` be somewhere in the noun. My vote goes to `EditorFile` or maybe `EditorDocument` but discoverability might not be great on the latter.  I really like `TextDocument` as well but I feel like it only makes sense if you're familiar with the language server which won't be the case for most.

**Comment by rkeithhill** [comment]
I like `Open-EditorFile`. We already have `Import/Register/Unregister-EditorCommand`.  So `EditorFile` as a noun, fits in nicely.

**Comment by daviwil** [comment]
Cool!  Let's use `EditorFile` then.  I think anything else could be confusing or hard to find.  Maybe it's best to add the rest of the cmdlets when the `Open` variant is added?

**Comment by SeeminglyScience** [comment]
While we're talking about it, also `Get-EditorContext` and `Get-EditorCommand`

**Comment by daviwil** [comment]
Definitely `Get-EditorContext` too.  What might someone use `Get-EditorCommand` for?

**Comment by SeeminglyScience** [comment]
Same thing you use any `Get-` command for ;)

Mostly just information, but also for piping to other commands like `Unregister-EditorCommand`

**Comment by daviwil** [comment]
Ahhh, cool, makes sense :)  Definitely, `Get | Unregister` makes sense.
