### ISSUE TITLE
Split PowerShellEditorServices.Protocol library into its own standalone project

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#53]
The PowerShellEditorServices.Protocol library has been generalized to the point where it could be used for any C# application that wanted to expose a language service.  It will be good to make this a separate library which is not PowerShell specific so that anyone could use it for this purpose.

cc @trondhindenes @AdamM52

**Comment by killerall** [comment]
Hello,
Is there any date to do this?

**Comment by SydneyhSmith** [comment]
Closing as this is tracked in #720
