### ISSUE TITLE
[VS Code Issue] $psEditor.Workspace.OpenFile() does not open some file paths E.g. OneDrive path

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/PowerShellEditorServices#546]
I have seen this issue for some time, however I cannot determine the cause.
Using VSCode, tried both x86 and x64, current VSCode version: 1.15.0

`$psEditor.EditorServicesVersion`
1.4.1.0

1. Example that works 

`New-Item -Path d:\test.ps1`

Directory: D:\
Mode                LastWriteTime         Length Name
-a----        8/12/2017   1:17 PM              0 test.ps1

`set-content -Path D:\test.ps1 -Value test`
`Get-Content -Path D:\test.ps1`

test

`$psEditor.Workspace.OpenFile('D:\test.ps1')`

> --> File opens in VS Code as expected.

2. Example that does not work (Opening a file in the OneDrive directory)

`New-Item -Path D:\OneDrive\test.ps1`

Directory: D:\OneDrive
Mode                LastWriteTime         Length Name
-a----        8/12/2017   1:18 PM              0 test.ps1

`set-content -Path D:\onedrive\test.ps1 -Value test`
`Get-Content -Path D:\onedrive\test.ps1`

test

`$psEditor.Workspace.OpenFile('D:\onedrive\test.ps1')`

> --> File does not open in VS Code as expected.

If I use the File > Open menu (in vscode) the files opens just fine.

**Comment by daviwil** [comment]
Interesting, thanks for pointing this out.  I'll take a look!

**Comment by brwilkinson** [comment]
I couldn't see a resolution here, however wanted to link it anyway.

https://github.com/Microsoft/vscode/issues/27285

**Comment by daviwil** [comment]
Looks like the resolution is an [updated version of Electron in VS Code](https://github.com/Microsoft/vscode/issues/27285#issuecomment-326280416) which won't appear until VS Code 1.16 (late Sept, early Oct).

**Comment by brwilkinson** [comment]
okay, yeah. . .

I tried that VSCode version linked with the backported fix, installed PowerShell Extension 1.4.2, I can confirm the issue is resolved.

`set-content -Path D:\onedrive\test.ps1 -Value test`
`Get-Content -Path D:\onedrive\test.ps1`

test

`$psEditor.Workspace.OpenFile('D:\onedrive\test.ps1')`

> File opens in VS Code as editor as expected  :)

**Comment by daviwil** [comment]
Thanks for giving it a shot!  I'll keep this bug open until a VS Code update comes out with a fix.

**Comment by daviwil** [comment]
I think VS Code team fixed this one a while back.

**Comment by brwilkinson** [comment]
Thanks @daviwil yeah all good. Still looking for a .saveas( ) however.
