### ISSUE TITLE
Upgrade to .NET Standard 2.0

### ISSUE THREAD

**Issue by elovelan** [PowerShell/PowerShellEditorServices#549]
Happy to submit a PR, but want to make sure this is in the cards first. Biggest impact seems to be pulling in `Microsoft.PowerShell.SDK` `6.0.0-beta.*`, which changes the target runtime from `netstandard1.6` to `netcoreapp2.0`.

I've done the changes on macOS and they work but I've yet to see the impact this has on Windows, especially targeting `net451` as the SDK NuGet package no longer has a `net4*` target. It may make little to no difference but that remains to be seen. Anyway, that's my next step before submitting a PR if this approach seems reasonable.

~~Other than keeping up with core PS libs, this also means no more dependencies on OpenSSL on macOS :smile:~~ - this happens automatically when .NET Core 2.0 runtime & PS 6.0-beta1+ are installed

**Comment by elovelan** [comment]
Seems PowerShell 6 needs some work first per:

https://github.com/PowerShell/PowerShell/issues/1152#issuecomment-315243874
https://github.com/PowerShell/PowerShell/issues/4374
and probably https://github.com/PowerShell/PowerShell/issues/3417 so this doesn't have to be hacked manually

should I keep this open to track this or close?

**Comment by rkeithhill** [comment]
Did you see this PR from two weeks ago?  

https://github.com/PowerShell/PowerShellEditorServices/pull/547 

IIRC there are some dependencies (RefEmit, etc) of the PS SDK that require it to base on netcoreapp2.0 instead of netstandard2.0.

**Comment by elovelan** [comment]
I did not see that PR though I did notice that there were test projects running under `netcoreapp2.0`.

I'm hoping `PowerShell` adopts the recommendation at https://github.com/PowerShell/PowerShell/issues/1152#issuecomment-319510051 or `PowerShellEditorServices` can eventually reference to upcoming reference assemblie(s).

If @daviwil is tracking this privately or has a different approach, happy to close this issue and wait

**Comment by daviwil** [comment]
Hey Eric, thanks a lot for looking into this!

I did try to get the PSES assemblies moved up to `netstandard2.0` a few weeks ago but ran into some complications with building for both that and `net451`, specifically around the current set of reference assemblies we (don't) ship for PowerShell 5.1.  Previously I was using the old 6.0.0-alpha* packages to get access to those APIs in the `net451` build but I can't do that any longer since the newer PowerShell SDK packages have dropped `net451` support.  I believe there was another issue relating to C# extensions to PSES having a more difficult build configuration so I shelved `netstandard2.0` migration for now.

Is there a particular reason why you need PSES to target `netstandard2.0`?  It loads perfectly well in the latest PowerShell Core builds even though it's built against `netstandard1.6`.

**Comment by rkeithhill** [comment]
FWIW, in this [CH9 video](https://channel9.msdn.com/Shows/On-NET/NET-Standard-Deep-Dive) Immo recommends that for libraries you target the lowest version of netstandard that will work (ie will compile).

**Comment by elovelan** [comment]
@daviwil, honestly my original motivation was due to the somewhat controversial symlink hack to get OpenSSL working on macOS. Happy to post links later if some background is needed as to why it's controversial.

@rkeithhill, can you please clarify your comment about targeting the lowest version of `netstandard`? I had expected that PSES would track https://github.com/PowerShell/PowerShell but maybe this is a misunderstanding on my part.

**Comment by rkeithhill** [comment]
@elovelan Start watching this [CH9 video ](https://channel9.msdn.com/Shows/On-NET/NET-Standard-Deep-Dive) at time index 28:13 for a few minutes.

**Comment by daviwil** [comment]
@elovelan Definitely aware of the controversy about symlinking the OpenSSL libraries.  Is it still necessary with the latest PowerShell Core that targets netcoreapp2.0?  Seems like we wouldn't need to change anything in our code to make user of .NET Core 2.0's improvements in that area.

**Comment by elovelan** [comment]
@daviwil, you are correct regarding not needing to change any code to support .NET Core improvements. There are still some issues with vscode support and documentation around OpenSSL, but that can be addressed in separate PRs. Sorry for conflating the two in my original comment, which I've updated.

While OpenSSL spurred my curiosity, my reason for pursuing the question was a genuine desire to help support the latest PowerShell Core SDK. However, given the lack of proper reference assemblies for the latest PS 6 betas, as I mentioned previously, there's not much that can be done.

@rkeithhill, I'm still not clear why you've posted the same video, which contains much of the same info as the [.NET Standard guide](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). Is your intent to continue supporting `netstandard1.6` even after the PS reference assemblies are released under `netstandard2.0`? This could be challenging, without continuing to reference the alpha assemblies due to the following [from the .NET Standard Guide](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#versioning):

> Given a .NET Standard version, you can use libraries that target that same or lower version.

**Comment by elovelan** [comment]
argh, seems there's already an issue tracking this! (should have searched with no spaces)

https://github.com/PowerShell/PowerShellEditorServices/issues/449

**Comment by rkeithhill** [comment]
@elovelan 

> Given a .NET Standard version, you can use libraries that target that same or lower version.

That is from the perspective of the application. The key is the "or lower version" part.  If the app targets .NET Core 1.0 it can use a netstandard 1.6 (or lower) library.  If an app targets `.NET Core 2.0`, it can use a netstandard 2.0 (**or lower**) library which includes libraries built against `netstandard1.6`.

**Comment by elovelan** [comment]
@rkeithhill, I'm still not understanding your point, I'm sorry. I suspect we may be talking about different things.

Here's what I'm wondering:

Given [Microsoft.PowerShell.SDK](https://powershell.myget.org/feed/powershell-core/package/nuget/Microsoft.PowerShell.SDK)'s and [System.Management.Automation](https://powershell.myget.org/feed/powershell-core/package/nuget/System.Management.Automation)'s current state of only supporting `netcoreapp2.0`, how can PSES continue to leverage the latest versions of these libs but still target `netstandard1.6`?

Would it be worthwhile to move this discussion to #449 since this may add to the discussion/implementation plan there?
