### ISSUE TITLE
Update docs for OpenSSL

### ISSUE THREAD

**Issue by elovelan** [PowerShell/PowerShellEditorServices#550]
Now the PS6-beta is out for macOS, OpenSSL symlink is no longer needed. Update docs

Note: this is a reminder for me to do this

**Comment by tylerl0706** [comment]
@elovelan Hey there! Are you talking about this section? https://github.com/PowerShell/PowerShellEditorServices#1-on-linux-or-macos-install-powershell-core

**Comment by elovelan** [comment]
yeah, thanks for the reminder, let me take a look within the next week or two
