### ISSUE TITLE
PowerShell Debug adapter terminates when using attach to host process

### ISSUE THREAD

**Issue by duffney** [PowerShell/PowerShellEditorServices#551]
When using the PowerShell attach to process option in the debugger the debugger adapter terminates unexpectedly. The integrated powershell terminal also terminates unexpectedly preventing you from using the debugger with other PowerShell process. 

![code_2017-09-24_13-06-29](https://user-images.githubusercontent.com/8146181/30862347-642fdcb6-a293-11e7-97a7-4a5295c3471c.png)

**Comment by rkeithhill** [comment]
I believe the offending exception originates from [here](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Session/PowerShellContext.cs#L456).  A task result is being set (apparently a second time) and an InvalidOpException happens - the ex message is:
```
    System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
       at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
       at Microsoft.PowerShell.EditorServices.PowerShellContext.<ExecuteCommand>d__48`1.MoveNext()
    ...
```

**Comment by kborowinski** [comment]
@rkeithhill @daviwil : Unfortunately it looks like the _attach to process_ is still crashing _PowerShellEditorServices_. I get _ProtocolEndpoint_UnhandledException_ in _EditorServicesHost.cs_ with PS 1.5.0 either on VSCode 1.17.2 or latest VSCode 1.18.0 insiders version. Logs attached.

[vsc_1_17_2_ps_1_5_0_logs.zip](https://github.com/PowerShell/vscode-powershell/files/1423999/vsc_1_17_2_ps_1_5_0_logs.zip)
[vsc_1_18_0_ps_1_5_0_logs.zip](https://github.com/PowerShell/vscode-powershell/files/1424000/vsc_1_18_0_ps_1_5_0_logs.zip)

**Comment by rkeithhill** [comment]
Yup, that's why this issue hasn't been closed.  We know where the bug is but are still looking for a way to fix the bug without breaking other behaviors.

**Comment by realonedet** [comment]
I am still experiencing this issue as well, i have tried new versions released through new test builds, still getting the error referenced here, very frustrating, is our only recourse to wait for an updated build of the plugin ?

**Comment by SeeminglyScience** [comment]
I suspect this will be fixed with all the changes PSReadLine brings.  A large amount of logic around how we execute commands had to be refactored to handle nested prompts.  No solid eta yet, but I would hold off attempting to fix this.  Current progress is in [this branch](https://github.com/SeeminglyScience/PowerShellEditorServices/tree/enable-psreadline).

**Comment by andyleejordan** [comment]
This has been long since fixed 😊
