### ISSUE TITLE
Variables that have changed since previous debug stop should be displayed with a "dirty" indicator

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#57]
This is borrowing another page from Visual Studio where it shows the value of a variable in a different color when the variable's value has changed since the previous debug stop e.g.:
![localvariabledirty](https://cloud.githubusercontent.com/assets/5177512/11551237/c4ebad56-9934-11e5-96f7-c8bb96334a15.png)
Doing this requires at least two new capabilities.  First we have to keep the previous debug stop's top level set of variables.  From what I can tell this feature doesn't need to support change indicator for when a composite variables properties or fields have changed.  Second, we need a way to compare objects (or determine that we can't compare objects).  

VSCode limits us in what we can display in the Variables tool window.  It doesn't let us color text for a specific variable value so we can't do it exactly like Visual Studio.  The current proposal is to display a changed variable like so:
```
Locals
  $i: 1 *
```

**Comment by daviwil** [comment]
Looks like VS Code team might implement this behavior on their side:

https://github.com/Microsoft/vscode/issues/866#issuecomment-161672767

**Comment by rkeithhill** [comment]
Saw that.  That would be way cool.

**Comment by rkeithhill** [comment]
VSCode has implemented this.  This is the new VSCode UI for dirty indicators"

![vscodechangedvariable](https://cloud.githubusercontent.com/assets/5177512/12766780/89dae740-c9c2-11e5-94f3-0050de9ea194.png)
