### ISSUE TITLE
[PSCore Align] Update contributing docs with top-level CONTRIBUTING.md

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShellEditorServices#585]
Opened the vscode equiv https://github.com/PowerShell/vscode-powershell/issues/1126 with @rkeithhill.

What we want:

A CONTRIBUTING.md being the top-level contributing guide (coding style, how to PR, expectations for a PR, etc) and then that can link to how to build and test the extension.

**Comment by tylerl0706** [comment]
right now, our docs are in the README and in http://powershell.github.io/PowerShellEditorServices/CONTRIBUTING.html
