### ISSUE TITLE
Test ServiceLoadsProfilesOnDemand fails with profile.ps1 present

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#591]
I still need to determine if it's something in my profile specifically or just the the fact that it's there.  In the mean time, if you run into this while building the project just rename your `profile.ps1` before starting the build.

**Comment by tylerl0706** [comment]
Thanks Patrick! So you're saying this test fails if there's a profile.ps1 present? Is that actually a `profile.ps1` or does that also include the Vscode profile - for example?

**Comment by SeeminglyScience** [comment]
Specifically `profile.ps1`.  The test uses a different host along with a profile for that custom host so the VSCode one doesn't come into play.

I'm not sure it's any time a `profile.ps1` is present or if it's because I have an unreasonably complicated profile ;)

I'll try to get that nailed down later, just wanted to get this issue up as information in case anyone building on their own failed on the test and went looking for answers.
