### ISSUE TITLE
Stepping into Import-LocalizedData crashes on Linux

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#593]
Looks like it attempts to create a temporary file to step into when it crashes.  Windows does this as well, but is successful.

It's throwing a unhandled `NullReferenceException` in the `RemoteFileManager` because the computer name isn't in the runspace session details.

If I remember correctly, it throws [here](https://github.com/PowerShell/PowerShellEditorServices/blob/3ed440643c8e6098dc18f2977ca4f6ea027ef00f/src/PowerShellEditorServices/Session/RemoteFileManager.cs#L361).

This probably also affects stepping into dynamically created scriptblocks

**Edit:** Actually it might be an `ArgumentNullException`.  I'll finalize the details later.

**Comment by tylerl0706** [comment]
Is this with debugging?

**Comment by SeeminglyScience** [comment]
@tylerl0706 Yeah, stepping into meaning pressing `F11` when the debugger is stopped on the `Import-LocalizedData` line.

But, the crash was because `ComputerName` was null.  Chances are you're unable to repo this because you already fixed it ;)

**Comment by tylerl0706** [comment]
Yep! That should be fixed with the change. I'll close this now and if we see it again, we can open a new one.
