### ISSUE TITLE
Need to handle the different Get-Content calls for different versions of pswh

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/PowerShellEditorServices#597]
PSCore removed `-Encoding Byte` for `-AsByteStream`. 

This line:
https://github.com/PowerShell/PowerShellEditorServices/blob/0f63e5c06e35f7445cb37734080c57d6a3620976/src/PowerShellEditorServices/Session/RemoteFileManager.cs#L50

We should handle this like:
```
$params = @{this=that}
if ($PSVersionTable.PSEdition -eq "Core")
{
    $params += @{AsByteStream=$true}
}
else
{
    $params += @{Encoding="Byte"}
}

Get-Content @params
```
This will fix at least 1 bug with psedit over ssh. This might actually fix psedit for PSCore on Windows.

**Comment by rkeithhill** [comment]
Good catch!

**Comment by tylerl0706** [comment]
@rkeithhill darn those PowerShell folks for breaking changes :P

**Comment by tylerl0706** [comment]
But wait, there's more to this "psedit over ssh" bug... Check this out:
https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Session/RemoteFileManager.cs#L356-L368

Notice the use of `computerName`?

On macOS and Linux, `$env:ComputerName` is null. I'm thinking we can just have a null check there and set it to some other unique identifier. Anyone have any ideas of what would also be a good enough identifier?

**Comment by rkeithhill** [comment]
Try this:
```
$ExecutionContext.Host.Runspace.ConnectionInfo.ComputerName
```
But you have to check for ConnectionInfo eq $null.  if it is, then use `localhost`.

**Comment by tylerl0706** [comment]
Where should I try that, exactly?

Here? https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Session/SessionDetails.cs#L55-L64

That's where the ComputerName gets set and ComputerName seems to be used throughout PSES. I worry about situations like this:
https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs#L388

That use `-ComputerName` when macOS and Linux don't have `$env:ComputerName` set.. @SteveL-MSFT is that by design, btw - macOS and Linux not having a ComputerName?

**Comment by rkeithhill** [comment]
Yes, modify that to something like:
```posh
"@{ 'computerName' = if ($ExecutionContext.Host.Runspace.ConnectionInfo) {$ExecutionContext.Host.Runspace.ConnectionInfo.ComputerName}  else {'localhost'}; ...
```
