### ISSUE TITLE
Tests needed for ReadKeyAsync changes

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellEditorServices#604]
Opening this issue as a reminder that tests need to be created for the changes to our internal `ReadKeyAsync` method.  From PR #592

**Comment by tylerl0706** [comment]
:) thanks!

**Comment by WernerMairl** [comment]
hi
i'm one of the issuer, now ready for a retest on Ubuntu...
where i can download/install the latest master build (assuming that the fix is merged) ?

i have found the following:

https://travis-ci.org/PowerShell/vscode-powershell/builds/333064180
but not able to find/download build output artifacts....

regards
Werner

**Comment by SeeminglyScience** [comment]
@WernerMairl this issue is about writing automated tests, but we'd love for you to try it out as well :)

1. Grab the build from `AppVeyor` [here](https://ci.appveyor.com/api/buildjobs/sk1qf096ecryddm9/artifacts/PowerShellEditorServices-1.5.1-1001.zip).  Note that this archive was built on Windows, some compression utilities won't automatically translate the Windows directory separators to Linux.  Ubuntu should thouhg.

1. In the integrated console, type `ii ((gmo PowerShellEditorServices.Commands).ModuleBase|Split-Path)`.  That should open the PSES folder within the extension in your file explorer.

1. Make sure all instances of VSCode are closed

1. Copy the contents of the PowerShellEditorServices folder from the zip into the window opened in step 1

1. If you get access denied errors, try running `gps pwsh|? id -ne $pid|spps` in a separate PowerShell window

**Note**: The changes in their current state could prevent the CPU from entering low power mode if you leave VSCode open.  That'll be fixed before this releases.
