### ISSUE TITLE
Support for VIM as shown in Powershell Azure Cloud Shell

### ISSUE THREAD

**Issue by itadder** [PowerShell/PowerShellEditorServices#608]
https://docs.microsoft.com/en-us/azure/cloud-shell/media/features-powershell/powershell-editing-vim.png
Microsoft says in their article "Rich PowerShell script editing
When you use VIM to edit PowerShell files (.ps1,.psm1,.psd1), you automatically get syntax highlighting and IntelliSense support. IntelliSense support is implemented via a vim-plugin that interacts with a local instance of PowerShell Editor Services." ( https://docs.microsoft.com/en-us/azure/cloud-shell/features-powershell )
![powershell-editing-vim](https://user-images.githubusercontent.com/6600157/34774584-e22535b0-f5dd-11e7-8908-17e92dfa5ebc.png)

Where can one download this plugin? Would like to use this outside of just clouds shell?

**Comment by SteveL-MSFT** [comment]
The VIM-plugin to integrate with PSEditorServices hasn't been published yet outside of CloudShell.  I expect it to be published as OSS in its own repo no later than next month.

**Comment by tylerl0706** [comment]
As Steve said, it's on our radar! I'll close this now as "answered" 👍

**Comment by itadder** [comment]
Thanks for the update

**Comment by frankk74** [comment]
Any chance of getting this?

Or is it out there somewhere else already?

**Comment by TylerLeonhardt** [comment]
I'm going to defer the answer of it being open sourced to @edyoung who owns the project. 

That said, @yatli prototyped a vim plugin a while back (I was able to get it working too) using https://github.com/autozimu/LanguageClient-neovim and PowerShell Editor Services and it worked really well!

Unfortunately, my time is spread thin to really properly maintain a project, but if someone out there is interested in taking a stab at building a proper package for it I can share learnings :)

**Comment by yatli** [comment]
hey @TylerLeonhardt I'm back!
this is my latest effort:
https://github.com/yatli/coc-pses

**Comment by TylerLeonhardt** [comment]
@yatli nice! I've been working with @corbob on this one - https://github.com/corbob/vim-powershell

**Comment by yatli** [comment]
I highly recommend to check it out. coc.nvim is great.

The key bindings can be pulled from my vimrc repo (v-yadli) and the overall experience is smooth.

**Comment by TylerLeonhardt** [comment]
@yatli are you in the PowerShell Community Slack or Discord? (aka.ms/psdiscord or aka.ms/psslack)
