### ISSUE TITLE
Using Find References on Linux causes Editor Services to crash with "too many open files"

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#612]
Seems we're hitting OS limits for file handles while walking the project's folder structure.

Relevant stack trace:

```
   System.AggregateException: One or more errors occurred. (Too many open files) ---> System.IO.IOException: Too many open files
       at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
       at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()
       at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)
       at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
       at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
       at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.LanguageService.<FindReferencesOfSymbol>d__18.MoveNext()
```

Related issues:

- vscode-powershell: https://github.com/PowerShell/vscode-powershell/issues/908
- ide-powershell: https://github.com/daviwil/ide-powershell/issues/1

**Comment by tylerl0706** [comment]
This + a `node_modules` folder makes PSES cry every time :(

**Comment by tylerl0706** [comment]
My debugger wont actually stop on the line... it's almost as if this exception is so bad, you can't break at it. Maybe you can't even catch it :(

**Comment by tylerl0706** [comment]
Wait I might have figured it out... 

The `Directory.EnumerateFiles` function has a 3rd overload where you pass in a `SearchOption` which can be `SearchOption.AllDirectories` which recurses down. This makes the function a matter of calling:

```c#
Directory.EnumerateFiles(
    folderPath,
    pattern,
    SearchOption.AllDirectories));
```

This call doesn't crash in a folder that crashed previously!

**Comment by tylerl0706** [comment]
The full function basically looks like this:

```c#
private static IEnumerable<string> EnumerateFiles(string folderPath) 
        {
            var foundFiles = Enumerable.Empty<string>();
            var patterns = new string[] { @"*.ps1", @"*.psm1", @"*.psd1" };

            foreach (var pattern in patterns)
            {
                try
                {
                    Console.Write("c");
                    foundFiles =
                        foundFiles.Concat(
                            Directory.EnumerateFiles(
                                folderPath,
                                pattern,
                                SearchOption.AllDirectories));
                    Console.Write("d");
                }
                catch (UnauthorizedAccessException e)
                {
                    Console.WriteLine(
                        $"Could not enumerate files in the path '{folderPath}' due to a file not being accessible",
                        e);
                }
            }


            return foundFiles;
        }
```

**Comment by rkeithhill** [comment]
I recommend you also catch `PathTooLongException` (assuming the EnumerateFiles can throw that exception) - just in case.  For these cases, I usually use C#'s exception filter mechanism so you don't have to repeat the contents of the multiple catch blocks.

**Comment by daviwil** [comment]
We were using this approach in the past, but the problem is that it stops enumerating on the first exception that it finds and there's no way to resume it:

https://github.com/PowerShell/PowerShellEditorServices/commit/0788a3eb55c99b330c8b77a97086ca3daabc8354#diff-7500716c7e03a30040a8f1664f42be23

We broke this out into our own loop so that we can catch the exceptions more granularly without interrupting the scan.

**Comment by tylerl0706** [comment]
Makes sense. So you don't think this is the right solution?

**Comment by daviwil** [comment]
Yeah, because if the first file/folder we look at throws an exception, none of the other files will be scanned, leaving the user to wonder why Find References, etc doesn't work.

**Comment by tylerl0706** [comment]
I get that... but if we use SearchOptions on Linux and Mac, that at least prevents a crash.

And looking at our exceptions, how often do they happen?
DirectoryNotFoundException - will only happen if given a bad folder path (not important)
PathTooLongException - not sure... but does this only happen on windows?
SecurityException, UnauthorizedAccessException - these seem rare to me... the user probably has to be working out of a protected folder or something but do people do that often?

The case I'm trying to make is that, I'd rather see no results than a crash on linux/mac.

Please correct me if I have something wrong or let me know what your thoughts are.

**Comment by tylerl0706** [comment]
btw globbingstar is on the .NET Core radar:
https://github.com/dotnet/corefx/issues/18922

**Comment by daviwil** [comment]
I think PathTooLongException only happens on Windows, but it's entirely possible to hit this when working on a project that's under a nested folder path if it has it's own deep folder tree.  Since users of Windows PowerShell greatly overwhelm any users of PowerShell on Linux or Mac, I think it makes sense to guard for cases that might be Windows-only while still giving the best possible language experience.

Before switching back to the old method, I'd recommend changing the current algorithm to not use the IEnumerable-returning EnumerateDirectories/EnumerateFiles since it will cause directory handles to be kept open while delving through larger file trees.  Here's the code where file enumeration happens on Unix machines:

https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs#L480

If you change those EnumerateDirectories/Files calls to GetDirectories/Files, it might take care of the problem.  There's really no benefit to using the Enumerate variety since we're not streaming the results back anyway, it just seemed to be the right thing to do at the time.

**Comment by tylerl0706** [comment]
@daviwil wow. Changing to Get* _just works_. Good call! I'll send out a PR
