### ISSUE TITLE
Stdout/stdin (pipe) protocol support

### ISSUE THREAD

**Issue by nanoant** [PowerShell/PowerShellEditorServices#634]
It seems that `PowerShellEditorServices` support only TCP protocol and cannot be ran as simply pipe (stdin/stdout) Language Service Server.

It there any change (plan) to add stdin/stdout support, this will enable integration with more Editors/IDEs such as Sublime Text LSP and VIM-LSP.

https://github.com/prabirshrestha/vim-lsp/issues/104
https://github.com/tomv564/LSP

**Comment by tylerl0706** [comment]
Sooner then you think :)

https://github.com/PowerShell/PowerShellEditorServices/pull/629

**Comment by tylerl0706** [comment]
If you hop in the PowerShellEditorServices gitter, there's some conversation on how to get that PR working with NeoVim 😀

**Comment by nanoant** [comment]
@tylerl0706 wow, thanks a lot :) Actually I am trying to make it working with Sublime Text 3 LSP plugin. I'll let you know if I get it running.

**Comment by tylerl0706** [comment]
Feel free to bug us on Gitter,  here, or the #vscode-contributors channel on the PowerShell slack! :) 

I'm all for getting new editors on board!

**Comment by tylerl0706** [comment]
Oh hey we did this 🎉 thanks to @yatli 😄

added in #629
