### ISSUE TITLE
Replace all instances of the Pipeline api with the PowerShell api

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/PowerShellEditorServices#646]
As mentioned in https://github.com/PowerShell/PowerShellEditorServices/pull/641, the [Pipeline](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.pipeline?view=powershellsdk-1.1.0) class is on the chopping block and was not included in PowerShell Standard.

We should replace all [Pipeline](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.pipeline?view=powershellsdk-1.1.0) class usages with the [PowerShell](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell?view=powershellsdk-1.1.0) class.

I think their APIs are pretty similar so the change is relatively straightforward so I'm making this as Up-for-Grabs

**Comment by dee-see** [comment]
This was already done in 2.0.0 by #690

**Comment by tylerl0706** [comment]
Nice catch. Closing
