### ISSUE TITLE
Get tests working in PowerShell Core & and Non-Windows

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/PowerShellEditorServices#648]
Right now, we have a ton of stuff hardcoded for Windows PowerShell like:

https://github.com/PowerShell/PowerShellEditorServices/blob/1e3234c82b1cff8f8457deaed617a85dab901ddf/test/PowerShellEditorServices.Test.Host/ServerTestsBase.cs#L99

Our tests should support running on Windows PowerShell & PowerShell Core - and be able to run on any OS.

**Comment by tylerl0706** [comment]
Marking Up-For-Grabs since I think it's relatively trivial, just a bit time consuming.

**Comment by glennsarti** [comment]
I'll take a crack at this.

**Comment by glennsarti** [comment]
@tylerl0706 Well, this may be an issue ...

Looks like tests are targetting different .Net versions than the actual code.

e.g. PowerShellEditorServices.Protocol is 
```
<TargetFrameworks>netstandard1.6;net451;</TargetFrameworks>
```

but the tests are
```
<TargetFrameworks>netcoreapp2.0;net452</TargetFrameworks>
```

This will not be an easy fix ...

**Comment by SeeminglyScience** [comment]
I could be wrong, but doesn't @rjmholt's netstandard migration PR do this already?

**Comment by glennsarti** [comment]
Hrmm ok ... yup that looks right.

This will probably be fixed in #741

Not really "Up For Grabs" anymore.

**Comment by tylerl0706** [comment]
Sorry @glennsarti, I've updated the issue

**Comment by rjmholt** [comment]
This has been merged in https://github.com/PowerShell/PowerShellEditorServices/pull/741
