### ISSUE TITLE
Investigate intermittent test hangs on AppVeyor

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#65]
Tests are randomly hanging on AppVeyor.  This happens both for library and host tests.  I still haven't uncovered the root of the issue yet but you can usually get past the issue by re-running the tests.  This isn't a long-term solution so we'll have to uncover the root cause soon.

**Comment by daviwil** [comment]
Turning off parallelized test runs in xUnit seems to have improved this somewhat but random tests still hang at times.  Will continue to investigate as issues come up.

**Comment by daviwil** [comment]
This seems to have improved a lot as many builds have completed with no issues.  Eventually I may turn parallelism back on since some code changes I made recently could have resolved the core issue.  We'll see how it goes.

**Comment by seesharper** [comment]
I had the same problem. Turning off parallel execution solved the problem. I think it might be related to a single core build agent which seems to be the default for open source projects at AppVeyor.

**Comment by daviwil** [comment]
Thanks Bernhard!  Glad I'm not the only one who experienced this.

On that note, I haven't actually seen a test hang in a while after the async timeout change so I'm going to close this issue for now.
