### ISSUE TITLE
Refactor Start-EditorServices.ps1 based on feedback

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShellEditorServices#656]
There is some feedback given in this PR of some parameter clean up:
https://github.com/PowerShell/PowerShellEditorServices/pull/629

It wasn't blocking for the PR so this is the issue to remember to do that refactoring.

**Comment by jpogran** [comment]
Most, if not all of the feedback mentioned seems to already have been accomplished in https://github.com/PowerShell/PowerShellEditorServices/commit/487ad1dac376e35578c4c7a173416ba76e0ecdd1. I think this can be closed

**Comment by TylerLeonhardt** [comment]
Yep! You're totally right. We can close this. @rjmholt will be refactoring it more (porting to a binary module) but that doesn't need this to be open.
