### ISSUE TITLE
power shell editor service crashes in Pester codelens

### ISSUE THREAD

**Issue by justin-romano** [PowerShell/PowerShellEditorServices#660]
Steps to reproduce
------------------
Sorry this is brief but there is no pattern and you most likely will tell by the logs i have posted what is going on.
1. Write some powershell code in vscode
2. Run the code using the vscode powershell debugger 

Expected behavior
-----------------
It should run without random crashes.

Actual behavior
---------------
it runs with random crashes. Sometimes i have to close vscode
I get the message "Debug adapter process has terminated unexpectedly"
Environment data

```powershell
Name                           Value
----                           -----
PSVersion                     5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
[EditorServices.log](https://github.com/PowerShell/PowerShellEditorServices/files/1965839/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/PowerShellEditorServices/files/1965840/vscode-powershell.log)

**Comment by tylerl0706** [comment]
Thanks for filing this! This particular crash seems to happen in the Pester codelens provider.

@rjmholt do you think you could look into this when you have a chance since you did some work in the Pester codlens code recently?

**Comment by rjmholt** [comment]
Looks like it's a null dereference here:
https://github.com/PowerShell/PowerShellEditorServices/blob/58fab2da05d0809471c7b30a7832487804846009/src/PowerShellEditorServices/Symbols/PesterDocumentSymbolProvider.cs#L200

I've opened a PR to fix.
