### ISSUE TITLE
Terminal History Artifacts

### ISSUE THREAD

**Issue by GHRoss** [PowerShell/PowerShellEditorServices#684]
PSReadLine 2.0.0
macOS High Sierra 10.13.4
PowerShell v6.1.0-preview.2
VS Code 1.24.0
PowerShell extension: 1.7.0-insiders-557

When going back in terminal history using the up cursor key, random 0A and 0B's are added to the end of the line.

This should be easy to recreate, but let me know if you'd like logs.

**Comment by rjmholt** [comment]
I've repro'd this. Even happens when you have no history

**Comment by GHRoss** [comment]
Just tried PSReadLine 2.0.0 in the macOS terminal (outside the VSCode integrated terminal) and got the same thing.

**Comment by rjmholt** [comment]
Same in Ubuntu18.04 -- might need to move the issue to the PSRL repo.

**Comment by tylerl0706** [comment]
Can we get a screenshot? FWIW I can't repro this before @SeeminglyScience's PR

**Comment by tylerl0706** [comment]
I can repro this in PSIC.

**Comment by GHRoss** [comment]
I've just tried this again in the macOS terminal and it seems OK now.

PSIC is still doing it though.

**Comment by tylerl0706** [comment]
@SeeminglyScience this is a V2 issue :)

**Comment by GHRoss** [comment]
@SeeminglyScience Let me know if you need me to test this.

**Comment by SeeminglyScience** [comment]
This was due to an issue in .NET Core related to how ANSI escape sequences were processed.  It is fixed in 2.1.1, which is included in PowerShell Core 6.1 preview 4.

Upstream issue: dotnet/corefx#29669

**Comment by tylerl0706** [comment]
we can close this in favor of that. I think we will mark PowerShell Core 6.0 on Unix (with the PSRL change) as not supported and unstable in favor of 6.1.

Note - 6.0 on Windows will work just fine AFAIK
