### ISSUE TITLE
Remove fully qualified type names from PSRL types when PSCore 6.0 goes out of support

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#746]
https://github.com/PowerShell/PowerShellEditorServices/blob/0a29e44f0cc45643adc8f2027bf7c80d8b994509/src/PowerShellEditorServices/Session/PSReadLinePromptContext.cs#L43

https://github.com/PowerShell/PowerShellEditorServices/blob/0a29e44f0cc45643adc8f2027bf7c80d8b994509/src/PowerShellEditorServices/Session/PSReadLinePromptContext.cs#L23

**Comment by TylerLeonhardt** [comment]
I guess we can do this now with #878 😊
