### ISSUE TITLE
Debug adapter process has terminated unexpectedly - VS Code

### ISSUE THREAD

**Issue by steven-cuthill-otm** [PowerShell/PowerShellEditorServices#751]
When running the Powershell debugger in VSCode there is a random chance for the Debug adapter process has terminated unexpectedly. there are no visible logs in the DevTools with the but this. this also can happen when restarting a script in the debugger. I can observe no pattern to why this works and does not work sometimes.

`Debug adapter process has terminated unexpectedly t.onDidNotificationChange @ notificationsAlerts.ts:41`

( macOS 10.13 ,PS 6.1 , VSC 1.27.1 )

**Comment by rjmholt** [comment]
Hi @steven-cuthill-otm, thanks for opening an issue.

Would you be able to provide [your logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)?

**Comment by steven-cuthill-otm** [comment]
Logs attached, not much to go from sadly.

Steve

**Comment by tylerl0706** [comment]
@steven-cuthill-otm attachments don't work when you respond via email 😢 can you attach via web

**Comment by tylerl0706** [comment]
Any chance you could attach those logs? @steven-cuthill-otm
