### ISSUE TITLE
PSEditorServices doesn't work when machine is DeviceGuard enabled

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShellEditorServices#754]
Enterprises that leverage DeviceGuard has PowerShell running in constrained language mode which prevents VSCode+PS from working.  Need to investigate what is happening and find appropriate solution.

**Comment by SeeminglyScience** [comment]
We could just convert the whole start up script to a cmdlet.  That would probably help with start up performance anyway.

**Comment by rjmholt** [comment]
I have been thinking about exactly that as well

**Comment by rjmholt** [comment]
As long as we can make it work properly across .NET platfroms, I'm onboard

**Comment by SeeminglyScience** [comment]
Side note so it doesn't get forgotten: Part of start up is creating a second runspace so we can use our custom host from `powershell.exe`/`pwsh`.  We'll need to make sure we propagate the language mode there.  We should also test that none of our internal commands (like the ones to get the call stack, computer name, etc) break in constrained language.

**Comment by SeeminglyScience** [comment]
@tylerl0706 Yeah.  The term "cmdlet" is sometimes used interchangeably with "command" but it does specifically refer to a command from a binary module.

**Comment by AndrewCi** [comment]
Any update on this? Is there a current workaround? Currently running into this issue with constrained language mode.

**Comment by rjmholt** [comment]
> Any update on this? Is there a current workaround? Currently running into this issue with constrained language mode.

No, [we currently don't support Constrained Language Mode](https://github.com/PowerShell/PowerShellEditorServices/blob/84a3d3f2ccb4af4e73ed5270712862d1242a6bad/module/PowerShellEditorServices/Start-EditorServices.ps1#L155-L163).

We haven't prioritised the work, but may be able to get it as part of other work we're doing this year.

**Comment by rjmholt** [comment]
Deduplicating this to https://github.com/PowerShell/vscode-powershell/issues/606

**Comment by jasonadsit** [comment]
I look forward to this getting fixed as well. VSCode not supporting constrained language mode has been a stumbling block for me for awhile now as well.

**Comment by Jared-Harrington-Gibbs** [comment]
I've also encountered this issue and I'm definitely looking forward to this getting fixed.

**Comment by TylerLeonhardt** [comment]
@Jared-Harrington-Gibbs can you try the [PowerShell Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview) extension? That should have support for Constrained Language Mode. 

We can close this issue since this is in the PowerShell Preview extension.
