### ISSUE TITLE
Ignore .dotfiles

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShellEditorServices#817]
Today, we recursively look in the current directory for PowerShell files without any filter.

This includes .dotfiles like .git which contains a bunch of stuff we should be ignoring.

We'll see some performance gains if we ignore dotfiles and/or honor the `files.exclude` setting that's already built into vscode

**Comment by rjmholt** [comment]
See https://github.com/PowerShell/vscode-powershell/issues/1039
