### ISSUE TITLE
Table width not calculated correct when using VT100

### ISSUE THREAD

**Issue by thordreier** [PowerShell/PowerShellEditorServices#840]
Table width not calculated correct when using VT100.

https://docs.microsoft.com/en-us/powershell/wmf/5.1/console-improvements states "PowerShell will ignore certain VT100 formatting escape sequences when calculating table widths". This is true in "plain" PowerShell, but not in VSCode.

This example demonstrates the problem:

```
# Create object with VT100 escape sequences
$x = [PSCustomObject]@{
    A = 'NoColor'
    B = "$([char](27))[33;1mColor$([char](27))[0m"
    C = 'NoColor'
}

# Auto size the columns
$x

# Set column width to 10
$x | Format-Table -Property @{L='A';E={$_.A};W=10},@{L='B';E={$_.B};W=10},@{L='C';E={$_.C};W=10}

# Column width is only 4 - this does not work anywhere!
$x | Format-Table -Property @{L='A';E={$_.A};W=4},@{L='B';E={$_.B};W=4},@{L='C';E={$_.C};W=4}
```

This example...:
- Does not work in VSCode - the VT100 sequence characters is included in the character count for table width
- Works in "plain" PowerShell on Windows 10 (not the four wide example)
- Does not work in ISE (but $host.UI.SupportsVirtualTerminal is $false - so VT100 doesn't work at all here)

**Comment by SydneyhSmith** [comment]
@thordreier thanks for pointing this out, I am able to easily reproduce this result. I am calling this an enhancement because it is not available in the ISE, but it does seem like a reasonable ask.

**Comment by rjmholt** [comment]
See also: https://github.com/PowerShell/PowerShell/issues/7744

**Comment by rjmholt** [comment]
@rkeithhill also had some good discussion in that issue

**Comment by SeeminglyScience** [comment]
This works in `ConsoleHost` because of a custom `PSHostRawUserInterface.LengthInBufferCells` implementation.  The default call just returns `string.Length`, but it should call `internalRawUI.LengthInBufferCells`.
