### ISSUE TITLE
where is Import-EditorCommand?

### ISSUE THREAD

**Issue by seadba** [PowerShell/PowerShellEditorServices#841]
hi - im curious as to where i can get Import-EditorCommand - if i import these mods i dont see it

PS C:\WINDOWS\system32> get-command -module powershelleditorservices

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Compress-LogDir                                    1.10.3     powershelleditorservices
Function        Get-PowerShellEditorServicesVersion                1.10.3     powershelleditorservices
Function        Start-EditorServicesHost                           1.10.3     powershelleditorservices

PS C:\WINDOWS\system32> import-module powershelleditorservices.vscode
PS C:\WINDOWS\system32> get-command -module powershelleditorservices.vscode

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Close-VSCodeHtmlContentView                        0.2.0      powershelleditorservices.vscode
Function        New-VSCodeHtmlContentView                          0.2.0      powershelleditorservices.vscode
Function        Set-VSCodeHtmlContentView                          0.2.0      powershelleditorservices.vscode
Function        Show-VSCodeHtmlContentView                         0.2.0      powershelleditorservices.vscode
Function        Write-VSCodeHtmlContentView                        0.2.0      powershelleditorservices.vscode

thanks

**Comment by TylerLeonhardt** [comment]
`Import-EditorCommand` comes from `PowerShellEditorServices.Commands` which should be available by default in PowerShell Editor Service's "PowerShell Integrated Console". The source code is [here](https://github.com/PowerShell/PowerShellEditorServices/blob/master/module/PowerShellEditorServices/Commands/Public/Import-EditorCommand.ps1)

Are you not seeing it?

**Comment by seadba** [comment]
thanks - its odd - in vscode the module is imported  -im sure its a config issue on my end but i cant quite figure it out

PS C:\projects\scripts> Import-EditorCommand -Module EditorServicesCommandSuite
Import-EditorCommand : The term 'Import-EditorCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Import-EditorCommand -Module EditorServicesCommandSuite
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Import-EditorCommand:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by SeeminglyScience** [comment]
> thanks - its odd - in vscode the module is imported -im sure its a config issue on my end but i cant quite figure it out

@seadba when you say the module is imported, do you mean it's imported automatically or you've manually imported it?

I ask because `PowerShellEditorServices.Commands` is imported during the start up of the integrated console, so if you don't see that module you may not be in the console created by the PowerShell extension.  If you aren't in that console, neither `EditorServicesCommandSuite` nor `PowerShellEditorServices.Commands` will work.

Can you paste the script below into the console you are trying to get this to work on and include the output here?

```powershell
Get-Module; $psEditor; $Host
```

**Comment by seadba** [comment]
thanks - im very sorry for wasting your time with this and i greatly appreciate it - i set the imports in both profile.ps1 files  - 


PS C:\projects\scripts> Get-Module; $psEditor; $Host

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.1      AZ
Script     1.0.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     1.0.0      Az.Aks                              {Get-AzAks, Import-AzAksCredential, New-AzAks, Remove-AzAks...}
Script     1.0.0      Az.AnalysisServices                 {Add-AzAnalysisServicesAccount, Export-AzAnalysisServicesInstanceLog, Get-AzAnalysisServicesServer, New-AzAnalysisServicesFirewallConfig...}
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserToGroup...}
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuousExport, New-AzApplicationInsights...}
Script     1.0.0      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAccount...}
Script     1.0.0      Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeScheduling, Disable-AzBatchJob, Disable-AzBatchJobSchedule...}
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzConsumptionBudget, Get-AzConsumptionMarketplace...}
Script     1.0.0      Az.Cdn                              {Confirm-AzCdnEndpointProbeURL, Disable-AzCdnCustomDomain, Enable-AzCdnCustomDomain, Get-AzCdnCustomDomain...}
Script     1.0.0      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}
Script     1.0.0      Az.Compute                          {Add-AzContainerServiceAgentPoolProfile, Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent...}
Script     1.0.0      Az.ContainerInstance                {Get-AzContainerGroup, Get-AzContainerInstanceLog, New-AzContainerGroup, Remove-AzContainerGroup}
Script     1.0.0      Az.ContainerRegistry                {Get-AzContainerRegistry, Get-AzContainerRegistryCredential, Get-AzContainerRegistryReplication, Get-AzContainerRegistryWebhook...}
Script     1.0.0      Az.DataFactory                      {Get-AzDataFactory, Get-AzDataFactoryActivityWindow, Get-AzDataFactoryDataset, Get-AzDataFactoryGateway...}
Script     1.0.0      Az.DataLakeAnalytics                {Add-AzDataLakeAnalyticsDataSource, Add-AzDataLakeAnalyticsFirewallRule, Get-AzDataLakeAnalyticsAccount, Get-AzDataLakeAnalyticsCatalogItem...}
Script     1.0.0      Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeStoreItemContent, Add-AzDataLakeStoreTrustedIdProvider, Add-AzDataLakeStoreVirtualNetworkRule...}
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.0.0      Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-AzDnsZone, New-AzDnsRecordConfig...}
Script     1.0.0      Az.EventGrid                        {Get-AzEventGridSubscription, Get-AzEventGridTopic, Get-AzEventGridTopicKey, Get-AzEventGridTopicType...}
Script     1.0.0      Az.EventHub                         {Get-AzEventHub, Get-AzEventHubAuthorizationRule, Get-AzEventHubConsumerGroup, Get-AzEventHubGeoDRConfiguration...}
Script     1.0.0      Az.HDInsight                        {Add-AzHDInsightClusterIdentity, Add-AzHDInsightComponentVersion, Add-AzHDInsightConfigValues, Add-AzHDInsightMetastore...}
Script     1.0.0      Az.IotHub                           {Add-AzIotHubCertificate, Add-AzIotHubEventHubConsumerGroup, Add-AzIotHubKey, Add-AzIotHubRoute...}
Script     1.0.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount...}
Script     1.0.0      Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountCallbackUrl, Get-AzIntegrationAccountCertificate...}
Script     1.0.0      Az.MachineLearning                  {Add-AzMlWebServiceRegionalProperty, Export-AzMlWebService, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlan...}
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Get-AzMediaService, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability, New-AzMediaService...}
Script     1.0.0      Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzWebtestAlertRule...}
Script     1.0.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSettings, Add-AzApplicationGatewayCustomErro...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}
Script     1.0.0      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsightsLinuxPerformanceCollection, Disable-AzOpera...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyRemediation, Get-AzPolicyState, Get-AzPolicyStateSummary...}
Script     1.0.0      Az.PowerBIEmbedded                  {Get-AzPowerBIEmbeddedCapacity, Get-AzPowerBIWorkspace, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys...}
Script     1.0.0      Az.RecoveryServices                 {Backup-AzRecoveryServicesBackupItem, Disable-AzRecoveryServicesBackupProtection, Disable-AzRecoveryServicesBackupRPMountScript, Edit-AzRecoveryServicesAsrRecoveryPlan...}
Script     1.0.0      Az.RedisCache                       {Export-AzRedisCache, Get-AzRedisCache, Get-AzRedisCacheFirewallRule, Get-AzRedisCacheKey...}
Script     1.0.0      Az.Relay                            {Get-AzRelayAuthorizationRule, Get-AzRelayHybridConnection, Get-AzRelayKey, Get-AzRelayNamespace...}
Script     1.0.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication...}
Script     1.0.0      Az.ServiceBus                       {Complete-AzServiceBusMigration, Get-AzServiceBusAuthorizationRule, Get-AzServiceBusGeoDRConfiguration, Get-AzServiceBusKey...}
Script     1.0.0      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.0.0      Az.SignalR                          {Get-AzSignalR, Get-AzSignalRKey, New-AzSignalR, New-AzSignalRKey...}
Script     1.0.0      Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlManagedInstanceTransparentDataEncryptionCertificate, Add-AzSqlServerKeyVaultKey, Add-AzSqlServerTransparentDataEncryptionCertificat...
Script     1.0.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountNetworkRule, Disable-AzStorageDeleteRetentionPolicy, Disable-AzStorageStaticWebsite...}
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsDefaultFunctionDefinition, Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsInput, Get-AzStreamAnalyticsJob...}
Script     1.0.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Add-AzTrafficManagerEndpointConfig, Add-AzTrafficManagerExpectedStatusCodeRange...}
Script     1.0.0      Az.Websites                         {Edit-AzWebAppBackupConfiguration, Enter-AzWebAppContainerPSSession, Get-AzAppServicePlan, Get-AzAppServicePlanMetrics...}
Binary     1.0.0.0    CimCmdlets                          {Export-BinaryMiLog, Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance...}
Script     1.1.162    dbachecks                           {Clear-DbcPowerBiDataSource, Export-DbcConfig, Get-DbcCheck, Get-DbcConfig...}
Script     0.9.734    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}
Script     0.4.0      EditorServicesCommandSuite          {Add-CommandToManifest, Add-ModuleQualification, Add-PinvokeMethod, ConvertTo-FunctionDefinition...}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}
Script     4.4.4      Pester                              {Add-AssertionOperator, AfterAll, AfterEach, AfterEachFeature...}
Script     1.1.3      Plaster                             {Get-PlasterTemplate, Invoke-Plaster, New-PlasterManifest, Test-PlasterManifest}
Script     1.10.3     PowerShellEditorServices            {Compress-LogDir, Get-PowerShellEditorServicesVersion, Start-EditorServicesHost}
Script     0.10.30... PSFramework                         {Remove-PSFNull, Select-PSFObject, Set-PSFConfig, Test-PSFShouldProcess...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler...}
Script     0.2.0      PSStringTemplate                    {Invoke-StringTemplate, New-StringTemplateGroup}

Name             : ConsoleHost
Version          : 5.1.17134.407
InstanceId       : 949d4212-3936-4201-acc3-7b390be19e1e
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by seadba** [comment]
awesome - i had it in the vscode_profile but didnt have the integrated console running - thanks very much -
