### ISSUE TITLE
Add choice prompt handling in PSHostUserInterface implementation

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#85]
The PSHostUserInterface implementation should implement the [PromptForChoice](https://msdn.microsoft.com/en-us/library/system.management.automation.host.pshostuserinterface.promptforchoice(v=vs.85).aspx) method which would allow a choice prompt to be shown to the user under certain circumstances.

My plan is to show the prompt in the REPL by default but also allow a custom prompt handler to be provided to `PowerShellContext.ExecuteCommand` calls so that prompt requests can be rerouted somewhere else (e.g. a prompt UI in the user's editor).

cc @dfinke

**Comment by dfinke** [comment]
Wire it up to showInputBox?

**Comment by daviwil** [comment]
Yep, the custom prompt handler would be used to send an event to VS Code to show the prompt using `showInputBox`.  I want to be able to change the way the prompt gets displayed contextually for operations like this.  In most cases the user is probably writing PowerShell code which shows a prompt so that prompt should appear in the REPL rather than the VS Code UI.
