### ISSUE TITLE
PS Integrated Console incorrect width

### ISSUE THREAD

**Issue by thomasrayner** [PowerShell/PowerShellEditorServices#865]
It doesn't look like the PS Integrated Console in VS Code actually knows how wide it is. In regular PowerShell.exe (or pwsh, if you prefer), you can look in `$host.ui.rawui.maxwindowsize.width` and get the number of cols wide the console is. In the PSIC in VS Code, this number is wrong.

If you run `write-host $(" " * $host.ui.rawui.maxwindowsize.width) -nonewline; "HERE"`, it should effectively write a blank line (space chars all the way across your screen) and then "HERE". The "HERE" should be on the start of it's own line. This is how it looks in the regular PowerShell console in VS Code.

![image](https://user-images.githubusercontent.com/13203965/51765488-c38fc400-208c-11e9-8ebd-2dbc35a384ca.png)

This is how it looks in the PSIC. I did not resize VS Code between these two screenshots.

![image](https://user-images.githubusercontent.com/13203965/51765473-b246b780-208c-11e9-911c-97e309d8c210.png)

**Comment by thomasrayner** [comment]
It looks like `$host.ui.rawui.buffersize.width` is correct so this isn't that big a deal, but it'd still be nice if the values were correct.

**Comment by vexx32** [comment]
Yes, please populate with proper values... Don't be another ISE. 😉 (ISE doesn't populate `$host.RawUI.WindowSize` at all, so this is still better, but... c'mon.) 

😄

**Comment by TylerLeonhardt** [comment]
IIRC @SeeminglyScience mentioned that `$host` is set when we first start up PSES (because we start it up IN pwsh), but is thrown away. This might be one of the things that can be preserved from the initial `$host` and get for free :)

**Comment by SeeminglyScience** [comment]
> IIRC @SeeminglyScience mentioned that $host is set when we first start up PSES (because we start it up IN pwsh), but is thrown away. This might be one of the things that can be preserved from the initial $host and get for free :)

Yep.  Right now it's just a constant, but we can definitely reuse `ConsoleHost` here.
