### ISSUE TITLE
Add diagnostic marker for dot-sourced file references that can't be found

### ISSUE THREAD

**Issue by kayladavis** [PowerShell/PowerShellEditorServices#9]
When dot sourcing a file that doesn't exist, a semantics level diagnostic marker should be created so that the user knows they are referencing an incorrect file path.

**Comment by daviwil** [comment]
This might be a nice Script Analyzer rule to add for a development ruleset, what do you think @kapilmb?

**Comment by kapilmb** [comment]
Yes, it looks like such a rule will be useful indeed!

**Comment by kapilmb** [comment]
Here is the issue: PowerShell/PSScriptAnalyzer#680

**Comment by tylerl0706** [comment]
Closing this here since the issue is opened in ScriptAnalyzer.
