### ISSUE TITLE
New-EditorFile error Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred."

### ISSUE THREAD

**Issue by SQLvariant** [PowerShell/PowerShellEditorServices#905]
Issue Type: <b>Bug</b>

When in a blank VS Code or ADS window (meaning no files open anywhere in the editor) and running New-EditorFile from the PowerShell Integrated Console, I receive the following error message:

"Exception calling "GetEditorContext" with "0" argument(s): "One or more errors occurred."
At C:\Users\Amanda\.azuredatastudio\extensions\ms-vscode.powershell-1.11.0\modules\PowerShellEditorServices\Commands\Public\CmdletInter
face.ps1:140 char:21
+ ...             $psEditor.GetEditorContext().CurrentFile.InsertText(($val ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException"

If I open at least one file of any type (.ps1, .sql) the error goes away.

Azure Data Studio version: azuredatastudio 1.6.0-insider (a4c2463b2f63c495f2840cefea6e74eda024777d, 2019-04-01T07:40:40.847Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
Nice catch - I have this fixed here: https://github.com/PowerShell/PowerShellEditorServices/pull/906
