### ISSUE TITLE
Expand-Archive does not expand the release zip files.

### ISSUE THREAD

**Issue by yatli** [PowerShell/PowerShellEditorServices#934]
see: https://github.com/yatli/coc-pses/blob/master/install.cmd
repro: download a release zip file. `Expand-Archive PowerShellEditorServices.zip`
expected: file expanded.
actual:
```
Expand-Archive : Cannot create "F:\git\coc-pses\PowerShellEditorServices\Plaster" because a file or directory with the
same name already exists.
At line:1 char:622
+ ... lease files;Expand-Archive $zip -Force -ErrorAction SilentlyContinue; ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Expand-Archive], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```

workaround: https://stackoverflow.com/questions/50106917/expand-archive-in-powershell-is-failing-to-extract-nested-folders-and-files

**Comment by rjmholt** [comment]
@yatli Can you elaborate on the PowerShell version you're using?

The zip was made using `Compress-Archive` and I can expand it with `Expand-Archive` using PowerShell 6.2 and PowerShell 5.1 on my Windows machine.

**Comment by yatli** [comment]
```powershell
echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by yatli** [comment]
hmm, is it about `PSCX`?

**Comment by yatli** [comment]
btw if you guys are still interested in a vim extension there it is :)

**Comment by yatli** [comment]
ok I can confirm, uninstalling Pscx solves the problem..
a bit weird though, Pscx is loaded even with `-NoProfile`

**Comment by rjmholt** [comment]
Is it on your module path? If so it might be taking precedence over the builtin Expand-Archive.

You can use a module-qualified command name if so:

```powershell
Microsoft.PowerShell.Archive\Expand-Archive ./PowerShellEditorServices.zip
```

**Comment by yatli** [comment]
yup, installed that to PROGRAM~1
Didn’t know the syntax of fully qualified names :p
