### ISSUE TITLE
Data tips only show once right after debug stop and not again until next debug stop

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#95]
Not sure what changed as I remember this working more consistently.

**Comment by daviwil** [comment]
Could be a VS Code bug, will have to investigate

**Comment by daviwil** [comment]
Just tried to repro this, I definitely see the issue. I don't see any requests to the debug adapter to get the variable values though so I think this must be a debugger client issue.  Just filed this issue against the VS Code repo:

https://github.com/Microsoft/vscode/issues/1804

**Comment by daviwil** [comment]
Looks like they've been making some improvements to data tips for the January release and the issue has already been fixed as a part of that.  I'll leave this bug open until we verify that it's working correctly after that release.

**Comment by rkeithhill** [comment]
The data tip behavior is still really wonky even in 0.10.7-insiders. Check this script out:
```powershell
$scriptVar = 'scriptVar'

function Test-Scope ($p1) {
    $foo = 42
    return $true
}

$p = Get-Process

Test-Scope bar
```
Set a breakpoint on the last line.  Start the debugger in 0.10.7-insiders.  Hover over `$scripvar` and `$p` - nothing. No F11 into Test-Scope and notice that you know get data tips for those two variables. Now in the callstack window, select <ScriptBlock>.  No you don't get data tips for those variables.  Select the Test-Scope stack frame and now you do.  Weird.  I wonder if in my work on variables and stack frame changes I've messed up the data tip mechanism.  

I'll try to take a look at this in the next day or two, since the new data tips in VSCode are pretty awesome.  I sure would like for them to work well for PowerShell.  If you have any pointers on where to look, let me know.

**Comment by rkeithhill** [comment]
Hmm, if I set a breakpoint on HandleVariablesRequest and attach the debugger, the breakpoints hits on some data tips (complex ones like array of process) but does not hit when I hover over variables and get no data tip.  So it is not something we mess up when retrieving the variable's value.  

How does VSCode know that the text under the cursor is a variable?  Is there another call it makes to understand that?  Is it using symbol info from the extension?

**Comment by daviwil** [comment]
Yeah, I think it must be using the tokenization from the syntax colorizer.  I've seen an issue recently where hovering over variables stops working at some point:

https://github.com/Microsoft/vscode/issues/1804

They say that they don't see it though.  I wonder if something about the way we send the response breaks their hover feature?  In the `DebugAdapter.log` do you see a request for the variable contents on subsequent hovers?

**Comment by rkeithhill** [comment]
For the one that work yes.  For the ones that don't no.

**Comment by tylerl0706** [comment]
Hey @rkeithhill + @daviwil, any idea where we left off with this issue? Looks like that vscode issue was closed but there still seems to be an action item for us?

**Comment by rkeithhill** [comment]
I just tried the repro and I don't see the problem anymore.  I'm closing it.
