### ISSUE TITLE
Exception: An unhandled exception occurred while listening for a named pipe client connection

### ISSUE THREAD

**Issue by corbob** [PowerShell/PowerShellEditorServices#954]
Following PR #878 On Windows 10, using Windows PowerShell, receive this exception when trying to run PSES. System.ArgumentException: Delegate to an instance method cannot have null 'this'. This does not happen with pwsh 6.2.0, it happens on Windows 10 builds 17763 (1809) and 18895 (Windows Insiders).

[1557806530-someValue.sessionId.zip](https://github.com/PowerShell/PowerShellEditorServices/files/3175896/1557806530-someValue.sessionId.zip)

**Comment by rjmholt** [comment]
@corbob Which PowerShell version did this happen with?

**Comment by rjmholt** [comment]
@corbob Can you include a screenshot? I'm interested in knowing where/how the exception is reported

**Comment by rjmholt** [comment]
Found it in the logs

**Comment by corbob** [comment]
Yeah, it doesn't report anything to the console. I have Diagnostic turned on, and it gets as far as `#-- Waiting for EditorServicesHost to complete execution ---------------------` and just hangs there. The exception (as you've found, but more for anyone else wanting to look at it) is in `EditorServices.log`


To answer the Version question, both 5.1.18895.1000 and 5.1.17763.1000

**Comment by rjmholt** [comment]
> and it gets as far as #-- Waiting for EditorServicesHost to complete execution --------------------- and just hangs there

I wouldn't quite characterise that as a hang; the server is still listening I think. But perhaps it should fall over there. There's another issue about the server shutting down by itself under certain conditions
