### ISSUE TITLE
[Request] Greater online presence

### ISSUE THREAD

**Issue by Priddles** [PowerShell/PowerShellEditorServices#969]
#### The Short
I would prefer to have known this project existed last year, when STDIO LSP mode became available.

#### The Long
Despite being aware of `vscode-powershell` ([GitHub](https://github.com/PowerShell/vscode-powershell), [PSGallery](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell)), I had not heard of its "backend" project until today.

This is frustrating because I had been waiting in vain for a PowerShell language server that supported STDIO. Since I am primarily a Neovim user, the VS Code extension was less than useful.

**Please try to get this project listed on sites such as [LangServer.org](https://langserver.org/) and Microsoft's own [LSP implementors list](https://microsoft.github.io/language-server-protocol/implementors/servers/)!**

**Comment by rjmholt** [comment]
As a neovim user, you might be interested in https://github.com/yatli/coc-powershell.

We'll look into those sites. They both look open source, so you might even be able to open a PR on them yourself.

**Comment by Priddles** [comment]
I did know about COC but was looking to configure PSES to work with my preferred LSP plugin [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim).

Thank you for the quick response!

**Comment by TylerLeonhardt** [comment]
@rjmholt I just sent https://github.com/PowerShell/vscode-powershell/pull/1996 which actually docs that vscode-powershell uses PSES.
