### ISSUE TITLE
FEATURE REQUEST: Intellisense for PSScriptAnalyzerSettings.psd1

### ISSUE THREAD

**Issue by travis-c-lagrone** [PowerShell/PowerShellEditorServices#973]
## FEATURE REQUEST: Intellisense for PSScriptAnalyzerSettings.psd1

Provide intellisense (suggestions and rule information) for any PSScriptAnalyzerSettings.psd1 file, wherein the intellisense is based on the expected format of PSSA files and the runtime value of `PSScriptAnalyzer\Get-ScriptAnalyzerRule`.

Ideally, there would also be an option to configure one or more custom rule paths, but that might constitute a separate feature request on account of editor configuration differences.

**Comment by rjmholt** [comment]
@travis-c-lagrone see https://github.com/PowerShell/PSScriptAnalyzer/issues/675#issuecomment-377783190 for your second request

**Comment by rkeithhill** [comment]
Seems like "schema for PSD1" files is a request that should be made on the PowerShell project.  Either that, or request an alternate format for settings that does support schema - like JSON.  For the PSSA settings file, I don't see a compelling reason to use PSD1 over JSON.

**Comment by rjmholt** [comment]
> or request an alternate format for settings that does support schema - like JSON. For the PSSA settings file, I don't see a compelling reason to use PSD1 over JSON.

Agreed

**Comment by travis-c-lagrone** [comment]
[PowerShell #4016](https://github.com/PowerShell/PowerShell/issues/4016) would address this feature request, but it hasn't seen any activity since 2017.  I've posted a question about progress, so we'll see what the answer is (if any).

**Comment by rjmholt** [comment]
We're working on a few other things at the moment. The easier thing to do might be to add JSON support in PSSA (I recently rewrote the PSD parsing for that and now would be a good time to add such support). I'd recommend opening an issue there

**Comment by TravisLaGrone** [comment]
@rjmholt I have opened [PSScriptAnalyzer #1254](https://github.com/PowerShell/PSScriptAnalyzer/issues/1254).

**Comment by travis-c-lagrone** [comment]
Closed as mis-scoped duplicate of [PSScriptAnalyzer #1254](https://github.com/PowerShell/PSScriptAnalyzer/issues/1254)
