### ISSUE TITLE
File path completions should not contain the current path prefix

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#98]
This is what I'm referring to here:

![filecompletionlist](https://cloud.githubusercontent.com/assets/5177512/12072931/f88fca44-b0bc-11e5-88a4-90b277a98fc6.png)

This would also make the extension behave like ISE WRT completing absolute paths.  

This would also mitigate an issue where the tooltip clips the end of the path:
![clipfilecompletionlist](https://cloud.githubusercontent.com/assets/5177512/12072939/93098236-b0bd-11e5-8b70-10d319951f2c.png)

**Comment by daviwil** [comment]
Interesting, looks like the ISE must be doing some post-processing of the completion results for paths.  I agree, this would be helpful!

**Comment by rkeithhill** [comment]
So I've been looking at this.  I figured out how to get VSCode to display different text in the tooltip vs what it injects into the doc.  It requires modifying this LanguageServer.cs method:
```csharp
internal static CompletionDetails Create(CompletionResult completionResult, int replacementLength)
{
    Validate.IsNotNull("completionResult", completionResult);

    // Some tooltips may have newlines or whitespace for unknown reasons
    string toolTipText = completionResult.ToolTip;
    if (toolTipText != null)
    {
        toolTipText = toolTipText.Trim();
    }

    var completionDetails = new CompletionDetails
    {
        CompletionText = completionResult.CompletionText,
        ToolTipText = toolTipText,
        SymbolTypeName = ExtractSymbolTypeNameFromToolTip(completionResult.ToolTip),
        CompletionType = 
            ConvertCompletionResultType(
                completionResult.ResultType)
    };

    if (completionDetails.CompletionType == CompletionType.Path)
    {
        completionDetails.CompletionText = completionDetails.CompletionText.Substring(replacementLength);
        completionDetails.ToolTipText = completionDetails.ToolTipText.Substring(replacementLength);
    }

    return completionDetails;
}
```
The problem is determining what text to remove from the tooltip.  I thought maybe that the `ReplacementLength` in the CommandCompletion object would work e.g.:
```csharp
internal static CompletionDetails Create(CompletionResult completionResult, int replacementLength)
{
    Validate.IsNotNull("completionResult", completionResult);

    // Some tooltips may have newlines or whitespace for unknown reasons
    string toolTipText = completionResult.ToolTip;
    if (toolTipText != null)
    {
        toolTipText = toolTipText.Trim();
    }

    var completionDetails = new CompletionDetails
    {
        CompletionText = completionResult.CompletionText,
        ToolTipText = toolTipText,
        SymbolTypeName = ExtractSymbolTypeNameFromToolTip(completionResult.ToolTip),
        CompletionType = 
            ConvertCompletionResultType(
                completionResult.ResultType)
    };

    // For completion items that are of type path, for the tooltip, let's A) use the ComplettionText
    // instead because the ToolTipText returned by PowerShell is always an absolute path. And B) let's
    // remove the beginning part of the path that has already been entered into the document.
    if ((completionDetails.CompletionType == CompletionType.Path) && 
        (completionResult.CompletionText != null))
    {
        int startIndex = replacementLength;
        if (startIndex < completionResult.CompletionText.Length)
        {
            completionDetails.ToolTipText = completionResult.CompletionText.Substring(startIndex);
        }
    }

    return completionDetails;
}
```
But no.  While this seems to work really well for paths without spaces, the `ReplacementLenght` value accounts for quotes typed in the doc e.g. `'C:\'` but those quotes get stripped off by the time I see the CompletionResult text.  So in the case of quoted paths, I strip off two extra chars at the beginning of the path. Somehow I need to "know" whether or not the path in the document was quoted.  Thoughts?

**Comment by daviwil** [comment]
Looks like there's an easy solution to this which I didn't catch before.  I checked the ISE codebase and it seems that `CompletionResult.ListItemText` is used as the text to display for the completion in the IntelliSense UI but `CompletionResult.CompletionText` as the string to insert.

I believe we'll need a new property on our `CompletionDetails` class called `DisplayText` which gets the value of `CompletionResult.ListItemText`.  Then in the `LanguageServer.CreateCompletionItem` class we'll need to assign `CompletionDetails.DisplayText` to `CompletionItem.Label`.  This should cause VS Code to show the right display text while still inserting the CompletionText as expected when the user confirms the IntelliSense choice.

**Comment by rkeithhill** [comment]
Yeah I've got the LanguageServer.CreateCompletionItem method figured out and working as it should (see my updated post above where I've actually pasted in the correct code instead of a dupe of the CompletionResult code - doh).

I can update CompletionDetails to add DisplayText but there is already a ToolTipText property.  Do we need both?  I guess the ToolTipText could be used in mouse over situations?  

Also, I need to see if ListItemText is appropriate for all the completion types.   Or would you prefer we limit the use of ListItemText to just completion type Path?

**Comment by daviwil** [comment]
ListItemText must be appropriate since the ISE uses it exclusively for this purpose.  I don't see any special casing for different completion types.  You should definitely feel free to try a few things to make sure that the text looks right, though.

The ToolTipText property should probably stay like it is for now.  I'm going to start using Editor Services in the ISE soon and it actually uses the tooltip text for showing a tooltip when IntelliSense is up.  It's a little misguided, but let's keep it that way until I come up with a better IntelliSense experience in the ISE.

**Comment by rkeithhill** [comment]
This is looking better.  The only problem I still have is when quotes are used e.g.
```
gc 'c:\us<tab-complete>'
```
completes correctly but doesn't put the caret at the end like it does when there are no quotes:
```
gc 'C:\Use|rs'
```
This only happens when you "complete" partially from within the string. If I were to type this:
```
gc 'C:'\use<tab-complete>
```
The caret winds up in the right spot:
```
gc 'C:\Users'|
```

**Comment by rkeithhill** [comment]
Hey, just realized the caret issue is not new.  I tried a stock 0.3.1 PSES install and it behaves the same way.  I'll do a bit more testing on this update and submit a PR in a day or two.

**Comment by daviwil** [comment]
Yep!  I just tried it and noticed the same thing.  I wonder if it's a VS Code thing?  Seems like they may preserve the caret location unnecessarily...  Not sure if there's another property that we need to set to make it work right.  Not a big problem for now.  Looking forward to the PR!

**Comment by rkeithhill** [comment]
OK I'm real close now but the three unit tests that test PS v3/4/5 are failing with:
```
Test Name:	CompilesWithPowerShellVersion(version: "3")
Test FullName:	Microsoft.PowerShell.EditorServices.Test.Language.PowerShellVersionTests.CompilesWithPowerShellVersion (34bf4ca4c5dcc9b9a818b38e82c1be4c08e436a5)
Test Source:	C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\test\PowerShellEditorServices.Test\Language\PowerShellVersionTests.cs : line 24
Test Outcome:	Failed
Test Duration:	0:00:00.142

Result StackTrace:	
at Microsoft.PowerShell.EditorServices.Test.Language.PowerShellVersionTests.Compile(String project, String version) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\test\PowerShellEditorServices.Test\Language\PowerShellVersionTests.cs:line 79
   at Microsoft.PowerShell.EditorServices.Test.Language.PowerShellVersionTests.CompilesWithPowerShellVersion(String version) in C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\test\PowerShellEditorServices.Test\Language\PowerShellVersionTests.cs:line 43
Result Message:	System.Exception : C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(723,5): error : The OutputPath property is not set for project '3.PowerShellEditorServices.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='X64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\Keith\GitHub\rkeithhill\PowerShellEditorServices\src\PowerShellEditorServices\3.PowerShellEditorServices.csproj]
```
Does the SLN file need to have an x64 solution platform added?  I only see AnyCPU at the SLN level.

**Comment by daviwil** [comment]
Huh, weird...  Did your Visual Studio's architecture dropdown get changed to x64 somehow?

![image](https://cloud.githubusercontent.com/assets/79405/12740066/818a6ac8-c924-11e5-8e3b-b9c260abcec5.png)

Try setting it to Any CPU if it's not that already.  If that doesn't help I'd check to see if the project files got manipulated by VS somehow.

**Comment by rkeithhill** [comment]
That's exactly how I have it configured.  And I just did a `git pull PowerShell master` and I'm up-to-date.

**Comment by daviwil** [comment]
In the error:

` error : The OutputPath property is not set for project '3.PowerShellEditorServices.csproj'`

Can you check that csproj file (it's generated in the src\PowerShellEditorServices path) and see if it doesn't have an OutputPath?  Not sure how the generation would have missed that but got it right for the other two.  Another thing to try would be commit your changes to a branch and then switch back to master to see if the problem goes away.  

If nothing jumps out at you, I can clone your code and give it a shot tomorrow.

**Comment by rkeithhill** [comment]
It does have that property and it's set to:
```xml
<OutputPath>bin\Debug\</OutputPath>
```
I'm trying to debug this unit test and right now I'm running MSBuild manually on the generated CSPROJ file.  No joy yet, but I'll keep plugging away at it.

**Comment by rkeithhill** [comment]
Getting close.  Something is setting an environment variable "Platform=X64" and that is messing up the build.

**Comment by rkeithhill** [comment]
Hmm, seems that the VS 2015 x64 native tools prompt defines the env var Platform=X64.  And the VS 2015 x86 native tools prompt defines it to Platform=X86. The latter works, the former doesn't.

**Comment by rkeithhill** [comment]
OK got past that problem by removing the "Platform" environment variable from the Process.StartInfo.  Now all the unit tests pass. But I'm a bit concerned about using ListItemText as the Label for all completion types.  I've identified two cases so far where I've needed to "tweak" the ListItemText.  

For variables the ListItemText doesn't have the `$` prefix (you can see this in ISE). This unfortunately prevents the drop-down from showing any variables unless I add it back in.  The same goes for Parameters except the prefix there is `-`.  

To be on the safe side, I think I'll use ListItemText just for the label of Path and Command completion types.  The will enable:

![completioncommandalias](https://cloud.githubusercontent.com/assets/5177512/12741532/7c7f675c-c93a-11e5-9246-0b6887566700.png)

and

![completioncommandapp](https://cloud.githubusercontent.com/assets/5177512/12741534/8280ef04-c93a-11e5-9ea5-5c04e88c8efc.png)

BTW I notice we don't complete .NET static methods `[System.Environment]::<tab>` and we don't provide xml doc comments for .NET method signatures.  Bummer.  

I see that we get back a basic signature (return type and parameters) in CommandCompletion but we don't currently display that.  Should we?  Seems like that would be nice and put us more on par with ISE?

**Comment by daviwil** [comment]
Jeez, did you just fix everything about IntelliSense? :)  All of your changes look great to me.  I also agree with not using ListItemText for the couple things that don't benefit from it.  I am fine with only using ListItemText for Path and Command results.

For the C# IntelliSense, I hadn't gotten around to it yet because I wanted to do the full signature help support so that you get the second popup with the available method signatures.  We can add that in a later release, but your current change helps a lot for the user to understand what they're calling.

Awesome work!
